# Hollywood Movie Data Analysis

## Project Overview

This project analyzes Hollywood movie data using Python, Pandas, and NumPy. The dataset contains information about movies, ratings, genres, studios, box-office collections, budgets, profitability, and release years.

## Objectives

- Explore the structure of the dataset.
- Identify missing and duplicate values.
- Analyze movie ratings and audience scores.
- Examine domestic, foreign, and worldwide gross.
- Study movie genres and lead studios.
- Analyze movie releases by year.
- Prepare the dataset for statistical analysis and visualization.

## Technologies Used

- Python
- Pandas
- NumPy
- Jupyter Notebook
- Matplotlib

## Dataset Features

| Column | Description |
|---|---|
| `Movie` | Movie title |
| `LeadStudio` | Lead production studio |
| `RottenTomatoes` | Rotten Tomatoes score |
| `AudienceScore` | Audience rating |
| `Story` | Movie story category |
| `Genre` | Movie genre |
| `TheatersOpenWeek` | Number of opening-week theaters |
| `OpeningWeekend` | Opening-weekend earnings |
| `BOAvgOpenWeekend` | Average box-office earnings |
| `DomesticGross` | Domestic earnings |
| `ForeignGross` | International earnings |
| `WorldGross` | Worldwide earnings |
| `Budget` | Production budget |
| `Profitability` | Movie profitability |
| `OpenProfit` | Opening profit |
| `Year` | Release year |

## Analysis Workflow

1. Install the required libraries.
2. Import Pandas and NumPy.
3. Load the CSV dataset.
4. Display the first and last records.
5. Examine dataset shape, data types, and statistical summaries.
6. Check missing values and duplicate records.
7. Remove duplicate records.
8. Explore unique values in each column.
9. Count movie, genre, studio, rating, and year occurrences.
10. Perform statistical analysis and create visualizations.

## Conclusion

This analysis provides an initial understanding of Hollywood movie data and establishes a foundation for future visualization, correlation analysis, outlier detection, and machine-learning projects such as box-office prediction and movie recommendation systems.

## 📦 Installing Required Libraries

This step installs the required Python libraries **NumPy** and **Pandas** for numerical computations and data analysis.

In [91]:
%pip install numpy pandas

Requirement already satisfied: numpy in c:\Users\Neha paswan\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.5.1)
Requirement already satisfied: pandas in c:\Users\Neha paswan\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Neha paswan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Neha paswan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\Neha paswan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

## 🐍 Check Python Environment

This section displays the path of the Python interpreter currently being used in the notebook. It helps verify the active Python environment and ensures that the installed libraries are available in the correct environment.

In [92]:
import sys
print(sys.executable)

c:\Users\Neha paswan\AppData\Local\Programs\Python\Python313\python.exe

## 🐼 Import Pandas Library

Pandas is a Python library used for data manipulation and analysis.  
This step imports the Pandas library and assigns it the alias **pd** for easier use throughout the notebook.

In [93]:
import pandas as pd

## 🔢 Import NumPy Library

NumPy is a Python library used for numerical computations and working with arrays.  
This step imports the NumPy library and assigns it the alias **np** for easier usage in the notebook.

In [94]:
import numpy as np

## 📂 Load Dataset

This step loads the **HollywoodMovies.csv** dataset into a Pandas DataFrame.  
The `read_csv()` function is used to read data from a CSV file, and the data is stored in the variable **df** for further analysis and processing.

In [95]:
df = pd.read_csv("HollywoodMovies.csv")

## 👀 Display First Few Rows

The `head()` function is used to display the first five rows of the dataset.  
It helps to quickly understand the structure, column names, and sample data present in the dataset.

In [96]:
df.head()

,Movie,LeadStudio,RottenTomatoes,AudienceScore,Story,Genre,TheatersOpenWeek,OpeningWeekend,BOAvgOpenWeekend,DomesticGross,ForeignGross,WorldGross,Budget,Profitability,OpenProfit,Year
0,Spider-Man 3,Sony,61.0,54.0,Metamorphosis,Action,4252.0,151.1,35540.0,336.53,554.34,890.87,258.0,345.30,58.57,2007
1,Shrek the Third,Paramount,42.0,57.0,Quest,Animation,4122.0,121.6,29507.0,322.72,476.24,798.96,160.0,499.35,76.00,2007
2,Transformers,Paramount,57.0,89.0,Monster Force,Action,4011.0,70.5,17577.0,319.25,390.46,709.71,150.0,473.14,47.00,2007
3,Pirates of the Caribbean: At World's End,Disney,45.0,74.0,Rescue,Action,4362.0,114.7,26302.0,309.42,654.00,963.42,300.0,321.14,38.23,2007
4,Harry Potter and the Order of the Phoenix,Warner Bros,78.0,82.0,Quest,Adventure,4285.0,77.1,17998.0,292.00,647.88,939.89,150.0,626.59,51.40,2007

## 📄 Display Last Few Rows

The `tail()` function is used to display the last five rows of the dataset.  
It helps to check the ending records and understand the overall structure of the dataset.

In [97]:
df.tail()

,Movie,LeadStudio,RottenTomatoes,AudienceScore,Story,Genre,TheatersOpenWeek,OpeningWeekend,BOAvgOpenWeekend,DomesticGross,ForeignGross,WorldGross,Budget,Profitability,OpenProfit,Year
965,The Canyons,IFC,22.0,NaN,NaN,NaN,1.0,0.01,13351.0,0.06,0.14,0.19,NaN,77.21,NaN,2013
966,The Call,TriStar,43.0,66.0,NaN,NaN,2507.0,17.12,6828.0,51.87,16.70,68.57,13.0,527.48,131.69,2013
967,The English Teacher,Cinedigm Entertainment,42.0,NaN,NaN,NaN,2.0,0.01,3001.0,0.10,0.06,0.10,NaN,NaN,NaN,2013
968,John Dies at the End,Magnolia,61.0,53.0,NaN,NaN,1.0,0.01,12467.0,0.14,NaN,0.14,1.0,14.20,1.00,2013
969,Lovelace,Radius-TWC,55.0,37.0,NaN,Biography,118.0,0.18,1564.0,0.36,1.17,1.52,10.0,15.25,1.80,2013

## 📊 Statistical Summary of Dataset

The `describe()` function provides a statistical summary of numerical columns in the dataset.  
It displays important information such as count, mean, standard deviation, minimum value, maximum value, and quartiles.

In [98]:
df.describe

<bound method NDFrame.describe of                                          Movie              LeadStudio  \
0                                 Spider-Man 3                    Sony
1                              Shrek the Third               Paramount
2                                 Transformers               Paramount
3     Pirates of the Caribbean: At World's End                  Disney
4    Harry Potter and the Order of the Phoenix             Warner Bros
..                                         ...                     ...
965                                The Canyons                     IFC
966                                   The Call                 TriStar
967                        The English Teacher  Cinedigm Entertainment
968                       John Dies at the End                Magnolia
969                                   Lovelace              Radius-TWC

     RottenTomatoes  AudienceScore          Story      Genre  \
0              61.0           54.0  Metamorphosis     Action
1              42.0           57.0          Quest  Animation
2              57.0           89.0  Monster Force     Action
3              45.0           74.0         Rescue     Action
4              78.0           82.0          Quest  Adventure
..              ...            ...            ...        ...
965            22.0            NaN            NaN        NaN
966            43.0           66.0            NaN        NaN
967            42.0            NaN            NaN        NaN
968            61.0           53.0            NaN        NaN
969            55.0           37.0            NaN  Biography

     TheatersOpenWeek  OpeningWeekend  BOAvgOpenWeekend  DomesticGross  \
0              4252.0          151.10           35540.0         336.53
1              4122.0          121.60           29507.0         322.72
2              4011.0           70.50           17577.0         319.25
3              4362.0          114.70           26302.0         309.42
4              4285.0           77.10           17998.0         292.00
..                ...             ...               ...            ...
965               1.0            0.01           13351.0           0.06
966            2507.0           17.12            6828.0          51.87
967               2.0            0.01            3001.0           0.10
968               1.0            0.01           12467.0           0.14
969             118.0            0.18            1564.0           0.36

     ForeignGross  WorldGross  Budget  Profitability  OpenProfit  Year
0          554.34      890.87   258.0         345.30       58.57  2007
1          476.24      798.96   160.0         499.35       76.00  2007
2          390.46      709.71   150.0         473.14       47.00  2007
3          654.00      963.42   300.0         321.14       38.23  2007
4          647.88      939.89   150.0         626.59       51.40  2007
..            ...         ...     ...            ...         ...   ...
965          0.14        0.19     NaN          77.21         NaN  2013
966         16.70       68.57    13.0         527.48      131.69  2013
967          0.06        0.10     NaN            NaN         NaN  2013
968           NaN        0.14     1.0          14.20        1.00  2013
969          1.17        1.52    10.0          15.25        1.80  2013

[970 rows x 16 columns]>

## ℹ️ Dataset Information

The `info()` function provides a concise summary of the dataset.  
It displays the number of rows, columns, column names, data types, and non-null values in each column.

In [99]:
df.info

<bound method DataFrame.info of                                          Movie              LeadStudio  \
0                                 Spider-Man 3                    Sony
1                              Shrek the Third               Paramount
2                                 Transformers               Paramount
3     Pirates of the Caribbean: At World's End                  Disney
4    Harry Potter and the Order of the Phoenix             Warner Bros
..                                         ...                     ...
965                                The Canyons                     IFC
966                                   The Call                 TriStar
967                        The English Teacher  Cinedigm Entertainment
968                       John Dies at the End                Magnolia
969                                   Lovelace              Radius-TWC

     RottenTomatoes  AudienceScore          Story      Genre  \
0              61.0           54.0  Metamorphosis     Action
1              42.0           57.0          Quest  Animation
2              57.0           89.0  Monster Force     Action
3              45.0           74.0         Rescue     Action
4              78.0           82.0          Quest  Adventure
..              ...            ...            ...        ...
965            22.0            NaN            NaN        NaN
966            43.0           66.0            NaN        NaN
967            42.0            NaN            NaN        NaN
968            61.0           53.0            NaN        NaN
969            55.0           37.0            NaN  Biography

     TheatersOpenWeek  OpeningWeekend  BOAvgOpenWeekend  DomesticGross  \
0              4252.0          151.10           35540.0         336.53
1              4122.0          121.60           29507.0         322.72
2              4011.0           70.50           17577.0         319.25
3              4362.0          114.70           26302.0         309.42
4              4285.0           77.10           17998.0         292.00
..                ...             ...               ...            ...
965               1.0            0.01           13351.0           0.06
966            2507.0           17.12            6828.0          51.87
967               2.0            0.01            3001.0           0.10
968               1.0            0.01           12467.0           0.14
969             118.0            0.18            1564.0           0.36

     ForeignGross  WorldGross  Budget  Profitability  OpenProfit  Year
0          554.34      890.87   258.0         345.30       58.57  2007
1          476.24      798.96   160.0         499.35       76.00  2007
2          390.46      709.71   150.0         473.14       47.00  2007
3          654.00      963.42   300.0         321.14       38.23  2007
4          647.88      939.89   150.0         626.59       51.40  2007
..            ...         ...     ...            ...         ...   ...
965          0.14        0.19     NaN          77.21         NaN  2013
966         16.70       68.57    13.0         527.48      131.69  2013
967          0.06        0.10     NaN            NaN         NaN  2013
968           NaN        0.14     1.0          14.20        1.00  2013
969          1.17        1.52    10.0          15.25        1.80  2013

[970 rows x 16 columns]>

## 📏 Dataset Shape

The `shape` attribute is used to find the dimensions of the dataset.  
It returns the total number of rows and columns present in the DataFrame.

In [100]:
df.shape

(970, 16)

## 🔤 Check Data Types

The `dtypes` attribute is used to display the data type of each column in the dataset.  
It helps to understand the type of data stored in each feature and is useful for data preprocessing.

In [101]:
df.dtypes

Movie                   str
LeadStudio              str
RottenTomatoes      float64
AudienceScore       float64
Story                   str
Genre                   str
TheatersOpenWeek    float64
OpeningWeekend      float64
BOAvgOpenWeekend    float64
DomesticGross       float64
ForeignGross        float64
WorldGross          float64
Budget              float64
Profitability       float64
OpenProfit          float64
Year                  int64
dtype: object

## 📊 Complete Statistical Summary

The `describe(include='all')` function provides a complete summary of all columns in the dataset, including both numerical and categorical features.  
It helps to analyze the overall structure and characteristics of the dataset.

In [102]:
df.describe(include='all')

,Movie,LeadStudio,RottenTomatoes,AudienceScore,Story,Genre,TheatersOpenWeek,OpeningWeekend,BOAvgOpenWeekend,DomesticGross,ForeignGross,WorldGross,Budget,Profitability,OpenProfit,Year
count,970,961,913.000000,907.000000,641,691,949.000000,969.000000,945.000000,970.000000,876.000000,914.000000,897.000000,896.000000,895.000000,970.000000
unique,968,59,NaN,NaN,42,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,All About Steve,Independent,NaN,NaN,Comedy,Comedy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2,133,NaN,NaN,80,177,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,51.707558,61.271224,NaN,NaN,2495.246575,20.620826,8562.593651,68.162544,101.237419,169.009945,56.117168,384.620100,62.223575,2010.236082
std,NaN,NaN,26.821268,16.602457,NaN,NaN,1164.223356,25.338689,10645.135565,80.409969,155.987696,227.744380,53.755914,631.666012,159.713218,1.954840
min,NaN,NaN,0.000000,19.000000,NaN,NaN,1.000000,0.010000,28.000000,0.060000,0.000000,0.100000,0.000000,2.300000,0.160000,2007.000000
25%,NaN,NaN,28.000000,49.000000,NaN,NaN,2054.000000,5.300000,3528.000000,17.565000,16.667500,38.357500,20.000000,150.020000,19.505000,2009.000000
50%,NaN,NaN,52.000000,61.000000,NaN,NaN,2798.000000,13.150000,5983.000000,40.415000,46.655000,88.180000,35.000000,254.820000,34.610000,2010.000000
75%,NaN,NaN,75.000000,74.000000,NaN,NaN,3285.000000,26.200000,9790.000000,89.252500,111.908750,202.310000,75.000000,417.987500,58.375000,2012.000000
max,NaN,NaN,99.000000,96.000000,NaN,NaN,4468.000000,207.440000,147262.000000,760.500000,2021.000000,2781.500000,300.000000,10175.850000,3373.000000,2013.000000

## ❓ Check Missing Values

The `isnull().sum()` function is used to identify the number of missing values present in each column of the dataset.  
It helps in detecting incomplete data and is useful for data cleaning and preprocessing.

In [103]:
df.isnull().sum()

Movie                 0
LeadStudio            9
RottenTomatoes       57
AudienceScore        63
Story               329
Genre               279
TheatersOpenWeek     21
OpeningWeekend        1
BOAvgOpenWeekend     25
DomesticGross         0
ForeignGross         94
WorldGross           56
Budget               73
Profitability        74
OpenProfit           75
Year                  0
dtype: int64

## 🔢 Total Missing Values Count

The `isnull().sum().sum()` function is used to calculate the total number of missing values present in the entire dataset.  
It helps to get an overall count of missing data before performing data cleaning.

In [104]:
df.isnull().sum().sum()

np.int64(1156)

## 🔁 Check Duplicate Records

The `duplicated().sum()` function is used to find the total number of duplicate rows present in the dataset.  
It helps in identifying repeated records that may affect data analysis and model performance.

In [105]:
df.duplicated().sum()

np.int64(1)

## 🧹 Remove Duplicate Records

The `drop_duplicates()` function is used to remove duplicate rows from the dataset.  
The `inplace=True` parameter applies the changes directly to the original DataFrame without creating a new copy.

In [106]:
df.drop_duplicates(inplace=True)

## 📋 Display Complete Dataset

The `print()` function is used to display the complete DataFrame.  
It shows all the rows and columns of the dataset in the output.

In [107]:
print(df)

                                         Movie              LeadStudio  \
0                                 Spider-Man 3                    Sony
1                              Shrek the Third               Paramount
2                                 Transformers               Paramount
3     Pirates of the Caribbean: At World's End                  Disney
4    Harry Potter and the Order of the Phoenix             Warner Bros
..                                         ...                     ...
964                                 The Butler               Weinstein
965                                The Canyons                     IFC
967                        The English Teacher  Cinedigm Entertainment
968                       John Dies at the End                Magnolia
969                                   Lovelace              Radius-TWC

     RottenTomatoes  AudienceScore          Story      Genre  \
0              61.0           54.0  Metamorphosis     Action
1              42.0           57.0          Quest  Animation
2              57.0           89.0  Monster Force     Action
3              45.0           74.0         Rescue     Action
4              78.0           82.0          Quest  Adventure
..              ...            ...            ...        ...
964            73.0           79.0            NaN        NaN
965            22.0            NaN            NaN        NaN
967            42.0            NaN            NaN        NaN
968            61.0           53.0            NaN        NaN
969            55.0           37.0            NaN  Biography

     TheatersOpenWeek  OpeningWeekend  BOAvgOpenWeekend  DomesticGross  \
0              4252.0          151.10           35540.0         336.53
1              4122.0          121.60           29507.0         322.72
2              4011.0           70.50           17577.0         319.25
3              4362.0          114.70           26302.0         309.42
4              4285.0           77.10           17998.0         292.00
..                ...             ...               ...            ...
964            2933.0           24.64            8400.0         116.63
965               1.0            0.01           13351.0           0.06
967               2.0            0.01            3001.0           0.10
968               1.0            0.01           12467.0           0.14
969             118.0            0.18            1564.0           0.36

     ForeignGross  WorldGross  Budget  Profitability  OpenProfit  Year
0          554.34      890.87   258.0         345.30       58.57  2007
1          476.24      798.96   160.0         499.35       76.00  2007
2          390.46      709.71   150.0         473.14       47.00  2007
3          654.00      963.42   300.0         321.14       38.23  2007
4          647.88      939.89   150.0         626.59       51.40  2007
..            ...         ...     ...            ...         ...   ...
964         51.11      167.74    30.0         559.14       82.13  2013
965          0.14        0.19     NaN          77.21         NaN  2013
967          0.06        0.10     NaN            NaN         NaN  2013
968           NaN        0.14     1.0          14.20        1.00  2013
969          1.17        1.52    10.0          15.25        1.80  2013

[969 rows x 16 columns]

## 🔍 Count Unique Values

The `nunique()` function is used to count the number of unique values present in each column of the dataset.  
It helps in understanding the diversity and variation of data in different features.

In [108]:
df.nunique()

Movie               968
LeadStudio           59
RottenTomatoes      100
AudienceScore        73
Story                42
Genre                14
TheatersOpenWeek    789
OpeningWeekend      721
BOAvgOpenWeekend    912
DomesticGross       935
ForeignGross        842
WorldGross          899
Budget              151
Profitability       883
OpenProfit          810
Year                  7
dtype: int64

## 🔍 Find Unique Values in RottenTomatoes Column

The `unique()` function is used to display all the unique values present in the **RottenTomatoes** column.  
It helps to understand the different ratings or categories available in this feature.

In [109]:
df['RottenTomatoes'].unique()

array([61., 42., 57., 45., 78., 69., 93., 31., 26., 60., 97., 90., 14.,
       91., 94., 20., 79., 35., 52., 88., 13., 92., 70., 28., 23., 66.,
        9., 41., 27., 71., 67., 95., 82., 18., 46., 33., 21., 86., 63.,
        8., 47., 39.,  2., 15., 50., 76., 43., 30.,  3., 89., 36., 55.,
       56., 49., 72., 54., 11., 75., 29., 44.,  4., 19.,  1., 77., 40.,
       96., 64., 80., 53., 73., 51., 83., 25., 65., 68., 58., 16., 87.,
       85., 38., 24., 62., 59., 22.,  0., 37.,  7., 32.,  5., 34., 48.,
       81., 10., 98., 12., 84., 74., 17.,  6., nan, 99.])

## 🎬 Find Unique Movie Names

The `unique()` function is used to display all the unique movie names present in the **Movie** column.  
It helps to identify different movie titles available in the dataset and check for duplicate entries.

In [110]:
df['Movie'].unique()

<StringArray>
[                             'Spider-Man 3',
                           'Shrek the Third',
                              'Transformers',
  'Pirates of the Caribbean: At World's End',
 'Harry Potter and the Order of the Phoenix',
                               'I Am Legend',
                      'The Bourne Ultimatum',
        'National Treasure: Book of Secrets',
                   'Alvin and the Chipmunks',
                                       '300',
 ...
                                'Austenland',
                                'The Iceman',
                          'Girl Most Likely',
                                    'Wadjda',
                    'Much Ado About Nothing',
                                'The Butler',
                               'The Canyons',
                       'The English Teacher',
                      'John Dies at the End',
                                  'Lovelace']
Length: 968, dtype: str

## 🎥 Find Unique Lead Studios

The `unique()` function is used to display all the unique values present in the **LeadStudio** column.  
It helps to identify the different production studios involved in the movies and understand the variety of studios in the dataset.

In [111]:
df['LeadStudio'].unique()

<StringArray>
[                    'Sony',                'Paramount',
                   'Disney',              'Warner Bros',
                'Universal',                      'Fox',
              'Independent',                'Weinstein',
                        nan,                'Lionsgate',
                      'MGM',                'Mediaplex',
                   'Summit',         'Relativity Media',
              'Buena Vista',                 'Overture',
            'Liberty Starz',                 'New Line',
                    'Focus',                  'Miramax',
                    'Crest',                      'CBS',
 'Highlight Communications',                  'Vertigo',
       'Aardman Animations',                    'Pixar',
             'Morgan Creek',                 'Reliance',
   'Spyglass Entertainment',               'DreamWorks',
         'Village Roadshow',      'Regency Enterprises',
            'Happy Madison',                   'Virgin',
                 'Columbia',       'Legendary Pictures',
        'Entertainment One',                 'Magnolia',
                     'Eros',     'Roadside Attractions',
       'Atlas Distribution',                      'UTV',
          'Fox Searchlight',                 'Yash Raj',
                'Open Road',              'Cohen Media',
        'ARC Entertainment',                      'IFC',
         'LD Entertainment',           'Rocky Mountain',
                  'TriStar',          'Music Box Films',
           'Samuel Goldwyn',             'FilmDistrict',
              'Screen Gems',            'Oscillloscope',
                      'A24',  'Millenium Entertainment',
   'Cinedigm Entertainment',               'Radius-TWC']
Length: 60, dtype: str

## ⭐ Find Unique Audience Scores

The `unique()` function is used to display all the unique values present in the **AudienceScore** column.  
It helps to understand the different audience ratings available in the dataset and analyze the variation in scores.

In [112]:
df['AudienceScore'].unique()

array([54., 57., 89., 74., 82., 69., 91., 72., 73., 90., 84., 78., 83.,
       68., 86., 55., 87., 80., 66., 56., 75., 81., 52., 70., 64., 47.,
       63., 85., 37., 38., 61., 65., 41., 53., 50., 46., 67., 59., 45.,
       43., 48., 79., 44., 96., 62., 76., 77., 40., 71., 34., 29., 36.,
       31., 51., 49., 88., 58., 42., 32., 26., 33., 28., 22., 60., nan,
       39., 27., 92., 35., 93., 24., 19., 20., 25.])

## 📖 Find Unique Story Values

The `unique()` function is used to display all the unique values present in the **Story** column.  
It helps to identify different story descriptions available in the dataset and understand the variety of movie plots.

In [113]:
df['Story'].unique()

<StringArray>
[     'Metamorphosis',              'Quest',      'Monster Force',
             'Rescue',            'Pursuit',         'The Riddle',
             'Comedy',          'Sacrifice',     'Transformation',
         'Maturation',               'Love',            'pursuit',
 'Journey and Return',           'Underdog',            'Rivalry',
            'Revenge',          'discovery',          'Discovery',
             'Escape',          'sacrifice',    'Wretched Excess',
         'Temptation',              'quest',               'love',
             'rescue',  'fish out of water',            'rivalry',
             'escape',         'maturation',           'underdog',
   'journey & return',  'Fish Out of Water',             'comedy',
      'monster force',             'riddle',            'tragedy',
         'temptation',     'transformation',            'Tragedy',
     'Rags to Riches',     'Rags To Riches',  'Fish Out Of Water',
                  nan]
Length: 43, dtype: str

## 🎭 Find Unique Movie Genres

The `unique()` function is used to display all the unique values present in the **Genre** column.  
It helps to identify the different movie genres available in the dataset and understand the variety of categories.

In [114]:
df['Genre'].unique()

<StringArray>
[     'Action',   'Animation',   'Adventure',    'Thriller',      'Comedy',
     'Musical',       'Drama',   'Biography',      'Horror',     'Romance',
     'Fantasy', 'Documentary',       'Crime',           nan,     'Mystery']
Length: 15, dtype: str

## 🎭 Find Unique Genres

The `unique()` function is used to display all the unique values present in the **Genre** column.  
It helps to identify the different types of movie genres available in the dataset and understand the category variation.

In [115]:
df['Genre'].unique()

<StringArray>
[     'Action',   'Animation',   'Adventure',    'Thriller',      'Comedy',
     'Musical',       'Drama',   'Biography',      'Horror',     'Romance',
     'Fantasy', 'Documentary',       'Crime',           nan,     'Mystery']
Length: 15, dtype: str

## 🎬 Find Unique Theaters Open Week Values

The `unique()` function is used to display all the unique values present in the **TheatersOpenWeek** column.  
It helps to understand the different numbers of theaters in which movies were released during their opening week.

In [116]:
df['TheatersOpenWeek'].unique()

array([4.252e+03, 4.122e+03, 4.011e+03, 4.362e+03, 4.285e+03, 3.606e+03,
       3.660e+03, 3.832e+03, 3.475e+03, 3.103e+03, 3.940e+03, 3.922e+03,
       3.287e+03, 2.871e+03, 1.019e+03, 3.778e+03, 3.408e+03, 3.959e+03,
       3.054e+03, 3.730e+03, 3.928e+03, 2.948e+03, 3.495e+03, 3.121e+03,
       3.372e+03, 3.565e+03, 3.619e+03, 3.604e+03, 3.413e+03, 3.136e+03,
       2.911e+03, 3.153e+03, 2.925e+03, 8.600e+02, 3.528e+03, 2.575e+03,
       3.183e+03, 2.051e+03, 3.472e+03, 2.011e+03, 3.110e+03, 2.454e+03,
       2.652e+03, 1.249e+03,       nan, 2.511e+03, 2.831e+03, 2.793e+03,
       2.806e+03, 2.604e+03, 2.425e+03, 2.611e+03, 8.850e+02, 2.801e+03,
       2.458e+03, 2.855e+03, 2.540e+03, 2.755e+03, 3.229e+03, 2.218e+03,
       2.612e+03, 2.362e+03, 3.164e+03, 2.453e+03, 2.629e+03, 2.423e+03,
       2.603e+03, 2.624e+03, 7.020e+02, 9.540e+02, 2.447e+03, 2.551e+03,
       6.050e+02, 6.580e+02, 2.650e+03, 2.725e+03, 2.350e+03, 7.150e+02,
       2.381e+03, 2.776e+03, 2.215e+03, 2.332e+03, 2.108e+03, 6.980e+02,
       2.155e+03, 2.277e+03, 1.720e+03, 4.366e+03, 4.105e+03, 4.260e+03,
       3.965e+03, 3.992e+03, 4.114e+03, 4.056e+03, 3.419e+03, 3.451e+03,
       3.954e+03, 3.285e+03, 2.976e+03, 3.929e+03, 3.505e+03, 3.175e+03,
       3.911e+03, 3.319e+03, 3.681e+03, 3.651e+03, 3.480e+03, 3.760e+03,
       2.811e+03, 3.510e+03, 3.094e+03, 3.462e+03, 3.434e+03, 3.410e+03,
       3.215e+03, 3.623e+03, 3.072e+03, 2.711e+03, 2.648e+03, 3.428e+03,
       3.411e+03, 2.988e+03, 3.057e+03, 3.204e+03, 3.560e+03, 3.149e+03,
       3.847e+03, 3.125e+03, 2.792e+03, 2.986e+03, 2.798e+03, 2.651e+03,
       2.543e+03, 2.758e+03, 2.470e+03, 3.030e+03, 2.466e+03, 3.151e+03,
       3.104e+03, 2.714e+03, 3.513e+03, 2.642e+03, 2.729e+03, 2.706e+03,
       2.707e+03, 2.700e+03, 2.751e+03, 2.387e+03, 2.006e+03, 2.704e+03,
       3.376e+03, 3.152e+03, 2.464e+03, 2.710e+03, 2.605e+03, 2.510e+03,
       2.213e+03, 1.591e+03, 2.070e+03, 2.532e+03, 1.850e+03, 3.452e+03,
       8.390e+02, 3.056e+03, 3.012e+03, 2.204e+03, 3.600e+01, 2.626e+03,
       2.461e+03, 2.421e+03, 2.436e+03, 3.735e+03, 2.769e+03, 2.664e+03,
       1.603e+03, 2.368e+03, 2.962e+03, 2.240e+03, 1.166e+03, 2.467e+03,
       2.753e+03, 2.960e+03, 2.030e+03, 2.054e+03, 6.920e+02, 3.390e+03,
       3.185e+03, 1.045e+03, 2.339e+03, 1.267e+03, 2.509e+03, 2.812e+03,
       2.168e+03, 2.585e+03, 1.505e+03, 5.020e+02, 9.000e+00, 2.660e+02,
       5.350e+02, 2.044e+03, 3.011e+03, 2.089e+03, 8.080e+02, 1.936e+03,
       1.291e+03, 2.808e+03, 1.106e+03, 6.870e+02, 2.508e+03, 1.185e+03,
       2.022e+03, 1.052e+03, 4.234e+03, 4.325e+03, 4.024e+03, 3.766e+03,
       3.269e+03, 3.849e+03, 3.700e+03, 3.626e+03, 4.104e+03, 4.099e+03,
       4.096e+03, 3.404e+03, 3.461e+03, 4.007e+03, 3.144e+03, 3.683e+03,
       3.527e+03, 3.530e+03, 3.119e+03, 3.135e+03, 3.697e+03, 3.049e+03,
       2.887e+03, 3.000e+03, 7.600e+02, 3.611e+03, 3.334e+03, 2.354e+03,
       2.882e+03, 1.895e+03, 3.332e+03, 3.118e+03, 3.036e+03, 2.299e+03,
       2.890e+03, 3.271e+03, 3.481e+03, 2.514e+03, 3.187e+03, 3.074e+03,
       3.105e+03, 3.255e+03, 2.756e+03, 3.226e+03, 2.732e+03, 3.007e+03,
       2.534e+03, 3.425e+03, 3.521e+03, 2.606e+03, 2.942e+03, 2.507e+03,
       2.563e+03, 3.022e+03, 2.357e+03, 3.035e+03, 2.750e+03, 2.574e+03,
       2.951e+03, 2.503e+03, 2.125e+03, 2.803e+03, 1.638e+03, 3.243e+03,
       2.251e+03, 3.025e+03, 2.505e+03, 2.443e+03, 8.170e+02, 2.313e+03,
       1.661e+03, 2.024e+03, 2.718e+03, 2.734e+03, 2.344e+03, 2.088e+03,
       2.450e+03, 2.527e+03, 2.364e+03, 3.106e+03, 2.727e+03, 1.898e+03,
       3.096e+03, 2.033e+03, 2.502e+03, 1.412e+03, 3.014e+03, 1.707e+03,
       2.655e+03, 1.810e+03, 4.000e+00, 2.702e+03, 3.008e+03, 1.862e+03,
       1.915e+03, 2.159e+03, 2.635e+03, 1.856e+03, 8.200e+02, 2.754e+03,
       2.223e+03, 1.721e+03, 7.610e+02, 2.331e+03, 6.420e+02, 2.665e+03,
       1.611e+03, 7.240e+02, 2.506e+03, 2.745e+03, 1.138e+03, 2.181e+03,
       6.000e+00, 2.133e+03, 1.136e+03, 1.164e+03, 8.820e+02, 1.110e+02,
       1.393e+03, 1.959e+03, 2.121e+03, 9.160e+02, 3.728e+03, 2.625e+03,
       9.590e+02, 1.100e+01, 3.037e+03, 2.211e+03, 3.705e+03, 2.000e+00,
       3.777e+03, 6.720e+02, 3.150e+03, 1.424e+03, 3.374e+03, 2.523e+03,
       2.969e+03, 2.459e+03, 3.476e+03, 2.809e+03, 3.077e+03, 3.355e+03,
       2.856e+03, 3.082e+03, 3.066e+03, 2.549e+03, 2.127e+03, 2.722e+03,
       2.997e+03, 2.697e+03, 3.003e+03, 3.000e+00, 3.534e+03, 2.546e+03,
       4.125e+03, 4.055e+03, 1.000e+02, 3.792e+03, 4.380e+03, 3.081e+03,
       2.825e+03, 1.831e+03, 3.065e+03, 2.859e+03, 3.098e+03, 3.575e+03,
       2.476e+03, 2.968e+03, 3.536e+03, 2.455e+03, 2.670e+03, 3.213e+03,
       3.944e+03, 2.518e+03, 2.572e+03, 2.784e+03, 1.605e+03, 3.216e+03,
       3.356e+03, 2.669e+03, 3.646e+03, 2.212e+03, 2.521e+03, 3.203e+03,
       3.503e+03, 3.612e+03, 2.818e+03, 3.445e+03, 2.956e+03, 4.359e+03,
       2.991e+03, 2.880e+03, 2.435e+03, 2.206e+03, 3.603e+03, 3.535e+03,
       2.823e+03, 3.280e+03, 3.111e+03, 3.555e+03, 3.270e+03, 8.190e+02,
       3.663e+03, 8.470e+02, 7.000e+02, 3.169e+03, 2.874e+03, 2.673e+03,
       2.936e+03, 2.564e+03, 2.440e+02, 2.771e+03, 3.504e+03, 2.924e+03,
       2.012e+03, 4.468e+03, 3.222e+03, 3.344e+03, 4.028e+03, 3.047e+03,
       3.207e+03, 3.655e+03, 3.233e+03, 2.456e+03, 3.515e+03, 2.548e+03,
       4.020e+02, 1.873e+03, 2.888e+03, 2.875e+03, 2.650e+02, 3.328e+03,
       3.276e+03, 2.733e+03, 3.417e+03, 1.952e+03, 5.000e+00, 2.918e+03,
       3.715e+03, 4.115e+03, 1.500e+01, 2.614e+03, 3.015e+03, 3.750e+03,
       3.020e+03, 3.167e+03, 3.507e+03, 2.760e+03, 2.661e+03, 2.886e+03,
       2.290e+03, 2.180e+02, 2.630e+03, 3.644e+03, 3.155e+03, 3.549e+03,
       2.926e+03, 3.114e+03, 2.994e+03, 3.816e+03, 2.950e+03, 2.535e+03,
       4.375e+03, 3.579e+03, 3.040e+03, 1.277e+03, 3.154e+03, 3.112e+03,
       3.122e+03, 2.408e+03, 1.910e+03, 3.438e+03, 1.552e+03, 3.548e+03,
       3.925e+03, 2.973e+03, 3.117e+03, 9.440e+02, 3.448e+03, 2.993e+03,
       2.473e+03, 3.339e+03, 2.470e+02, 3.018e+03, 1.719e+03, 2.555e+03,
       3.321e+03, 2.802e+03, 4.155e+03, 2.864e+03, 3.952e+03, 3.917e+03,
       3.440e+03, 3.826e+03, 3.648e+03, 2.787e+03, 3.305e+03, 2.816e+03,
       1.000e+01, 3.703e+03, 2.904e+03, 2.214e+03, 2.961e+03, 3.295e+03,
       3.033e+03, 3.379e+03, 2.003e+03, 2.840e+03, 3.087e+03, 6.620e+02,
       2.200e+01, 2.150e+03, 2.913e+03, 1.060e+02, 7.070e+02, 1.826e+03,
       8.760e+02, 2.940e+03, 2.296e+03, 2.914e+03, 3.584e+03, 3.615e+03,
       2.199e+03, 8.020e+02, 2.703e+03, 2.985e+03, 2.273e+03, 3.395e+03,
       2.996e+03, 3.017e+03, 3.955e+03, 8.090e+02, 3.367e+03, 4.088e+03,
       4.061e+03, 3.043e+03, 2.376e+03, 1.869e+03, 2.817e+03, 3.002e+03,
       2.405e+03, 3.641e+03, 3.482e+03, 7.000e+00, 3.108e+03, 1.320e+02,
       2.450e+02, 3.192e+03, 1.600e+01, 1.970e+02, 3.232e+03, 1.012e+03,
       3.690e+03, 2.129e+03, 4.164e+03, 1.580e+02, 3.820e+02, 2.002e+03,
       2.433e+03, 2.907e+03, 2.008e+03, 2.863e+03, 5.500e+01, 1.660e+02,
       3.755e+03, 3.391e+03, 3.010e+03, 3.729e+03, 1.200e+02, 2.730e+03,
       8.800e+01, 1.884e+03, 7.570e+02, 3.005e+03, 3.690e+02, 3.174e+03,
       3.220e+02, 2.410e+02, 2.439e+03, 1.700e+01, 2.361e+03, 3.349e+03,
       3.083e+03, 1.210e+02, 3.881e+03, 1.610e+02, 3.352e+03, 2.540e+02,
       3.749e+03, 3.470e+03, 2.424e+03, 1.407e+03, 2.814e+03, 2.927e+03,
       2.992e+03, 4.258e+03, 2.930e+03, 2.998e+03, 4.200e+01, 4.349e+03,
       4.248e+03, 1.900e+01, 8.000e+02, 3.900e+02, 3.412e+03, 3.429e+03,
       3.350e+02, 2.255e+03, 3.396e+03, 2.500e+01, 2.670e+02, 2.724e+03,
       2.512e+03, 3.653e+03, 1.300e+01, 2.266e+03, 1.800e+01, 2.628e+03,
       1.625e+03, 1.480e+03, 5.610e+02, 1.000e+00, 3.773e+03, 2.244e+03,
       2.567e+03, 3.661e+03, 1.720e+02, 3.239e+03, 4.318e+03, 8.100e+02,
       2.700e+01, 3.745e+03, 3.205e+03, 1.511e+03, 1.403e+03, 4.404e+03,
       2.285e+03, 3.316e+03, 2.431e+03, 4.045e+03, 4.137e+03, 3.358e+03,
       1.400e+01, 3.477e+03, 4.070e+03, 2.958e+03, 3.168e+03, 2.912e+03,
       3.601e+03, 3.078e+03, 3.021e+03, 2.515e+03, 3.545e+03, 3.752e+03,
       1.280e+03, 1.769e+03, 2.238e+03, 5.910e+02, 3.491e+03, 3.401e+03,
       3.143e+03, 2.883e+03, 3.290e+03, 2.750e+02, 1.010e+02, 6.500e+01,
       4.253e+03, 4.003e+03, 4.163e+03, 3.742e+03, 3.771e+03, 4.004e+03,
       3.820e+03, 4.207e+03, 3.841e+03, 4.065e+03, 3.607e+03, 3.912e+03,
       3.907e+03, 3.924e+03, 3.734e+03, 3.550e+03, 3.867e+03, 3.115e+03,
       3.284e+03, 3.809e+03, 3.894e+03, 3.904e+03, 4.001e+03, 3.184e+03,
       3.375e+03, 3.716e+03, 3.080e+03, 3.525e+03, 2.557e+03, 3.230e+03,
       2.922e+03, 3.330e+03, 3.345e+03, 2.781e+03, 3.016e+03, 3.028e+03,
       1.474e+03, 3.055e+03, 2.690e+03, 3.237e+03, 3.009e+03, 3.407e+03,
       3.405e+03, 1.283e+03, 3.399e+03, 2.671e+03, 3.736e+03, 2.308e+03,
       2.591e+03, 3.303e+03, 1.225e+03, 3.157e+03, 3.402e+03, 2.852e+03,
       2.041e+03, 3.223e+03, 3.044e+03, 3.026e+03, 2.160e+03, 2.945e+03,
       7.250e+02, 3.202e+03, 1.553e+03, 1.584e+03, 2.411e+03, 1.379e+03,
       2.570e+03, 1.110e+03, 2.422e+03, 1.729e+03, 2.023e+03, 1.010e+03,
       8.350e+02, 4.430e+02, 7.290e+02, 1.001e+03, 2.230e+03, 2.633e+03,
       1.260e+02, 2.622e+03, 6.500e+02, 2.188e+03, 2.161e+03, 1.086e+03,
       2.538e+03, 9.900e+01, 9.680e+02, 2.101e+03, 8.970e+02, 2.135e+03,
       2.404e+03, 1.525e+03, 1.420e+02, 9.100e+01, 7.700e+02, 4.830e+02,
       8.700e+02, 8.070e+02, 5.830e+02, 2.330e+02, 3.110e+02, 6.700e+02,
       1.440e+02, 1.950e+02, 8.600e+01, 2.740e+02, 2.580e+02, 3.510e+02,
       8.700e+01, 2.220e+02, 2.933e+03, 1.180e+02])

## 💰 Find Unique Opening Weekend Values

The `unique()` function is used to display all the unique values present in the **OpeningWeekend** column.  
It helps to identify different opening weekend earnings of movies and understand the variation in box office performance.

In [117]:
df['OpeningWeekend'].unique()

array([1.5110e+02, 1.2160e+02, 7.0500e+01, 1.1470e+02, 7.7100e+01,
       7.7200e+01, 6.9300e+01, 4.4800e+01, 4.4300e+01, 7.0900e+01,
       4.7000e+01, 7.4000e+01, 3.9700e+01, 3.0700e+01, 1.0600e+01,
       4.9100e+01, 3.3400e+01, 5.8000e+01, 4.3600e+01, 3.4400e+01,
       3.8000e+01, 3.3000e+01, 3.4200e+01, 2.7500e+01, 3.6100e+01,
       4.5300e+01, 3.1200e+01, 2.5100e+01, 1.9400e+01, 2.2900e+01,
       2.2200e+01, 7.8000e+00, 2.5700e+01, 9.6000e+00, 3.1700e+01,
       2.1900e+01, 1.7600e+01, 2.6400e+01, 2.1400e+01, 2.4300e+01,
       6.5000e+00, 1.4000e+01, 9.3000e+00, 1.3600e+01, 1.0400e+01,
       1.7100e+01, 1.4500e+01, 1.1700e+01, 1.0000e+01, 4.9000e+00,
       1.8600e+01, 1.3200e+01, 1.5600e+01, 9.1600e+00, 1.3500e+01,
       1.4600e+01, 1.3700e+01, 1.3400e+01, 9.6300e+00, 1.0800e+01,
       7.5000e+00, 6.9000e+00, 8.9000e+00, 1.1600e+01, 3.6000e+00,
       3.8000e+00, 9.7000e+00, 7.6000e+00, 2.0000e+00, 2.1000e+00,
       4.1000e+00, 7.1000e+00, 8.2000e+00, 1.6000e+00, 6.6000e+00,
       5.6000e+00, 6.7000e+00, 3.4000e+00, 5.7000e+00, 1.8000e+00,
       4.7000e+00, 5.0000e+00, 1.5840e+02, 9.8620e+01, 1.0010e+02,
       6.2600e+01, 6.3090e+01, 6.0240e+01, 6.3110e+01, 6.9640e+01,
       6.7500e+01, 4.5000e+01, 5.7040e+01, 2.9480e+01, 2.7750e+01,
       5.5030e+01, 4.3000e+00, 5.5140e+01, 5.0930e+01, 3.8700e+01,
       3.1070e+01, 2.5810e+01, 2.6200e+01, 3.6360e+01, 4.0500e+01,
       2.1000e+01, 2.9200e+01, 3.0940e+01, 3.8530e+01, 1.8260e+01,
       3.5900e+01, 2.9300e+01, 4.2030e+01, 2.3200e+01, 2.1030e+01,
       2.4100e+01, 2.0170e+01, 2.7400e+01, 4.0100e+01, 2.6850e+01,
       2.3010e+01, 3.4500e+01, 3.0500e+01, 2.2870e+01, 1.9000e+01,
       2.1600e+01, 1.9170e+01, 3.0520e+01, 1.7730e+01, 1.9130e+01,
       1.7410e+01, 1.4900e+01, 1.8910e+01, 3.0100e+01, 2.0990e+01,
       1.0100e+01, 1.4530e+01, 1.4800e+01, 1.4760e+01, 1.0680e+01,
       2.0810e+01, 1.8200e+01, 1.6210e+01, 2.0080e+01, 1.3420e+01,
       1.6300e+01, 1.5000e+01, 1.2900e+01, 1.8510e+01, 1.4910e+01,
       1.7700e+01, 1.0530e+01, 1.7380e+01, 1.2620e+01, 9.4000e+00,
       1.5080e+01, 6.8400e+00, 1.0300e+01, 1.3910e+01, 9.7600e+00,
       1.5000e+00, 1.2060e+01, 1.4200e+01, 1.1310e+01, 1.2400e+01,
       1.0070e+01, 1.2700e+01, 1.1200e+01, 7.1800e+00, 5.9400e+00,
       1.1400e+01, 1.0120e+01, 1.2500e+01, 1.0500e+01, 9.5100e+00,
       8.6000e+00, 7.9000e+00, 3.7600e+00, 9.5000e+00, 7.7400e+00,
       8.2700e+00, 5.3000e+00, 3.3000e+00, 8.0000e+00, 7.0000e+00,
       6.2300e+00, 6.2600e+00, 5.8000e+00, 5.4000e+00, 5.0100e+00,
       3.4100e+00, 2.9000e-01, 4.2500e+00, 2.8000e+00, 2.4900e+00,
       5.2500e+00, 4.0000e+00, 4.0500e+00, 4.5600e+00, 4.0900e+00,
       9.0000e-02, 1.0300e+00, 3.6100e+00, 3.5000e+00, 3.1300e+00,
       4.6000e-01, 2.9700e+00, 4.0300e+00, 7.7000e+01, 1.0900e+02,
       7.7800e+01, 1.4280e+02, 6.8100e+01, 7.5200e+01, 3.4100e+01,
       4.8800e+01, 6.2300e+01, 5.9300e+01, 4.1700e+01, 8.5100e+01,
       5.4200e+01, 6.5300e+01, 3.3600e+01, 5.4700e+01, 3.1800e+01,
       2.4700e+01, 4.6200e+01, 4.2600e+01, 3.0300e+01, 3.7400e+01,
       2.2100e+01, 3.4300e+01, 1.9600e+01, 5.5200e+01, 2.4200e+01,
       2.5200e+01, 2.0000e+01, 2.7800e+01, 2.7600e+01, 2.4600e+01,
       3.2300e+01, 3.2700e+01, 1.6800e+01, 1.7000e+01, 2.3300e+01,
       1.7800e+01, 2.8600e+01, 2.4400e+01, 2.3370e+01, 4.0600e+01,
       2.3700e+01, 3.0600e+01, 2.1100e+01, 2.3000e+01, 1.5400e+01,
       2.2700e+01, 2.1200e+01, 1.6900e+01, 1.8800e+01, 2.0800e+01,
       1.9800e+01, 1.2300e+01, 1.5800e+01, 1.2800e+01, 1.3300e+01,
       1.4100e+01, 2.0500e+01, 1.0700e+01, 1.2200e+01, 1.1000e+01,
       8.0500e+00, 9.1500e+00, 5.4500e+00, 5.5000e+00, 1.4000e-01,
       5.9000e+00, 3.9000e+00, 6.3000e+00, 7.6000e-01, 9.0000e-01,
       5.1000e+00, 4.4000e+00, 1.3000e-01, 4.8000e+00, 2.5000e-01,
       3.2000e+00, 2.9000e+00, 2.6000e+00, 2.6000e-01, 2.2000e+00,
       2.1300e+00, 3.2900e+01, 1.1610e+02, 9.1000e+00, 8.3800e+00,
       1.0300e-01, 1.1950e+01, 3.2000e-02, 6.1200e+01, 1.6200e+00,
       1.8210e+01, 7.3300e+00, 1.8000e-01, 1.5100e+01, 3.0400e+01,
       1.6200e+01, 5.6400e+01, 2.3500e+01, 3.2690e+01, 2.3100e+01,
       1.7200e+01, 6.0000e+00, 8.5200e+00, 1.9500e+01, 1.4300e+01,
       1.1000e-01, 1.2500e+02, 4.3700e+01, 6.2800e+01, 1.2810e+02,
       5.0400e+01, 8.3000e+00, 2.0200e+01, 9.2000e+00, 1.6100e+01,
       1.7500e+01, 3.0830e+01, 9.7400e+00, 4.6020e+01, 8.4000e+00,
       4.0670e+01, 1.0000e-01, 2.4800e+01, 3.0000e+01, 2.1800e+01,
       6.1000e+00, 2.6700e+01, 3.6000e+01, 2.2530e+01, 3.1000e+01,
       9.8000e+00, 7.0800e+01, 4.1000e+01, 1.1690e+01, 7.5000e-02,
       4.8770e+01, 1.3100e+01, 2.0700e+01, 2.4000e+01, 1.6070e+01,
       3.4800e+01, 1.2000e+01, 5.1000e-01, 5.5700e+01, 4.0300e+01,
       2.0400e+01, 1.6000e+01, 6.5400e+00, 3.5500e+01, 8.0000e-01,
       2.2400e+01, 2.3800e+01, 6.4800e+01, 3.1500e+01, 1.1030e+02,
       4.4030e+01, 2.2690e+01, 5.6200e+01, 1.6400e+01, 1.6000e-01,
       1.3330e+01, 8.6400e+00, 1.7000e-01, 1.2950e+01, 1.0930e+01,
       1.0200e+00, 8.0000e-02, 8.7000e+00, 1.2220e+01, 1.2070e+01,
       2.2000e+01, 3.1600e+01, 3.5570e+01, 9.8500e+00, 2.6250e+01,
       6.5060e+01, 6.6140e+01, 3.0000e-01, 1.0410e+01, 1.0020e+01,
       3.6430e+01, 1.9100e+01, 2.3750e+01, 1.9150e+01, 8.5300e+00,
       8.1300e+00, 1.1340e+01, 5.1900e+00, 7.5000e-01, 7.9000e-01,
       1.0040e+01, 8.6190e+01, 1.8030e+01, 1.5560e+01, 1.8620e+01,
       7.7100e+00, 2.5360e+01, 5.3170e+01, 1.3540e+01, 1.2370e+01,
       2.1240e+01, 1.6919e+02, 3.7540e+01, 2.8300e+01, 1.1360e+01,
       1.9450e+01, 3.2210e+01, 1.2050e+01, 1.3270e+01, 1.1220e+01,
       2.5000e+01, 3.8300e+00, 3.0510e+01, 9.3500e+00, 4.7660e+01,
       5.0000e-02, 5.6000e-01, 6.9100e+00, 5.8300e+00, 2.9550e+01,
       7.4500e+00, 1.8450e+01, 1.7500e+00, 1.3010e+01, 1.9700e+01,
       5.0800e+00, 7.0100e+00, 5.2570e+01, 1.3040e+01, 9.0150e+01,
       1.4950e+01, 3.4080e+01, 3.8080e+01, 2.7320e+01, 1.4010e+01,
              nan, 3.9230e+01, 5.4810e+01, 1.8690e+01, 3.4000e-01,
       3.9630e+01, 1.3950e+01, 1.4810e+01, 1.1640e+01, 1.9060e+01,
       3.5450e+01, 3.4600e+00, 2.1160e+01, 9.7200e+00, 2.3700e+00,
       3.2500e+00, 1.3530e+01, 6.4000e-01, 3.5100e+00, 9.9100e+00,
       4.3800e+00, 8.6800e+00, 1.2760e+01, 3.3500e+01, 8.5950e+01,
       2.6040e+01, 1.0470e+01, 5.4100e+00, 1.3210e+01, 2.9240e+01,
       5.1400e+00, 3.5610e+01, 8.4900e+00, 8.6700e+00, 3.7000e-01,
       6.5720e+01, 5.4700e+00, 2.4030e+01, 9.7850e+01, 1.3812e+02,
       2.1860e+01, 1.4520e+01, 5.2400e+00, 1.6840e+01, 9.3600e+00,
       5.4200e+00, 7.8600e+00, 5.5100e+01, 2.0070e+01, 3.6300e+01,
       4.0000e-02, 1.6310e+01, 1.1400e+00, 7.0000e-01, 2.1510e+01,
       7.0000e-02, 3.2000e-01, 1.9460e+01, 1.0600e+00, 2.5530e+01,
       7.7600e+00, 6.6320e+01, 5.4000e-01, 2.2900e+00, 2.2700e+00,
       7.9600e+00, 9.6100e+00, 2.4350e+01, 2.9690e+01, 1.4620e+01,
       3.0120e+01, 7.0220e+01, 6.2800e+00, 1.3150e+01, 2.4900e+01,
       1.8900e+00, 1.1410e+01, 2.0200e+00, 2.2120e+01, 1.3800e+00,
       1.2300e+00, 8.4300e+00, 1.4650e+01, 4.2520e+01, 1.2290e+01,
       8.5000e-01, 4.6630e+01, 1.2800e+00, 1.5210e+01, 8.6000e-01,
       3.0180e+01, 2.7340e+01, 7.1400e+00, 6.8100e+00, 1.5900e+00,
       2.7280e+01, 2.2450e+01, 9.4000e-01, 6.0320e+01, 3.9130e+01,
       2.0744e+02, 5.4590e+01, 1.8130e+01, 5.2000e-01, 1.1800e+00,
       1.7000e+00, 2.9000e+01, 1.4090e+01, 1.4550e+01, 5.1500e+00,
       6.0300e+00, 5.1050e+01, 1.6700e+00, 1.4280e+01, 1.8780e+01,
       2.1050e+01, 2.3770e+01, 1.4440e+01, 3.0000e-02, 7.8900e+00,
       4.0170e+01, 2.3000e-01, 1.6020e+01, 3.8200e+00, 4.1700e+00,
       4.4000e-01, 5.9000e-01, 1.8010e+01, 8.8360e+01, 5.6220e+01,
       1.1730e+01, 4.9510e+01, 1.6400e+00, 5.4420e+01, 1.3450e+01,
       6.2000e+01, 2.8400e+00, 7.4000e-01, 3.8140e+01, 1.4740e+01,
       2.6590e+01, 1.8300e+00, 3.1000e+00, 1.6089e+02, 3.3730e+01,
       1.7440e+01, 2.8590e+01, 1.0610e+01, 1.9670e+01, 5.2900e+00,
       8.4620e+01, 1.5254e+02, 2.2520e+01, 1.1140e+01, 2.1000e-01,
       1.7010e+01, 1.4107e+02, 4.1200e+01, 1.2750e+01, 2.0870e+01,
       1.1580e+01, 2.5580e+01, 2.5310e+01, 1.0550e+01, 3.3460e+01,
       4.9040e+01, 4.2000e-01, 1.0800e+00, 1.5800e+00, 4.1510e+01,
       2.7520e+01, 2.5720e+01, 9.8900e+00, 2.0820e+01, 7.0900e+00,
       6.0000e-02, 1.7414e+02, 8.3520e+01, 1.5807e+02, 7.3650e+01,
       2.4000e-01, 9.7380e+01, 8.2430e+01, 5.5790e+01, 1.1662e+02,
       8.5740e+01, 4.3640e+01, 6.6410e+01, 7.9110e+01, 7.0170e+01,
       5.3110e+01, 3.7290e+01, 4.1670e+01, 2.9350e+01, 5.0090e+01,
       1.7550e+01, 4.1860e+01, 2.4830e+01, 3.7050e+01, 2.9810e+01,
       2.1310e+01, 2.6420e+01, 3.3530e+01, 2.9210e+01, 3.4020e+01,
       3.9120e+01, 1.9690e+01, 2.2230e+01, 2.4850e+01, 1.4400e+01,
       2.7200e+01, 1.8360e+01, 3.4550e+01, 1.2770e+01, 2.4640e+01,
       2.6230e+01, 4.0270e+01, 3.0370e+01, 3.2060e+01, 2.8400e+01,
       1.8050e+01, 2.7060e+01, 9.2000e-01, 2.0720e+01, 1.6330e+01,
       2.0350e+01, 2.7020e+01, 1.7070e+01, 1.9030e+01, 2.5780e+01,
       2.7490e+01, 6.1000e-01, 1.7330e+01, 4.1000e-01, 1.5810e+01,
       9.3400e+00, 1.9000e-01, 3.4060e+01, 2.0240e+01, 1.4160e+01,
       1.2690e+01, 3.0110e+01, 7.8400e+00, 1.7120e+01, 7.5800e+00,
       1.8100e+01, 8.8100e+00, 8.7500e+00, 1.3170e+01, 6.7100e+00,
       2.8000e-01, 6.9200e+00, 7.9400e+00, 4.8100e+00, 7.0200e+00,
       8.1900e+00, 5.5000e-01, 9.0300e+00, 7.5900e+00, 5.3500e+00,
       6.1500e+00, 3.9000e-01, 4.6000e+00, 7.7300e+00, 3.8400e+00,
       3.5300e+00, 5.2200e+00, 4.5000e+00, 4.5500e+00, 3.6700e+00,
       2.0000e-01, 2.4600e+00, 8.9000e-01, 1.0100e+00, 1.4900e+00,
       6.9000e-01, 1.0000e-02])

## 💵 Find Unique BOAvgOpenWeekend Values

The `unique()` function is used to display all the unique values present in the **BOAvgOpenWeekend** column.  
It helps to identify the different average box office opening weekend values and understand the variation in movie performance.

In [118]:
df['BOAvgOpenWeekend'].unique()

array([3.55400e+04, 2.95070e+04, 1.75770e+04, 2.63020e+04, 1.79980e+04,
       2.14110e+04, 1.89290e+04, 1.16860e+04, 1.27500e+04, 2.28440e+04,
       1.19350e+04, 1.88770e+04, 1.20770e+04, 1.06900e+04, 1.04360e+04,
       1.29960e+04, 9.79100e+03, 1.46630e+04, 1.42640e+04, 9.23300e+03,
       9.67900e+03, 1.12110e+04, 9.79500e+03, 8.80300e+03, 9.79000e+03,
       1.01350e+04, 1.25410e+04, 8.65400e+03, 7.36100e+03, 1.09040e+04,
       6.66100e+03, 7.39600e+03, 8.72600e+03, 7.59800e+03, 9.04200e+03,
       7.30800e+03, 3.75000e+03, 9.97600e+03, 1.06450e+04, 5.00000e+03,
       7.59200e+03, 1.06180e+04, 7.79900e+03, 2.64100e+03, 5.29200e+03,
       7.44600e+03,         nan, 4.13100e+03, 6.20200e+03, 6.13500e+03,
       5.17500e+03, 4.00200e+03, 4.82600e+03, 3.85300e+03, 5.50200e+03,
       6.64400e+03, 5.36200e+03, 5.58700e+03, 3.61000e+03, 4.88900e+03,
       4.34200e+03, 6.59900e+03, 5.22600e+03, 5.67100e+03, 3.04300e+03,
       4.58300e+03, 4.08300e+03, 2.84500e+03, 2.61500e+03, 3.68600e+03,
       3.85100e+03, 4.41900e+03, 5.12800e+03, 4.00900e+03, 3.95800e+03,
       2.98000e+03, 3.32700e+03, 3.24900e+03, 1.57500e+03, 2.61700e+03,
       3.49000e+03, 2.24300e+03, 2.77500e+03, 2.14300e+03, 3.02500e+03,
       1.45900e+03, 2.71100e+03, 2.52300e+03, 2.18600e+03, 2.21300e+03,
       2.90700e+03, 3.62830e+04, 2.40240e+04, 2.35070e+04, 1.57890e+04,
       1.58030e+04, 1.46420e+04, 1.55590e+04, 2.03680e+04, 1.95680e+04,
       1.13840e+04, 1.73630e+04, 9.32500e+03, 1.40070e+04, 1.58100e+04,
       1.60400e+04, 9.89100e+03, 7.77700e+03, 7.45700e+03, 7.18200e+03,
       1.04480e+04, 1.07600e+04, 7.47700e+03, 8.30500e+03, 1.00000e+04,
       1.11300e+04, 5.31800e+03, 1.05180e+04, 9.11400e+03, 1.16010e+04,
       7.56700e+03, 7.75600e+03, 9.10300e+03, 6.27400e+03, 7.98000e+03,
       1.17440e+04, 8.98700e+03, 7.52600e+03, 1.07800e+04, 8.56200e+03,
       7.26400e+03, 4.94000e+03, 6.90900e+03, 6.86500e+03, 1.02200e+04,
       6.79100e+03, 7.21500e+03, 6.84500e+03, 5.38500e+03, 7.65500e+03,
       9.82200e+03, 8.51500e+03, 3.25500e+03, 5.35500e+03, 3.76000e+03,
       5.60200e+03, 5.40700e+03, 5.02600e+03, 3.94500e+03, 5.17400e+03,
       7.70500e+03, 6.61700e+03, 6.79000e+03, 1.00110e+04, 4.96200e+03,
       5.22500e+03, 5.16800e+03, 6.09000e+03, 4.75400e+03, 7.10400e+03,
       5.93900e+03, 8.00400e+03, 8.39700e+03, 4.98500e+03, 5.05500e+03,
       4.23300e+03, 4.83000e+03, 8.14800e+03, 3.37300e+03, 4.61700e+03,
       4.43000e+03, 4.03850e+04, 4.59400e+03, 5.77500e+03, 4.67200e+03,
       5.10100e+03, 3.68000e+03, 4.58000e+03, 4.19000e+03, 2.86000e+03,
       3.70200e+03, 4.79500e+03, 3.41500e+03, 5.58500e+03, 7.03500e+03,
       5.05400e+03, 3.79400e+03, 3.21200e+03, 3.15200e+03, 3.83100e+03,
       5.42700e+03, 2.79800e+03, 3.14700e+03, 3.13200e+03, 4.83300e+03,
       3.17400e+03, 4.21400e+03, 2.57600e+03, 2.84600e+03, 3.20900e+03,
       2.81500e+03, 2.42300e+03, 2.93700e+03, 2.20900e+03, 2.04500e+03,
       3.33000e+03, 6.79200e+03, 3.25970e+04, 1.04120e+04, 4.65500e+03,
       2.64300e+03, 1.74400e+03, 1.95300e+03, 5.01300e+03, 2.54400e+03,
       3.52800e+03, 1.62500e+03, 3.70000e+03, 1.49000e+03, 5.01500e+03,
       1.70300e+03, 2.93500e+03, 1.54800e+03, 2.82400e+03, 2.23130e+04,
       2.57360e+04, 1.79970e+04, 3.54970e+04, 1.80850e+04, 1.37590e+04,
       1.95390e+04, 1.09710e+04, 1.32100e+04, 1.71830e+04, 1.44540e+04,
       1.01710e+04, 2.07510e+04, 1.32260e+04, 1.91650e+04, 1.10040e+04,
       2.05000e+04, 1.36540e+04, 1.01250e+04, 7.76500e+03, 8.15900e+03,
       1.31000e+04, 1.20560e+04, 9.71600e+03, 1.20240e+04, 8.57600e+03,
       1.22510e+04, 1.14290e+04, 2.58130e+04, 1.52910e+04, 7.05000e+03,
       7.58000e+03, 8.50800e+03, 8.75100e+03, 9.57900e+03, 5.94700e+03,
       7.38400e+03, 1.03670e+04, 8.75400e+03, 8.14700e+03, 7.32900e+03,
       7.28000e+03, 5.20100e+03, 6.67500e+03, 6.57000e+03, 1.13180e+04,
       7.65100e+03, 8.78200e+03, 7.60300e+03, 1.30660e+04, 7.28800e+03,
       6.23300e+03, 1.11100e+04, 6.52800e+03, 8.42000e+03, 4.85400e+03,
       7.53500e+03, 8.38300e+03, 4.93300e+03, 5.35000e+03, 4.77400e+03,
       7.08000e+03, 6.01000e+03, 6.63500e+03, 6.48900e+03, 8.40500e+03,
       4.04800e+03, 6.31000e+03, 4.68100e+03, 5.42500e+03, 5.05000e+03,
       5.32000e+03, 4.05200e+03, 5.02000e+03, 1.25140e+04, 3.57300e+03,
       4.99400e+03, 5.40500e+03, 4.17700e+03, 4.57700e+03, 4.35800e+03,
       1.03980e+04, 4.80100e+03, 2.43400e+03, 4.23600e+03, 4.40500e+03,
       4.56300e+03, 4.65000e+03, 4.34400e+03, 4.84000e+03, 3.94700e+03,
       2.57800e+03, 4.04000e+03, 4.24500e+03, 3.23400e+03, 3.42600e+03,
       3.65900e+03, 3.86200e+03, 2.22400e+03, 4.11700e+03, 2.86200e+03,
       3.03000e+03, 3.63380e+04, 2.54200e+03, 1.83000e+03, 3.07300e+03,
       3.40000e+03, 2.75500e+03, 2.87300e+03, 2.64800e+03, 4.76100e+03,
       2.28500e+03, 3.13300e+03, 2.70200e+03, 1.00300e+03, 2.28600e+03,
       1.52700e+03, 1.89900e+03, 2.69400e+03, 7.34000e+03, 1.76500e+03,
       1.79100e+03, 3.61300e+03, 3.26030e+04, 2.18100e+03, 4.18900e+04,
       1.80600e+03, 4.15600e+03, 2.76900e+03, 3.29300e+03, 1.35340e+04,
       2.48200e+03, 1.35400e+03, 2.95740e+04, 1.05200e+03, 2.33300e+03,
       9.87500e+03, 3.11430e+04, 3.46900e+03, 8.74200e+03, 6.89600e+03,
       9.11500e+03, 3.93400e+03, 2.42000e+03, 3.31400e+03, 4.55500e+03,
       1.60000e+04, 1.62130e+04, 2.42400e+03, 5.78100e+03, 5.14500e+03,
       4.54290e+04, 7.47100e+03, 6.00300e+03, 1.02620e+04, 6.59500e+03,
       1.62250e+04, 4.37500e+03, 7.19100e+03, 8.08200e+03, 9.74300e+03,
       6.20900e+03, 7.49700e+03, 5.61500e+03, 2.35900e+03, 3.87300e+03,
       9.16700e+03, 2.99700e+03, 2.21100e+03, 6.51500e+03, 2.27200e+03,
       4.76500e+03, 3.93840e+04, 1.14620e+04, 2.47700e+03, 3.03070e+04,
       5.09100e+03, 1.07850e+04, 1.65570e+04, 2.92520e+04, 1.63430e+04,
       1.90400e+03, 4.52500e+03, 6.46900e+03, 5.53900e+03, 6.50100e+03,
       3.66500e+03, 4.50700e+03, 7.06900e+03, 4.56200e+03, 4.60500e+03,
       8.72000e+03, 3.96700e+03, 1.58500e+03, 4.27600e+03, 1.16680e+04,
       3.65500e+03, 2.66000e+03, 3.02000e+03, 1.26490e+04, 9.30800e+03,
       4.09200e+03, 9.27700e+03, 8.25400e+03, 6.68600e+03, 3.65700e+03,
       2.43000e+03, 8.32000e+03, 1.02950e+04, 9.97000e+03, 8.02400e+03,
       3.76500e+03, 8.99900e+03, 3.30700e+03, 1.62510e+04, 1.37290e+04,
       4.06000e+03, 2.37340e+04, 6.49400e+03, 1.26280e+04, 9.29800e+03,
       1.35350e+04, 7.26200e+03, 4.66800e+03, 3.72000e+03, 1.05400e+04,
       6.72900e+03, 6.75200e+03, 1.06500e+04, 4.84800e+03, 2.52000e+03,
       1.51970e+04, 4.16200e+03, 6.40600e+03, 1.27250e+04, 7.08700e+03,
       5.98900e+03, 3.20400e+03, 2.55200e+03, 9.73500e+03, 3.30000e+03,
       8.10000e+03, 5.02800e+03, 3.32600e+03, 4.19300e+03, 5.97700e+03,
       8.32200e+03, 1.45100e+04, 9.77000e+03, 2.73850e+04, 1.25780e+04,
       8.14900e+03, 7.07500e+03, 1.53510e+04, 3.77400e+03, 5.33300e+03,
       5.02900e+03, 1.35910e+04, 4.66900e+03, 3.67800e+03, 4.61600e+03,
       3.51700e+03, 4.50600e+03, 3.50400e+03, 3.85600e+03, 3.73100e+03,
       3.53700e+03, 8.50200e+03, 1.03650e+04, 1.04110e+04, 5.04700e+03,
       2.82680e+04, 8.99500e+03, 1.75120e+04, 1.60720e+04, 2.01980e+04,
       3.98200e+03, 3.32400e+03, 6.93500e+03, 9.71500e+03, 6.32600e+03,
       7.50000e+03, 5.46100e+03, 3.08900e+03, 3.05500e+03, 3.92900e+03,
       2.26500e+03, 3.65200e+03, 3.82000e+03, 2.36550e+04, 5.71500e+03,
       4.38300e+03, 6.36400e+03, 8.46900e+03, 1.39350e+04, 4.58800e+03,
       4.88000e+03, 5.88900e+03, 3.86720e+04, 1.04900e+04, 9.31000e+03,
       8.89900e+03, 6.16700e+03, 1.03490e+04, 3.86000e+03, 5.51100e+03,
       5.87300e+03, 7.27300e+03, 2.47000e+03, 8.60100e+03, 1.21420e+04,
       6.86000e+03, 2.21800e+03, 6.17700e+03, 8.67200e+03, 6.51600e+03,
       3.01400e+03, 5.52400e+03, 7.17400e+03, 3.71400e+03, 6.51200e+03,
       2.95500e+03, 2.74400e+03, 1.58290e+04, 2.16970e+04, 5.22100e+03,
       8.62300e+03, 9.72200e+03, 7.94200e+03, 4.62200e+03, 1.02520e+04,
       1.50240e+04, 3.39000e+03, 5.65600e+03, 3.76900e+03, 3.49520e+04,
       2.99500e+03, 1.07040e+04, 4.80200e+03, 4.78900e+03, 5.00200e+03,
       3.53400e+03, 6.28400e+03, 1.04920e+04, 1.73000e+03, 7.45000e+03,
       3.14900e+03, 3.58300e+03, 4.89000e+03, 1.51300e+03, 4.64500e+03,
       6.11100e+03, 4.96000e+03, 6.06000e+03, 3.78200e+03, 4.38200e+03,
       9.33500e+03, 2.37750e+04, 1.02780e+04, 6.74900e+03, 4.87900e+03,
       4.22600e+03, 8.50000e+03, 4.95500e+03, 5.92100e+03, 2.25900e+03,
       2.58200e+03, 1.04890e+04, 2.83500e+03, 2.87500e+03, 9.32300e+04,
       1.66180e+04, 6.77200e+03, 7.13500e+03, 2.39370e+04, 3.40120e+04,
       7.18300e+03, 6.11400e+03, 2.80500e+03, 5.97900e+03, 3.00300e+03,
       3.26700e+03, 1.51340e+04, 3.38000e+03, 5.76300e+03, 1.16320e+04,
       8.36400e+03, 5.45900e+03, 5.24700e+03, 8.64000e+03, 2.84100e+03,
       6.74000e+03, 2.27550e+04, 2.00430e+04, 1.01630e+04, 6.02000e+03,
       1.73100e+03, 8.04300e+03, 6.92000e+03, 4.24260e+04, 3.64500e+03,
       1.59280e+04, 3.38900e+03, 5.98800e+03, 2.69460e+04, 1.13300e+03,
       3.27000e+03, 7.56900e+03, 4.78700e+03, 8.50500e+03, 4.67900e+03,
       6.14000e+03, 7.90600e+03, 4.31200e+03, 1.00080e+04, 1.88300e+04,
       2.50500e+03, 9.49500e+03, 4.81800e+03, 8.47100e+03, 1.80250e+04,
       1.32170e+04, 2.37640e+04, 2.49100e+03, 3.79800e+03, 5.47200e+03,
       6.96800e+03, 4.29800e+03, 5.11600e+03, 3.45400e+03, 1.69240e+04,
       6.20500e+03, 1.26970e+04, 3.98500e+03, 7.00100e+03, 2.03410e+04,
       7.13100e+03, 1.20150e+04, 7.97300e+03, 4.53800e+03, 3.36900e+03,
       2.10180e+04, 8.05000e+03, 7.87800e+03, 1.53110e+04, 1.26330e+04,
       2.81100e+03, 1.12700e+03, 3.46300e+03, 9.69500e+03, 7.67000e+03,
       8.58460e+04, 6.95200e+03, 1.41660e+04, 1.33540e+04, 2.66900e+03,
       6.23800e+03, 4.76980e+04, 1.28510e+04, 5.03200e+03, 5.90500e+03,
       1.30749e+05, 1.48000e+03, 4.35200e+03, 8.50100e+03, 4.10800e+03,
       4.32300e+03, 1.53710e+04, 2.67400e+03, 1.50320e+04, 6.95700e+03,
       6.26900e+03, 5.24100e+03, 6.98900e+03, 6.50800e+03, 1.77700e+04,
       4.16100e+03, 1.08320e+04, 1.35770e+04, 3.48300e+03, 1.28800e+04,
       1.08620e+04, 1.25500e+04, 3.81110e+04, 6.09500e+03, 9.15300e+03,
       2.35200e+03, 2.82100e+03, 2.76880e+04, 1.04700e+03, 7.12600e+03,
       2.52110e+04, 6.88010e+04, 1.49000e+04, 5.18900e+03, 4.57000e+03,
       1.35250e+04, 9.52700e+03, 1.68000e+04, 4.44000e+03, 1.43600e+04,
       3.50800e+03, 2.72980e+04, 1.01850e+04, 5.24500e+03, 8.29600e+03,
       1.21200e+03, 3.65320e+04, 1.47630e+04, 5.79600e+03, 8.62200e+03,
       3.61400e+03, 6.17400e+03, 2.17600e+03, 2.09190e+04, 3.68710e+04,
       9.58800e+03, 7.13700e+03, 1.47262e+05, 5.70900e+04, 3.31700e+03,
       6.29700e+03, 1.71090e+04, 1.52700e+04, 2.83670e+04, 4.89200e+03,
       3.46600e+04, 1.39290e+04, 4.02500e+03, 7.31100e+03, 3.97600e+03,
       7.10300e+03, 8.22200e+03, 3.49100e+03, 1.03500e+03, 9.43800e+03,
       1.30700e+04, 8.40200e+03, 8.34300e+04, 8.41000e+02, 9.46000e+02,
       3.13100e+03, 2.67200e+03, 1.18900e+04, 8.09200e+03, 8.18300e+03,
       3.42900e+03, 6.32700e+03, 5.84000e+02, 2.18700e+03, 3.64000e+02,
       9.07000e+02, 4.09460e+04, 2.08640e+04, 3.79710e+04, 1.87490e+04,
       6.50000e+01, 2.58220e+04, 2.05870e+04, 1.46030e+04, 2.77200e+04,
       2.23220e+04, 1.07350e+04, 1.84120e+04, 2.02230e+04, 1.79590e+04,
       1.35360e+04, 1.13500e+04, 1.08470e+04, 1.16890e+04, 9.52300e+03,
       1.41090e+04, 1.34370e+04, 6.98600e+03, 9.77200e+03, 9.07700e+03,
       5.59500e+03, 7.66900e+03, 8.61100e+03, 7.48200e+03, 1.22850e+04,
       5.83400e+03, 5.98300e+03, 7.71300e+03, 4.67600e+03, 7.71700e+03,
       7.18100e+03, 1.06970e+04, 4.36900e+03, 7.39900e+03, 7.48000e+03,
       2.82000e+02, 1.27650e+04, 9.77900e+03, 9.58300e+03, 1.02130e+04,
       5.98400e+03, 8.93600e+03, 6.27000e+02, 6.78200e+03, 3.68400e+03,
       5.04600e+03, 6.76400e+03, 7.93000e+03, 5.50100e+03, 6.10500e+03,
       8.52100e+03, 8.07300e+03, 4.77000e+02, 2.80000e+01, 5.09700e+03,
       1.55000e+02, 4.23100e+03, 8.10000e+01, 1.31450e+04, 6.12900e+03,
       1.05000e+02, 5.10000e+03, 4.45000e+03, 1.47510e+04, 6.64000e+03,
       2.57700e+03, 6.82800e+03, 3.57100e+03, 2.54700e+03, 2.57000e+03,
       8.38000e+03, 4.52700e+03, 2.15600e+03, 3.31000e+03, 5.67400e+03,
       3.15900e+03, 5.24400e+03, 2.82000e+03, 1.76000e+02, 7.40000e+01,
       1.91000e+02, 2.69100e+03, 2.35000e+02, 1.51000e+02, 2.37600e+03,
       2.45900e+03, 8.30000e+01, 3.54000e+03, 2.79000e+02, 2.96000e+02,
       5.56000e+02, 5.52000e+02, 4.05000e+03, 2.88300e+03, 3.05000e+02,
       3.15400e+03, 3.30000e+02, 2.44300e+03, 2.84800e+03, 3.56000e+02,
       2.29200e+03, 1.51200e+03, 1.43500e+03, 9.83000e+02, 1.45000e+02,
       2.48500e+03, 2.75000e+02, 2.11000e+03, 1.89200e+03, 2.40600e+03,
       7.06000e+02, 2.83000e+02, 2.56000e+02, 1.94000e+02, 2.83300e+03,
       1.63000e+02, 1.51900e+03, 5.90000e+02, 3.26100e+03, 4.90000e+02,
       3.95000e+02, 7.25000e+02, 7.58000e+02, 1.48000e+02, 3.41000e+02,
       1.97800e+03, 4.74000e+02, 7.75000e+02, 8.40000e+03, 1.33510e+04,
       3.00100e+03, 1.24670e+04, 1.56400e+03])

## 💰 Find Unique Domestic Gross Values

The `unique()` function is used to display all the unique values present in the **DomesticGross** column.  
It helps to identify the different domestic box office earnings of movies and understand the variation in revenue performance.

In [119]:
df['DomesticGross'].unique()

array([3.3653e+02, 3.2272e+02, 3.1925e+02, 3.0942e+02, 2.9200e+02,
       2.5639e+02, 2.2747e+02, 2.1996e+02, 2.1733e+02, 2.1061e+02,
       2.0645e+02, 1.8314e+02, 1.6827e+02, 1.4877e+02, 1.4350e+02,
       1.4013e+02, 1.3453e+02, 1.3192e+02, 1.3016e+02, 1.2781e+02,
       1.2663e+02, 1.2146e+02, 1.2006e+02, 1.1887e+02, 1.1859e+02,
       1.1715e+02, 1.1580e+02, 1.0046e+02, 9.7820e+01, 9.5670e+01,
       9.3470e+01, 9.0650e+01, 8.2280e+01, 8.0210e+01, 7.4280e+01,
       7.0110e+01, 6.6660e+01, 6.3300e+01, 6.1360e+01, 5.8870e+01,
       5.8270e+01, 5.5200e+01, 5.4150e+01, 5.3700e+01, 5.3610e+01,
       5.2900e+01, 5.0570e+01, 4.9030e+01, 4.7850e+01, 4.7540e+01,
       4.7000e+01, 4.3800e+01, 4.3110e+01, 4.1800e+01, 4.0220e+01,
       3.9740e+01, 3.9690e+01, 3.9570e+01, 3.8630e+01, 3.6790e+01,
       3.5790e+01, 3.5020e+01, 3.3080e+01, 3.2060e+01, 2.8560e+01,
       2.8550e+01, 2.5930e+01, 2.5610e+01, 2.5590e+01, 2.5130e+01,
       2.5040e+01, 2.4540e+01, 2.4340e+01, 2.0800e+01, 1.9360e+01,
       1.9070e+01, 1.8350e+01, 1.8320e+01, 1.8210e+01, 1.7610e+01,
       1.5800e+01, 1.5590e+01, 1.5070e+01, 1.5000e+01, 1.3240e+01,
       1.2810e+01, 1.1900e+01, 1.1050e+01, 1.0980e+01, 1.0230e+01,
       5.3486e+02, 3.1876e+02, 3.1710e+02, 2.2795e+02, 2.2381e+02,
       2.1543e+02, 1.8001e+02, 1.9277e+02, 1.6837e+02, 1.5453e+02,
       1.5265e+02, 1.4810e+02, 1.4413e+02, 1.4162e+02, 1.4132e+02,
       1.3481e+02, 1.3451e+02, 1.3032e+02, 1.2015e+02, 1.1052e+02,
       1.1010e+02, 1.1405e+02, 1.4315e+02, 1.0249e+02, 1.0170e+02,
       1.0144e+02, 1.0047e+02, 1.0002e+02, 9.7690e+01, 9.4780e+01,
       9.4510e+01, 9.0560e+01, 8.7340e+01, 8.3080e+01, 8.1160e+01,
       8.0280e+01, 8.0170e+01, 8.0050e+01, 1.2751e+02, 7.6810e+01,
       7.5990e+01, 7.9370e+01, 7.2270e+01, 7.1200e+01, 7.0230e+01,
       6.7290e+01, 6.4510e+01, 6.3170e+01, 6.0360e+01, 6.0490e+01,
       6.9950e+01, 5.8020e+01, 5.6750e+01, 5.2600e+01, 5.2080e+01,
       5.0880e+01, 4.8240e+01, 4.8010e+01, 4.9550e+01, 4.6010e+01,
       4.5610e+01, 4.4090e+01, 4.3950e+01, 4.3870e+01, 4.2750e+01,
       4.2440e+01, 4.1980e+01, 4.1850e+01, 4.0690e+01, 4.0080e+01,
       3.9260e+01, 3.9390e+01, 3.8230e+01, 3.8110e+01, 3.7930e+01,
       3.7770e+01, 3.7110e+01, 3.6320e+01, 3.5740e+01, 3.5160e+01,
       3.3480e+01, 3.3460e+01, 3.2860e+01, 3.2240e+01, 3.1840e+01,
       3.1720e+01, 3.1690e+01, 3.1490e+01, 3.1420e+01, 3.1460e+01,
       3.1370e+01, 3.0690e+01, 3.0110e+01, 3.0060e+01, 2.8690e+01,
       2.6900e+01, 2.6890e+01, 2.6810e+01, 2.6420e+01, 2.5880e+01,
       2.5530e+01, 2.4850e+01, 2.3530e+01, 2.3220e+01, 2.2530e+01,
       2.0980e+01, 2.0670e+01, 2.0210e+01, 1.9530e+01, 1.9220e+01,
       3.3450e+01, 1.9810e+01, 1.7660e+01, 1.7430e+01, 1.7210e+01,
       1.6290e+01, 1.5740e+01, 1.5300e+01, 1.4190e+01, 1.3850e+01,
       1.3560e+01, 1.3370e+01, 1.3010e+01, 1.2800e+01, 1.2980e+01,
       1.2590e+01, 1.2310e+01, 1.2080e+01, 1.1800e+01, 1.1540e+01,
       1.1180e+01, 1.1010e+01, 1.0920e+01, 1.0010e+01, 9.7900e+00,
       9.5100e+00, 9.4300e+00, 9.0500e+00, 8.4000e+00, 8.2000e+00,
       8.0500e+00, 7.9200e+00, 7.8700e+00, 7.8000e+00, 7.7200e+00,
       7.5600e+00, 7.6050e+02, 4.0210e+02, 3.0200e+02, 2.9662e+02,
       2.9300e+02, 2.7730e+02, 2.5770e+02, 2.5596e+02, 2.1950e+02,
       2.0902e+02, 1.9840e+02, 1.9657e+02, 1.7990e+02, 1.7720e+02,
       1.6612e+02, 1.6396e+02, 1.5510e+02, 1.5020e+02, 1.4633e+02,
       1.4500e+02, 1.3790e+02, 1.3340e+02, 1.2530e+02, 1.2490e+02,
       1.2050e+02, 1.1940e+02, 1.1560e+02, 1.1273e+02, 1.0920e+02,
       1.0792e+02, 1.0750e+02, 1.0440e+02, 9.7100e+01, 9.4120e+01,
       9.3950e+01, 8.8900e+01, 8.3820e+01, 7.9950e+01, 7.9580e+01,
       7.7230e+01, 7.5590e+01, 7.5280e+01, 7.3400e+01, 7.3000e+01,
       7.2100e+01, 7.1400e+01, 6.8260e+01, 6.7170e+01, 6.6500e+01,
       6.5450e+01, 6.5000e+01, 6.4200e+01, 6.3410e+01, 6.0100e+01,
       5.8750e+01, 5.5390e+01, 5.5250e+01, 5.1850e+01, 5.1540e+01,
       4.9490e+01, 4.9430e+01, 4.9200e+01, 4.5800e+01, 4.4270e+01,
       4.4000e+01, 4.3330e+01, 4.2670e+01, 4.2190e+01, 4.2100e+01,
       4.1590e+01, 4.0570e+01, 3.8570e+01, 3.8120e+01, 3.7490e+01,
       3.7020e+01, 3.6840e+01, 3.5920e+01, 3.3860e+01, 3.3390e+01,
       3.3310e+01, 3.2400e+01, 3.2390e+01, 3.1810e+01, 3.1740e+01,
       3.1700e+01, 2.9580e+01, 2.9100e+01, 2.8600e+01, 2.8500e+01,
       2.7690e+01, 2.5660e+01, 2.5480e+01, 2.5400e+01, 2.5200e+01,
       2.4000e+01, 2.2960e+01, 2.2460e+01, 2.1000e+01, 2.0530e+01,
       1.9670e+01, 1.9550e+01, 1.8450e+01, 1.7300e+01, 1.7200e+01,
       1.7010e+01, 1.6200e+01, 1.6120e+01, 1.6040e+01, 1.5990e+01,
       1.5500e+01, 1.5100e+01, 1.4800e+01, 1.4250e+01, 1.3870e+01,
       1.3700e+01, 1.3000e+01, 1.2570e+01, 1.2230e+01, 1.2060e+01,
       1.1970e+01, 1.0800e+01, 1.0600e+01, 1.0300e+01, 1.0280e+01,
       1.0000e+01, 9.4500e+00, 9.3600e+00, 9.2300e+00, 9.2000e+00,
       8.7400e+00, 8.6700e+00, 8.0100e+00, 8.1200e+00, 7.4600e+00,
       6.3800e+00, 5.3000e+00, 5.2000e+00, 1.8330e+01, 6.3080e+01,
       3.3419e+02, 2.5110e+01, 1.0695e+02, 2.7160e+01, 1.0400e+00,
       3.9440e+01, 1.3260e+01, 4.3590e+01, 3.1160e+01, 6.6700e+00,
       1.6321e+02, 6.7900e+00, 4.4880e+01, 2.0220e+01, 7.4700e+00,
       9.8710e+01, 3.0100e+01, 8.0010e+01, 4.2740e+01, 2.5151e+02,
       3.3600e+01, 6.4000e+01, 7.3030e+01, 1.0054e+02, 5.8400e+01,
       8.0570e+01, 4.3310e+01, 1.2070e+01, 2.3240e+01, 3.7730e+01,
       2.4080e+01, 1.7630e+01, 6.0970e+01, 1.7800e+01, 3.5050e+01,
       4.2300e+00, 1.6200e+02, 4.2780e+01, 2.9500e+02, 5.0290e+01,
       2.1758e+02, 2.0400e+00, 2.9258e+02, 3.1243e+02, 1.1723e+02,
       1.0550e+01, 2.1540e+01, 4.8070e+01, 4.7060e+01, 7.6420e+01,
       2.5920e+01, 5.5680e+01, 4.0170e+01, 5.3030e+01, 5.3130e+01,
       1.4844e+02, 3.2370e+01, 8.5300e+00, 2.6590e+01, 3.3640e+01,
       1.4842e+02, 3.1010e+01, 1.4740e+01, 2.9010e+01, 2.4300e+00,
       2.0260e+01, 8.4750e+01, 8.8770e+01, 2.5000e+01, 4.0300e+00,
       5.2000e+01, 9.0760e+01, 9.0380e+01, 1.3790e+01, 6.0130e+01,
       1.0527e+02, 1.1831e+02, 4.5710e+01, 3.1520e+01, 9.5350e+01,
       3.2010e+01, 2.3874e+02, 1.2801e+02, 2.1390e+01, 4.3600e+00,
       4.2400e+01, 1.8100e+00, 5.7740e+01, 2.0082e+02, 7.7220e+01,
       3.5610e+01, 9.4840e+01, 6.7060e+01, 1.0439e+02, 3.9120e+01,
       1.0307e+02, 9.3620e+01, 1.5540e+01, 1.4800e+00, 1.7659e+02,
       2.0810e+01, 1.3879e+02, 1.3177e+02, 4.1030e+01, 6.2950e+01,
       2.3590e+01, 2.1150e+01, 1.1922e+02, 3.5700e+00, 9.6960e+01,
       6.3150e+01, 2.4310e+01, 2.7780e+01, 6.7630e+01, 9.2190e+01,
       3.0053e+02, 6.1980e+01, 6.0020e+01, 4.1500e+02, 1.7206e+02,
       1.7124e+02, 8.1560e+01, 1.1049e+02, 3.6660e+01, 5.2470e+01,
       3.2680e+01, 6.0090e+01, 1.0025e+02, 2.5700e+01, 3.2400e+00,
       1.5280e+01, 3.7050e+01, 3.5010e+01, 5.7000e+00, 3.5060e+01,
       2.8090e+01, 4.4600e+00, 1.3200e+00, 1.7690e+01, 3.3040e+01,
       4.6460e+01, 6.9000e+01, 1.0029e+02, 8.3550e+01, 2.7870e+01,
       5.7900e+00, 1.6911e+02, 1.7665e+02, 1.9145e+02, 6.8600e+00,
       3.6670e+01, 2.1300e+01, 7.5660e+01, 1.0024e+02, 8.4350e+01,
       5.2700e+01, 7.2290e+01, 2.4050e+01, 1.0720e+01, 1.1900e+00,
       2.7100e+00, 3.1847e+01, 2.0940e+02, 4.2590e+01, 5.1800e+01,
       5.5800e+01, 1.8300e+01, 9.9970e+01, 1.1660e+02, 4.5060e+01,
       4.0260e+01, 6.4010e+01, 3.8101e+02, 1.0809e+02, 1.1754e+02,
       7.3864e+01, 5.5100e+01, 8.3500e+01, 3.7520e+01, 5.4010e+01,
       3.7310e+01, 7.4160e+01, 8.3100e+00, 1.0303e+02, 2.5120e+01,
       1.6525e+02, 7.9250e+01, 5.4000e-01, 5.3500e+00, 5.6820e+01,
       2.0939e+02, 7.5600e+01, 2.3190e+01, 6.8220e+01, 1.4600e+01,
       5.4540e+01, 7.0660e+01, 1.3840e+01, 2.4820e+01, 1.0403e+02,
       3.7410e+01, 2.4107e+02, 2.9140e+01, 1.4926e+02, 1.2348e+02,
       8.5470e+01, 3.7660e+01, 1.1000e+00, 1.4362e+02, 1.7670e+02,
       2.3210e+01, 3.8180e+01, 2.4830e+01, 3.0900e+00, 1.8880e+01,
       1.8685e+02, 3.9050e+01, 4.3850e+01, 5.4710e+01, 3.8540e+01,
       3.6390e+01, 1.2700e+02, 6.9300e+00, 1.7300e+00, 6.2500e+01,
       7.7591e+01, 4.4671e+01, 9.7000e-01, 7.2000e+00, 3.7080e+01,
       4.4400e+00, 3.1180e+01, 8.2580e+01, 4.8480e+01, 1.9490e+01,
       1.0206e+02, 9.8780e+01, 2.5446e+02, 1.6971e+02, 4.0960e+01,
       3.0017e+01, 5.8010e+01, 2.9120e+01, 8.8630e+01, 3.3050e+01,
       3.7300e+01, 1.3110e+01, 3.0441e+01, 1.4261e+02, 1.6930e+01,
       2.0370e+01, 1.3300e+01, 1.8103e+02, 2.4149e+01, 7.8040e+01,
       3.5239e+02, 2.8129e+02, 6.3690e+01, 7.9884e+01, 1.3660e+01,
       5.8710e+01, 7.5624e+01, 1.4010e+01, 2.6690e+01, 1.4641e+02,
       2.1600e+01, 8.0360e+01, 1.3845e+02, 1.5600e+00, 1.5500e+00,
       1.9900e+00, 3.0100e+00, 5.7010e+01, 6.7400e+00, 1.2820e+01,
       1.3603e+02, 3.3400e+00, 2.8000e+00, 6.5420e+01, 2.0160e+01,
       2.3728e+02, 3.8600e+00, 5.9100e+00, 6.0000e+00, 1.8120e+01,
       6.4580e+01, 2.7110e+01, 6.6530e+01, 1.8300e+00, 2.5200e+00,
       7.9730e+01, 4.9010e+01, 1.6281e+02, 2.1403e+02, 1.3410e+01,
       2.3500e+00, 4.1000e+01, 1.8600e+00, 1.6000e+00, 9.3770e+01,
       2.0100e+00, 5.6700e+00, 3.5290e+01, 7.2500e+00, 5.1770e+01,
       2.6100e+00, 4.1700e+00, 1.8940e+01, 6.0100e+00, 6.3540e+01,
       1.4831e+02, 3.1610e+01, 1.7900e+00, 1.8000e+00, 1.6132e+02,
       3.0500e+00, 8.0070e+01, 4.2700e+00, 2.5500e+00, 7.3080e+01,
       1.0386e+02, 2.5330e+01, 1.4700e+00, 1.5030e+01, 3.3300e+00,
       3.7400e+01, 1.4881e+02, 1.2499e+02, 1.8221e+02, 6.6490e+01,
       2.1639e+02, 1.1372e+02, 1.8620e+01, 1.4100e+00, 6.2336e+02,
       1.7902e+02, 6.4940e+01, 4.5510e+01, 3.3800e+00, 5.1600e+00,
       5.3920e+01, 5.6000e+01, 7.7270e+01, 2.0280e+01, 1.2648e+02,
       7.6000e+00, 3.1300e+00, 4.4810e+01, 4.9880e+01, 4.2350e+01,
       1.0341e+02, 3.8520e+01, 2.5400e+00, 2.0600e+00, 1.7140e+01,
       1.2637e+02, 4.0100e+00, 2.6700e+00, 4.7380e+01, 3.7000e+00,
       7.0800e+00, 1.5020e+01, 1.3209e+02, 1.6100e+00, 4.8090e+01,
       3.0436e+02, 2.2700e+00, 1.5533e+02, 2.4400e+01, 3.5070e+01,
       1.3985e+02, 2.8700e+00, 2.1882e+02, 3.6930e+01, 2.6203e+02,
       4.9400e+00, 4.6410e+01, 1.1320e+02, 4.2070e+01, 8.6910e+01,
       3.7600e+00, 6.8400e+00, 4.4814e+02, 5.3260e+01, 5.9650e+01,
       8.5030e+01, 2.8840e+01, 5.1580e+01, 3.7130e+01, 3.0300e+02,
       4.0801e+02, 1.9020e+01, 6.0460e+01, 1.6380e+01, 1.7740e+01,
       3.1050e+01, 4.9130e+01, 2.4000e+00, 4.1100e+00, 4.4340e+01,
       2.9232e+02, 1.2501e+02, 3.5350e+01, 5.4330e+01, 6.7540e+01,
       5.8880e+01, 6.2320e+01, 4.1150e+01, 5.3100e+00, 8.3670e+01,
       1.8942e+02, 1.6400e+00, 9.5720e+01, 1.5320e+01, 3.2600e+00,
       1.7620e+01, 3.4900e+00, 1.3367e+02, 6.0520e+01, 1.0624e+02,
       6.1000e+01, 1.7100e+00, 3.4690e+01, 1.6300e+00, 4.0901e+02,
       3.6806e+02, 4.2002e+02, 2.5233e+02, 3.4790e+02, 2.3868e+02,
       2.6849e+02, 2.6121e+02, 2.9105e+02, 2.0451e+02, 1.8717e+02,
       2.0236e+02, 2.3491e+02, 2.2878e+02, 1.3256e+02, 1.0180e+02,
       1.2252e+02, 1.1220e+02, 1.1772e+02, 1.4484e+02, 7.1020e+01,
       1.3740e+02, 6.7350e+01, 8.9110e+01, 9.3050e+01, 8.3030e+01,
       1.5039e+02, 1.0752e+02, 8.9300e+01, 1.5958e+02, 5.5700e+01,
       9.0290e+01, 7.3100e+01, 6.8560e+01, 6.5190e+01, 9.8510e+01,
       5.6340e+01, 1.2380e+02, 8.3590e+01, 9.8930e+01, 1.0200e+02,
       7.1630e+01, 7.5610e+01, 4.9280e+01, 1.0147e+02, 3.8060e+01,
       6.3750e+01, 6.6380e+01, 6.1740e+01, 4.6000e+01, 4.2030e+01,
       5.4240e+01, 9.5020e+01, 3.3200e+01, 9.3910e+01, 4.4670e+01,
       7.9160e+01, 5.5440e+01, 3.1170e+01, 2.6950e+01, 6.4470e+01,
       3.3220e+01, 3.5270e+01, 3.2020e+01, 3.3620e+01, 7.0530e+01,
       7.1350e+01, 1.6970e+01, 5.1870e+01, 3.2170e+01, 1.9320e+01,
       1.9450e+01, 4.0040e+01, 2.8800e+01, 1.8390e+01, 1.2050e+01,
       2.6630e+01, 2.6000e+01, 2.5680e+01, 4.2930e+01, 1.6130e+01,
       2.1400e+01, 2.6510e+01, 1.4120e+01, 3.0130e+01, 2.4480e+01,
       2.4120e+01, 8.8400e+00, 2.9240e+01, 8.0800e+00, 1.7420e+01,
       1.7550e+01, 2.3300e+00, 1.2000e+01, 2.1510e+01, 2.1570e+01,
       2.1820e+01, 2.4500e+00, 1.9700e+01, 5.8500e+00, 1.0900e+01,
       1.8010e+01, 1.6100e+01, 8.8900e+00, 1.5180e+01, 7.3900e+00,
       1.3700e+00, 1.1720e+01, 1.1310e+01, 8.1100e+00, 1.0500e+01,
       9.4900e+00, 7.0200e+00, 2.1600e+00, 1.7000e+00, 6.8500e+00,
       6.2200e+00, 5.7500e+00, 5.1300e+00, 2.1900e+00, 4.0700e+00,
       3.3500e+00, 3.3100e+00, 2.9600e+00, 2.3000e+00, 2.3400e+00,
       2.2900e+00, 1.9700e+00, 1.3800e+00, 1.3500e+00, 4.3300e+00,
       1.1663e+02, 6.0000e-02, 1.0000e-01, 1.4000e-01, 3.6000e-01])

## 🌍 Find Unique Foreign Gross Values

The `unique()` function is used to display all the unique values present in the **ForeignGross** column.  
It helps to identify the different international box office earnings of movies and understand the variation in foreign revenue performance.

In [120]:
df['ForeignGross'].unique()

array([5.54340e+02, 4.76240e+02, 3.90460e+02, 6.54000e+02, 6.47880e+02,
       3.28960e+02, 2.15350e+02, 2.37400e+02, 1.44010e+02, 2.45450e+02,
       4.17280e+02, 3.43940e+02, 8.53500e+01, 7.03100e+01, 8.79200e+01,
       1.17900e+02, 2.49000e+02, 1.57130e+02, 1.36300e+02, 2.12680e+02,
       1.60960e+02, 4.84100e+01, 6.60100e+01, 8.36800e+01, 2.71100e+01,
       1.94160e+02, 1.12940e+02, 7.29600e+01, 7.15100e+01, 6.36400e+01,
       8.19100e+01, 5.72300e+01, 1.14110e+02, 3.75500e+01, 9.73400e+01,
       3.02130e+02, 5.23400e+01, 7.60500e+01, 1.41500e+01, 9.01800e+01,
       2.19800e+01, 6.60000e-01, 4.14600e+01, 1.03140e+02, 1.64100e+01,
       9.96300e+01, 9.53200e+01, 4.39600e+01, 3.62900e+01, 3.91200e+01,
       4.86900e+01, 2.55100e+01, 4.94900e+01, 8.70900e+01, 3.59600e+01,
       4.71300e+01, 6.02800e+01, 3.59400e+01, 9.69300e+01, 3.29900e+01,
       9.09800e+01, 2.13200e+01, 2.41700e+01, 5.17100e+01, 3.74100e+01,
       2.63600e+01, 1.95700e+01, 2.18100e+01, 5.05000e+00, 3.17000e+01,
       3.76400e+01, 3.80000e-01, 1.15500e+01, 5.02000e+00, 1.66600e+01,
       1.59400e+01, 3.10000e+00, 3.79000e+01, 2.26000e+00, 5.78600e+01,
       1.80100e+01, 5.74800e+01, 2.25000e+01, 2.51000e+01, 4.82100e+01,
       4.96000e+00, 1.40100e+01, 2.31800e+01, 6.51000e+00, 6.41300e+01,
       2.05900e+01, 4.69700e+02, 2.66760e+02, 4.69530e+02, 3.96440e+02,
       2.97500e+02, 4.16310e+02, 4.23890e+02, 1.99850e+02, 4.17720e+02,
       1.42610e+02, 2.62610e+02, 1.21860e+02, 4.65710e+02, 2.78040e+02,
       2.36590e+02, 1.28620e+02, 2.06920e+02, 1.00370e+02, 4.35900e+01,
       7.75600e+01, 1.02770e+02, 1.95930e+02, 9.95600e+01, 2.98640e+02,
       1.40290e+02, 7.66300e+01, 2.76400e+01, 9.99200e+01, 1.25550e+02,
       1.75000e+02, 5.47700e+01, 1.62350e+02, 1.42800e+01, 1.17200e+02,
       7.67700e+01, 1.39100e+02, 1.42060e+02, 9.07200e+01, 2.06420e+02,
       8.34500e+01, 8.44000e+01, 1.53730e+02, 7.89000e+01, 9.16400e+01,
       4.10000e+01, 2.50900e+01, 9.89000e+01, 4.20000e+01, 1.03360e+02,
       3.67000e+00, 9.82200e+01, 9.28000e+01, 5.71200e+01, 2.97900e+01,
       7.59000e+01, 3.60700e+01, 2.22100e+01, 5.20700e+01, 1.61790e+02,
       5.99500e+01, 5.94000e+00, 2.60000e-01, 5.00000e+01, 1.33300e+01,
       7.04900e+01, 1.21000e+00,         nan, 4.25200e+01, 4.47300e+01,
       3.83800e+01, 5.39000e+00, 7.57000e+01, 4.64100e+01, 5.38000e+00,
       8.70000e-01, 2.18000e+00, 3.93600e+01, 7.72800e+01, 3.31200e+01,
       1.04100e+01, 2.00000e-02, 1.68300e+01, 8.63000e+00, 2.32100e+01,
       2.27500e+01, 7.72600e+01, 9.63000e+00, 2.02000e+00, 2.55500e+01,
       1.06500e+01, 9.93000e+00, 4.68000e+01, 3.47300e+01, 3.47600e+01,
       2.39700e+01, 2.31100e+01, 1.89600e+01, 5.09000e+01, 3.91500e+01,
       2.19500e+01, 4.53600e+01, 3.97000e+00, 1.67800e+01, 4.13000e+00,
       7.31900e+01, 4.95800e+01, 4.73900e+01, 5.74000e+00, 7.45000e+00,
       1.12200e+01, 2.24000e+01, 1.74600e+01, 1.92300e+01, 5.30000e+00,
       1.53800e+01, 1.34000e+00, 1.54100e+01, 2.71900e+01, 2.06300e+01,
       2.94600e+01, 1.86000e+00, 1.37100e+01, 6.30000e-01, 3.83000e+00,
       1.70000e-01, 1.07200e+01, 4.41000e+00, 2.50000e-01, 3.88500e+01,
       2.30000e-01, 1.94000e+01, 1.12000e+01, 2.90000e-01, 1.11400e+01,
       1.00000e-02, 2.33000e+00, 8.65000e+00, 3.13700e+01, 1.03500e+01,
       6.80000e-01, 2.05000e+00, 1.40000e+00, 1.00600e+01, 2.55900e+01,
       1.38900e+01, 2.02100e+03, 4.34200e+02, 6.32000e+02, 4.13200e+02,
       4.38300e+02, 1.90160e+02, 1.27950e+02, 5.32400e+01, 2.23000e+02,
       3.15000e+02, 1.83200e+02, 6.90110e+02, 1.93200e+02, 2.35800e+02,
       6.03570e+02, 1.53420e+02, 2.08000e+02, 1.52260e+02, 3.69500e+01,
       8.18000e+01, 1.87430e+02, 3.52600e+02, 2.46700e+02, 1.18130e+02,
       2.00910e+02, 1.73380e+02, 9.51700e+01, 1.06370e+02, 6.26300e+01,
       8.54400e+01, 7.77000e+01, 1.62640e+02, 1.17000e+02, 3.24500e+01,
       8.48900e+01, 1.16380e+02, 1.03630e+02, 7.59700e+01, 2.28500e+01,
       2.68000e+01, 4.93000e+01, 5.30800e+01, 4.39700e+01, 1.89090e+02,
       2.02000e+01, 5.56000e+00, 3.92100e+01, 1.19690e+02, 8.47100e+01,
       2.64000e+01, 7.21000e+01, 3.79200e+01, 7.87500e+01, 5.59500e+01,
       2.21300e+01, 4.69700e+01, 1.97300e+01, 4.91900e+01, 4.72600e+01,
       1.93400e+01, 4.65100e+01, 4.55500e+01, 6.40500e+01, 4.95100e+01,
       1.90200e+01, 3.38400e+01, 6.34500e+01, 4.87000e+01, 3.51000e+01,
       3.75700e+01, 8.38600e+01, 2.34700e+01, 8.47400e+01, 5.07900e+01,
       7.52000e+00, 4.00200e+01, 6.26000e+00, 6.02000e+00, 8.45000e+00,
       3.65400e+01, 2.83300e+01, 1.70400e+01, 1.66700e+01, 6.61000e+00,
       5.57000e+01, 2.13000e+00, 1.30300e+01, 1.47700e+01, 4.05000e+01,
       5.77000e+00, 2.22200e+01, 3.47000e+01, 3.26800e+01, 2.96000e+00,
       1.31200e+01, 5.47600e+01, 2.54600e+01, 2.02900e+01, 3.43200e+01,
       2.03400e+01, 1.39500e+01, 4.51400e+01, 1.37000e+00, 3.22100e+01,
       1.53500e+01, 6.86000e+00, 1.12000e+00, 6.95000e+00, 7.33000e+00,
       1.82800e+01, 1.02000e+00, 5.40000e+00, 2.53600e+01, 2.08000e+01,
       3.59000e+00, 1.35200e+01, 4.51000e+00, 1.52400e+01, 3.00000e-02,
       1.40000e-01, 1.03100e+01, 7.57000e+00, 1.50000e-01, 5.44000e+00,
       4.81300e+01, 2.22000e+01, 7.20000e+00, 4.02000e+00, 1.17900e+01,
       1.95100e+01, 2.52000e+00, 7.01000e+00, 4.24000e+01, 5.25900e+01,
       6.91280e+02, 2.54000e+01, 2.22440e+02, 9.28000e+00, 1.81100e+01,
       5.00800e+01, 1.49300e+01, 6.89000e+01, 1.70300e+01, 1.20000e+00,
       3.30000e+02, 2.92000e+00, 1.07100e+01, 3.10000e-01, 2.45000e+00,
       5.35500e+01, 2.13100e+01, 3.49600e+01, 6.31000e+00, 2.91600e+02,
       2.90900e+01, 1.17000e+01, 1.38300e+01, 1.11240e+02, 1.65500e+01,
       1.24020e+02, 3.78100e+01, 3.07000e+00, 1.23900e+01, 1.73200e+01,
       2.87500e+01, 1.86100e+01, 3.02900e+01, 2.42500e+01, 5.98300e+01,
       1.92000e+00, 1.09430e+02, 1.94600e+02, 6.64300e+02, 2.77300e+02,
       1.86900e+01, 5.32960e+02, 3.11500e+02, 5.44600e+01, 3.60000e-01,
       4.81200e+01, 5.11000e+01, 1.85510e+02, 6.69000e+00, 2.77500e+01,
       2.61500e+01, 4.30300e+01, 1.62210e+02, 7.04400e+01, 8.00000e-01,
       1.75000e+01, 5.01200e+01, 1.73470e+02, 2.90300e+01, 6.23000e+00,
       6.42300e+01, 7.02000e+00, 1.15000e+00, 9.27600e+01, 1.37730e+02,
       5.81900e+01, 2.80000e-01, 7.52300e+01, 2.45610e+02, 1.08630e+02,
       3.69600e+01, 4.62000e+00, 2.36090e+02, 2.16400e+02, 1.75190e+02,
       9.04400e+01, 1.61400e+01, 1.93000e+02, 1.77700e+01, 5.13860e+02,
       1.66790e+02, 4.54300e+01, 8.20000e-01, 1.16890e+02, 7.67000e+00,
       1.13100e+01, 3.90970e+02, 1.00020e+02, 3.22700e+01, 3.99900e+01,
       6.22700e+01, 6.92700e+01, 3.11300e+02, 1.56800e+01, 1.71400e+02,
       3.55400e+01, 4.46800e+01, 4.90000e-01, 1.82530e+02, 2.75410e+02,
       1.87940e+02, 2.67000e+01, 2.60900e+01, 5.79000e+00, 4.63000e+01,
       5.12100e+01, 1.11000e+00, 1.27960e+02, 1.52130e+02, 2.09300e+01,
       2.20500e+01, 2.10720e+02, 6.18400e+01, 3.97960e+02, 7.78100e+01,
       5.24400e+01, 6.48160e+02, 2.28000e+02, 8.10300e+01, 8.62400e+01,
       1.06000e+02, 4.38900e+01, 8.22700e+01, 1.03600e+01, 5.80000e-01,
       1.01340e+02, 6.30000e+00, 3.10300e+01, 4.37000e+00, 3.49000e+00,
       4.17000e+00, 2.17600e+01, 3.30000e-01, 5.40000e+01, 1.09300e+01,
       4.50000e-01, 7.88000e+00, 1.27000e+01, 1.00950e+02, 1.10000e+02,
       1.15900e+02, 1.28270e+02, 1.53000e+01, 8.52000e+00, 1.19280e+02,
       1.93920e+02, 3.68400e+02, 2.43000e+01, 2.75000e+01, 5.98000e+01,
       7.45800e+01, 5.85000e+01, 1.97200e+01, 2.31200e+01, 1.29500e+01,
       1.72000e+01, 4.11100e+01, 1.82100e+01, 3.45000e+00, 2.34000e+01,
       4.16300e+02, 1.15300e+02, 1.17400e+01, 9.37400e+01, 2.27000e+01,
       9.40000e+01, 1.03250e+02, 3.81000e+01, 2.35200e+01, 8.64000e+01,
       9.60500e+02, 7.58700e+01, 9.21000e+01, 1.11905e+02, 9.47800e+01,
       1.43400e+02, 1.36410e+02, 4.30000e+01, 4.73000e+01, 7.55200e+01,
       1.51770e+02, 1.11920e+02, 3.12600e+01, 5.00440e+02, 3.64000e+01,
       8.26000e+01, 5.70000e-01, 1.76000e+01, 9.43000e+01, 4.85320e+02,
       3.46000e+01, 1.64800e+01, 1.19140e+02, 2.04600e+01, 8.75000e+01,
       7.85700e+01, 1.03010e+02, 6.05700e+01, 8.04640e+02, 4.91700e+01,
       4.05730e+02, 1.22250e+02, 2.13800e+02, 5.15000e+01, 3.41020e+02,
       3.05040e+02, 8.54000e+01, 5.89600e+01, 6.68000e+01, 1.37840e+01,
       2.12600e+01, 3.58600e+02, 2.11400e+01, 3.24000e+00, 9.26200e+01,
       4.70300e+01, 5.34000e+01, 1.33090e+02, 6.53700e+01, 2.96402e+02,
       8.87610e+01, 2.40000e-01, 3.83700e+01, 4.40000e-01, 3.94000e+00,
       1.44600e+01, 9.46600e+01, 2.12500e+01, 7.63000e+00, 1.30101e+02,
       1.29040e+02, 3.32300e+02, 4.69300e+01, 3.50300e+01, 8.49380e+01,
       1.70000e+01, 7.65500e+01, 6.30000e+01, 3.19000e+00, 1.08400e+01,
       4.50000e+00, 4.21140e+02, 1.05000e+01, 1.11900e+02, 2.68290e+02,
       5.64810e+01, 7.48800e+01, 7.71400e+02, 4.30880e+02, 6.71000e+01,
       9.77000e+01, 9.40000e+00, 5.83900e+01, 4.44570e+01, 1.64200e+01,
       6.46000e+00, 2.07220e+02, 3.26000e+00, 8.94900e+01, 6.31400e+01,
       7.89500e+01, 1.77980e+02, 5.61100e+01, 2.75700e+01, 9.63000e+01,
       2.37600e+02, 4.56000e+00, 3.01700e+02, 1.90400e+01, 6.20600e+01,
       1.03370e+02, 2.97300e+01, 1.65800e+02, 2.81000e+01, 2.62560e+02,
       1.34810e+02, 7.12000e+00, 6.80000e+01, 4.62000e+01, 8.07900e+01,
       1.44300e+01, 5.07500e+01, 2.10060e+02, 7.85000e+00, 7.15920e+02,
       1.38270e+02, 2.11060e+02, 2.31400e+02, 7.40000e+00, 2.29000e+01,
       1.62800e+01, 2.93000e+02, 4.84030e+02, 9.30900e+01, 1.10020e+02,
       5.30530e+02, 5.35000e+01, 2.76000e+01, 8.95240e+02, 4.45010e+02,
       1.01240e+02, 8.89200e+01, 5.11400e+01, 4.25000e+01, 4.80400e+01,
       1.08100e+01, 2.76880e+02, 1.97810e+02, 2.03530e+02, 2.09000e+01,
       2.32000e+01, 8.17000e+01, 2.55200e+01, 3.55800e+01, 4.40000e+00,
       1.04320e+02, 2.96300e+01, 8.04200e+02, 2.41260e+02, 1.05400e+02,
       2.36290e+02, 3.30550e+02, 2.07900e+01, 4.90190e+02, 9.04200e+01,
       1.62940e+02, 2.44100e+01, 1.80000e+01, 6.36300e+02, 4.85000e+01,
       1.19730e+02, 2.20400e+02, 2.50700e+01, 2.57000e+01, 4.73000e+00,
       7.14000e+02, 2.83240e+02, 1.61250e+02, 3.89000e+01, 1.18800e+01,
       1.56400e+01, 9.20000e+01, 3.63200e+01, 1.04800e+01, 5.37360e+02,
       7.11000e+01, 3.29100e+01, 7.34000e+01, 2.05100e+01, 1.39590e+02,
       9.77900e+01, 4.32300e+01, 2.21600e+02, 2.81800e+02, 3.71000e+01,
       7.17800e+01, 2.86000e+01, 7.00000e-02, 1.13320e+02, 1.83320e+02,
       1.10240e+02, 1.08240e+02, 6.11200e+01, 7.85000e+01, 8.39000e+00,
       8.06430e+02, 5.96700e+02, 4.35870e+02, 5.95000e+02, 4.62500e+02,
       5.50000e+02, 4.75070e+02, 4.27300e+02, 3.77000e+02, 4.28400e+02,
       4.00040e+02, 3.37650e+02, 2.58400e+02, 2.38590e+02, 2.82270e+02,
       3.09200e+02, 2.53220e+02, 2.49800e+02, 2.34000e+02, 2.06200e+02,
       2.76530e+02, 1.80600e+02, 2.37300e+02, 1.97060e+02, 1.93090e+02,
       1.99540e+02, 1.19600e+02, 1.60910e+02, 1.71200e+02, 1.38900e+02,
       7.03500e+01, 1.70000e+02, 1.29500e+02, 1.32260e+02, 1.31290e+02,
       1.32500e+02, 7.71000e+01, 3.94600e+01, 1.12700e+02, 5.11100e+01,
       4.17000e+01, 3.54000e+01, 7.79200e+01, 6.21000e+01, 4.70000e+01,
       7.48000e+01, 8.88200e+01, 5.63300e+01, 2.45700e+01, 8.37000e+01,
       5.39900e+01, 5.06000e+01, 5.04900e+01, 5.92000e+01, 5.63100e+01,
       4.33000e+01, 6.16000e+01, 4.88200e+01, 1.21000e+01, 5.94000e+01,
       6.33000e+01, 2.48600e+01, 3.63000e+01, 5.16500e+01, 4.87600e+01,
       4.63600e+01, 4.47100e+01, 1.10000e+00, 0.00000e+00, 5.32600e+01,
       1.67000e+01, 3.12000e+01, 4.33600e+01, 4.06000e+01, 1.99000e+01,
       3.07600e+01, 4.11300e+01, 3.62800e+01, 2.16000e+01, 2.00800e+01,
       1.98000e+01, 1.40800e+01, 8.94000e+00, 6.00000e+00, 5.97000e+00,
       6.24000e+00, 2.10900e+01, 1.90100e+01, 9.00000e+00, 6.87000e+00,
       2.19300e+01, 1.01000e+01, 1.69000e+00, 8.90000e-01, 1.79700e+01,
       1.33000e+01, 7.18000e+00, 9.20000e-01, 7.66000e+00, 7.00000e+00,
       6.40000e+00, 3.06000e+00, 5.18000e+00, 5.34000e+00, 2.67000e+00,
       1.00000e-01, 6.00000e-02, 1.17000e+00])

## 🌎 Find Unique World Gross Values

The `unique()` function is used to display all the unique values present in the **WorldGross** column.  
It helps to identify the different worldwide box office earnings of movies and understand the variation in global revenue performance.

In [121]:
df['WorldGross'].unique()

array([8.908700e+02, 7.989600e+02, 7.097100e+02, 9.634200e+02,
       9.398900e+02, 5.853500e+02, 4.428200e+02, 4.573600e+02,
       3.613400e+02, 4.560700e+02, 6.237200e+02, 5.270700e+02,
       2.536200e+02, 2.190800e+02, 2.314100e+02, 2.580200e+02,
       3.835300e+02, 2.890500e+02, 2.664600e+02, 3.404900e+02,
       2.875900e+02, 1.698700e+02, 1.860700e+02, 2.025500e+02,
       1.457100e+02, 3.113100e+02, 2.287400e+02, 1.734200e+02,
       1.693300e+02, 1.593100e+02, 1.753700e+02, 1.478800e+02,
       1.963900e+02, 1.177600e+02, 1.716300e+02, 3.722300e+02,
       1.190000e+02, 1.393500e+02, 7.551000e+01, 1.490400e+02,
       8.025000e+01, 5.586000e+01, 9.561000e+01, 1.568300e+02,
       7.002000e+01, 1.525200e+02, 1.459000e+02, 9.299000e+01,
       8.415000e+01, 8.666000e+01, 9.570000e+01, 6.931000e+01,
       9.260000e+01, 1.288800e+02, 7.618000e+01, 8.687000e+01,
       9.997000e+01, 7.550000e+01, 1.355600e+02, 6.979000e+01,
       1.277700e+02, 5.710000e+01, 5.919000e+01, 8.479000e+01,
       6.947000e+01, 5.493000e+01, 4.812000e+01, 4.774000e+01,
       3.067000e+01, 5.729000e+01, 6.277000e+01, 2.542000e+01,
       3.609000e+01, 2.937000e+01, 3.747000e+01, 3.530000e+01,
       2.218000e+01, 5.625000e+01, 2.058000e+01, 7.607000e+01,
       3.562000e+01, 7.328000e+01, 3.809000e+01, 4.017000e+01,
       6.322000e+01, 1.820000e+01, 2.682000e+01, 3.508000e+01,
       1.756000e+01, 7.511000e+01, 3.082000e+01, 1.004560e+03,
       5.855200e+02, 7.866400e+02, 6.243900e+02, 5.213100e+02,
       6.317400e+02, 6.039000e+02, 3.926200e+02, 5.860900e+02,
       2.971400e+02, 4.152500e+02, 2.699600e+02, 6.098400e+02,
       4.196700e+02, 3.779100e+02, 2.634300e+02, 3.414300e+02,
       2.306900e+02, 1.637300e+02, 1.880700e+02, 2.128700e+02,
       3.099800e+02, 2.427200e+02, 4.011300e+02, 2.419900e+02,
       1.780700e+02, 1.281100e+02, 1.999400e+02, 2.232400e+02,
       2.697800e+02, 1.492800e+02, 2.529100e+02, 1.016200e+02,
       2.002800e+02, 1.579300e+02, 2.193800e+02, 2.222300e+02,
       1.707600e+02, 3.339300e+02, 1.602600e+02, 1.603900e+02,
       2.330900e+02, 1.511600e+02, 1.628400e+02, 1.112300e+02,
       9.238000e+01, 1.634000e+02, 1.051700e+02, 1.637200e+02,
       6.416000e+01, 1.681700e+02, 1.508200e+02, 1.138600e+02,
       8.239000e+01, 1.279800e+02, 8.695000e+01, 7.044000e+01,
       1.000800e+02, 2.113400e+02, 1.059600e+02, 5.155000e+01,
       4.435000e+01, 9.395000e+01, 5.720000e+01, 1.132400e+02,
       4.365000e+01, 4.198000e+01, 8.437000e+01, 8.542000e+01,
       7.846000e+01, 4.465000e+01, 1.151000e+02, 8.465000e+01,
       4.349000e+01, 3.880000e+01, 3.995000e+01, 3.711000e+01,
       7.568000e+01, 1.130200e+02, 6.828000e+01, 4.388000e+01,
       3.347000e+01, 4.969000e+01, 4.086000e+01, 5.545000e+01,
       5.459000e+01, 1.089800e+02, 4.132000e+01, 3.351000e+01,
       5.696000e+01, 4.210000e+01, 4.130000e+01, 7.749000e+01,
       6.483000e+01, 6.482000e+01, 5.266000e+01, 5.001000e+01,
       4.585000e+01, 7.771000e+01, 6.557000e+01, 4.788000e+01,
       7.124000e+01, 2.951000e+01, 4.163000e+01, 2.766000e+01,
       9.641000e+01, 7.211000e+01, 6.837000e+01, 2.641000e+01,
       2.767000e+01, 3.075000e+01, 4.162000e+01, 5.091000e+01,
       3.903000e+01, 1.766000e+01, 2.273000e+01, 3.259000e+01,
       1.763000e+01, 3.115000e+01, 4.249000e+01, 3.482000e+01,
       4.331000e+01, 1.542000e+01, 2.707000e+01, 1.364000e+01,
       1.662000e+01, 1.315000e+01, 2.331000e+01, 1.672000e+01,
       1.233000e+01, 5.065000e+01, 1.177000e+01, 3.058000e+01,
       2.221000e+01, 1.121000e+01, 2.116000e+01, 9.810000e+00,
       1.184000e+01, 1.808000e+01, 4.042000e+01, 1.876000e+01,
       8.880000e+00, 1.010000e+01, 9.320000e+00, 1.793000e+01,
       3.339000e+01, 7.720000e+00, 2.146000e+01, 2.781500e+03,
       8.363000e+02, 9.340000e+02, 7.098200e+02, 7.313000e+02,
       4.674600e+02, 3.856500e+02, 3.092000e+02, 4.407000e+02,
       5.240200e+02, 3.815000e+02, 8.866800e+02, 3.731000e+02,
       4.130000e+02, 7.696900e+02, 3.147000e+02, 3.631000e+02,
       3.021000e+02, 1.832800e+02, 2.268000e+02, 3.253300e+02,
       4.859000e+02, 3.720000e+02, 2.430300e+02, 3.214100e+02,
       2.851000e+02, 2.107700e+02, 2.191000e+02, 1.718300e+02,
       1.933600e+02, 1.853000e+02, 2.670400e+02, 2.141000e+02,
       1.265700e+02, 1.788400e+02, 2.052800e+02, 2.002000e+02,
       1.835800e+02, 1.555500e+02, 1.023900e+02, 1.245800e+02,
       1.264800e+02, 1.182000e+02, 2.611900e+02, 9.140000e+01,
       7.382000e+01, 1.063800e+02, 1.861900e+02, 1.501600e+02,
       1.363000e+02, 1.013300e+02, 1.308000e+02, 1.151500e+02,
       7.752000e+01, 1.022200e+02, 7.158000e+01, 1.007300e+02,
       9.675000e+01, 6.877000e+01, 9.571000e+01, 9.135000e+01,
       1.083000e+02, 9.351000e+01, 6.235000e+01, 7.651000e+01,
       1.056400e+02, 9.080000e+01, 7.669000e+01, 7.814000e+01,
       1.224300e+02, 6.159000e+01, 1.222300e+02, 8.830000e+01,
       4.436000e+01, 7.594000e+01, 4.012000e+01, 3.941000e+01,
       4.176000e+01, 6.894000e+01, 6.072000e+01, 4.885000e+01,
       4.841000e+01, 3.831000e+01, 8.528000e+01, 3.120000e+01,
       4.270000e+01, 4.327000e+01, 6.819000e+01, 3.143000e+01,
       4.770000e+01, 6.010000e+01, 5.788000e+01, 2.696000e+01,
       3.608000e+01, 7.721000e+01, 4.646000e+01, 4.082000e+01,
       5.399000e+01, 3.989000e+01, 3.240000e+01, 6.244000e+01,
       1.860000e+01, 4.922000e+01, 3.155000e+01, 2.299000e+01,
       1.716000e+01, 1.600000e+01, 2.283000e+01, 3.338000e+01,
       1.582000e+01, 1.920000e+01, 3.923000e+01, 3.450000e+01,
       2.609000e+01, 1.728000e+01, 1.657000e+01, 2.721000e+01,
       1.083000e+01, 1.070000e+01, 1.700000e+01, 1.220000e+01,
       1.000000e+01, 1.489000e+01, 5.823000e+01, 1.640000e+01,
       1.234000e+01, 1.801000e+01, 3.634000e+01, 2.763000e+01,
       9.980000e+00, 6.380000e+00, 3.509000e+01, 1.210000e+01,
       6.073000e+01, 1.156700e+02, 1.025466e+03, 5.050700e+01,
       3.293970e+02, 3.643900e+01, 1.914800e+01, 8.951900e+01,
       2.819000e+01, 1.124900e+02, 4.818800e+01, 7.874000e+00,
       4.932140e+02, 9.710000e+00, 5.558800e+01, 2.052800e+01,
       9.920000e+00, 1.522630e+02, 5.141000e+01, 1.149700e+02,
       4.905000e+01, 5.431130e+02, 6.269400e+01, 7.570000e+01,
       8.685500e+01, 2.117800e+02, 7.495000e+01, 2.045900e+02,
       8.112000e+01, 1.514000e+01, 3.562600e+01, 5.504900e+01,
       5.282900e+01, 3.623600e+01, 9.125700e+01, 4.205000e+01,
       9.487800e+01, 6.150000e+00, 2.714300e+02, 2.373820e+02,
       9.593000e+02, 6.457100e+01, 4.948800e+02, 2.072200e+01,
       8.255360e+02, 6.239300e+02, 1.716850e+02, 1.091000e+01,
       2.156900e+01, 9.618800e+01, 9.816000e+01, 2.619270e+02,
       3.260800e+01, 1.400730e+02, 6.792000e+01, 7.917900e+01,
       5.337400e+01, 3.106490e+02, 1.028020e+02, 9.327000e+00,
       4.408900e+01, 8.375700e+01, 3.218840e+02, 6.003900e+01,
       2.097100e+01, 9.324000e+01, 9.450000e+00, 2.141300e+01,
       1.775110e+02, 2.265000e+02, 8.318800e+01, 4.309000e+00,
       1.272320e+02, 3.363650e+02, 1.990060e+02, 5.603400e+01,
       1.841000e+01, 2.962200e+02, 3.216690e+02, 2.935020e+02,
       1.361500e+02, 4.766000e+01, 2.883470e+02, 4.977800e+01,
       7.526040e+02, 2.948020e+02, 6.681700e+01, 5.178000e+00,
       1.592910e+02, 9.479000e+00, 6.905000e+01, 5.917940e+02,
       1.772360e+02, 6.787500e+01, 7.747700e+01, 1.571070e+02,
       1.363330e+02, 4.156850e+02, 5.480300e+01, 2.744690e+02,
       1.291540e+02, 6.022000e+01, 1.970000e+00, 3.591200e+02,
       3.470400e+01, 4.142040e+02, 3.197130e+02, 6.773300e+01,
       8.904000e+01, 2.938000e+01, 6.745000e+01, 1.704310e+02,
       4.677000e+00, 2.249190e+02, 2.152800e+02, 4.523900e+01,
       4.983100e+01, 2.783460e+02, 1.540250e+02, 6.984890e+02,
       1.397900e+02, 1.124600e+02, 1.063160e+03, 4.000620e+02,
       2.522730e+02, 1.678020e+02, 2.164850e+02, 8.054600e+01,
       1.347430e+02, 4.304000e+01, 6.067000e+01, 2.015840e+02,
       3.200300e+01, 3.426700e+01, 1.964900e+01, 4.055000e+01,
       3.919000e+01, 2.746000e+01, 3.539000e+01, 8.209000e+01,
       1.539000e+01, 1.770000e+00, 2.556000e+01, 4.574000e+01,
       1.474100e+02, 1.750000e+02, 2.162000e+02, 2.118200e+02,
       4.317000e+01, 1.431000e+01, 2.883800e+02, 3.705700e+02,
       5.598500e+02, 6.860000e+00, 6.097000e+01, 4.880000e+01,
       1.354600e+02, 1.748200e+02, 1.428500e+02, 7.242000e+01,
       9.541000e+01, 3.699000e+01, 3.850000e+01, 7.617000e+01,
       2.893000e+01, 4.630000e+00, 2.710000e+00, 5.524700e+01,
       6.261300e+02, 1.578900e+02, 6.354000e+01, 1.495400e+02,
       4.100000e+01, 1.939700e+02, 2.198500e+02, 8.316000e+01,
       6.378000e+01, 1.504100e+02, 1.341510e+03, 1.839500e+02,
       2.096400e+02, 1.857690e+02, 1.498800e+02, 2.269000e+02,
       1.739300e+02, 9.701000e+01, 8.461000e+01, 1.496800e+02,
       1.600800e+02, 2.149500e+02, 5.638000e+01, 6.656900e+02,
       7.201000e+01, 1.618500e+02, 1.100000e+00, 1.950000e+01,
       3.899000e+01, 1.511200e+02, 6.947100e+02, 1.102000e+02,
       3.967000e+01, 1.873600e+02, 3.506000e+01, 1.420400e+02,
       1.492300e+02, 5.939000e+01, 2.482000e+01, 2.070400e+02,
       9.798000e+01, 1.045710e+03, 7.831000e+01, 5.549900e+02,
       2.457200e+02, 2.992700e+02, 8.916000e+01, 4.846300e+02,
       4.817400e+02, 1.086100e+02, 9.714000e+01, 9.163000e+01,
       1.687400e+01, 4.014000e+01, 5.454500e+02, 6.018000e+01,
       4.709000e+01, 1.473300e+02, 8.556000e+01, 8.979000e+01,
       2.601000e+02, 6.930000e+00, 3.130000e+00, 1.278700e+02,
       3.739930e+02, 1.334320e+02, 6.370000e+00, 7.450000e+00,
       7.545000e+01, 4.880000e+00, 1.548000e+01, 4.564000e+01,
       1.772400e+02, 6.972000e+01, 2.712000e+01, 2.321610e+02,
       2.278200e+02, 5.867600e+02, 2.166400e+02, 7.599000e+01,
       1.149550e+02, 7.501000e+01, 5.107000e+01, 1.651800e+02,
       9.605000e+01, 4.049000e+01, 2.395000e+01, 3.494100e+01,
       5.637500e+02, 2.743000e+01, 1.322700e+02, 5.430000e+01,
       4.493200e+02, 8.063000e+01, 1.529200e+02, 1.123790e+03,
       7.121700e+02, 1.307900e+02, 1.775840e+02, 2.306000e+01,
       1.170900e+02, 1.200810e+02, 3.043000e+01, 3.315000e+01,
       3.536200e+02, 2.486000e+01, 1.698500e+02, 2.015900e+02,
                nan, 1.164700e+02, 2.349900e+02, 6.893000e+01,
       3.549000e+01, 2.323300e+02, 3.030300e+02, 1.280000e+01,
       2.472000e+01, 5.389800e+02, 3.716000e+01, 1.266400e+02,
       1.304800e+02, 9.626000e+01, 2.455300e+02, 7.711000e+01,
       4.253700e+02, 3.488400e+02, 3.563000e+01, 4.813000e+01,
       1.617700e+02, 8.149000e+01, 1.325600e+02, 3.337000e+01,
       1.142800e+02, 3.583800e+02, 3.946000e+01, 8.772400e+02,
       2.183400e+02, 2.841400e+02, 3.352600e+02, 3.273000e+01,
       3.793000e+01, 5.368000e+01, 4.418100e+02, 6.090200e+02,
       2.752900e+02, 1.765100e+02, 7.469200e+02, 1.672200e+02,
       4.622000e+01, 1.518590e+03, 6.240300e+02, 1.661700e+02,
       2.275000e+01, 1.428400e+02, 1.071400e+02, 1.197700e+02,
       1.130400e+02, 3.108000e+01, 4.033500e+02, 4.481000e+01,
       5.037000e+01, 2.401600e+02, 3.069400e+02, 5.942000e+01,
       4.035000e+01, 2.080800e+02, 3.456000e+01, 8.297000e+01,
       1.942000e+01, 2.364100e+02, 1.108560e+03, 3.965900e+02,
       2.464000e+01, 1.404700e+02, 3.761400e+02, 5.493700e+02,
       5.772000e+01, 7.522200e+02, 1.368400e+02, 2.761400e+02,
       6.649000e+01, 1.049100e+02, 1.084440e+03, 1.017600e+02,
       1.793800e+02, 3.054300e+02, 5.391000e+01, 7.728000e+01,
       4.186000e+01, 1.017000e+03, 6.912500e+02, 1.802700e+02,
       9.936000e+01, 2.826000e+01, 1.230500e+02, 8.545000e+01,
       5.482000e+01, 8.296900e+02, 1.961100e+02, 6.827000e+01,
       1.277300e+02, 8.806000e+01, 1.984700e+02, 1.601100e+02,
       8.438000e+01, 3.052700e+02, 4.712200e+02, 1.328200e+02,
       8.710000e+01, 8.560000e+00, 3.570000e+00, 2.469800e+02,
       2.438400e+02, 2.164900e+02, 1.333800e+02, 1.221300e+02,
       1.208000e+01, 1.131900e+02, 1.002000e+01, 1.320000e+00,
       1.215440e+03, 9.647600e+02, 8.559000e+02, 8.473300e+02,
       8.104000e+02, 7.886800e+02, 7.435600e+02, 6.885100e+02,
       6.680500e+02, 6.329100e+02, 5.872000e+02, 5.400100e+02,
       4.933100e+02, 4.673700e+02, 4.148300e+02, 4.110000e+02,
       3.757400e+02, 3.620000e+02, 3.517200e+02, 3.510400e+02,
       3.475500e+02, 3.180000e+02, 3.046500e+02, 2.861700e+02,
       2.861400e+02, 2.825700e+02, 2.699900e+02, 2.684300e+02,
       2.605000e+02, 2.577700e+02, 2.299300e+02, 2.257000e+02,
       2.197900e+02, 2.053700e+02, 1.998500e+02, 1.976900e+02,
       1.756100e+02, 1.739700e+02, 1.690400e+02, 1.677100e+02,
       1.655000e+02, 1.624000e+02, 1.615000e+02, 1.610300e+02,
       1.490000e+02, 1.464300e+02, 1.420800e+02, 1.319400e+02,
       1.281800e+02, 1.260400e+02, 1.217600e+02, 1.177400e+02,
       1.169800e+02, 1.122300e+02, 1.052000e+02, 9.834000e+01,
       9.754000e+01, 9.502000e+01, 9.480000e+01, 9.391000e+01,
       9.349000e+01, 9.126000e+01, 9.084000e+01, 9.057000e+01,
       9.025000e+01, 8.933000e+01, 8.618000e+01, 8.487000e+01,
       8.403000e+01, 7.838000e+01, 7.832000e+01, 7.163000e+01,
       7.135000e+01, 7.024000e+01, 6.857000e+01, 6.337000e+01,
       6.268000e+01, 6.005000e+01, 5.994000e+01, 5.956000e+01,
       5.952000e+01, 4.833000e+01, 4.823000e+01, 4.609000e+01,
       4.558000e+01, 4.293000e+01, 3.593000e+01, 3.546000e+01,
       3.172000e+01, 3.136000e+01, 3.133000e+01, 3.085000e+01,
       3.045000e+01, 3.037000e+01, 2.993000e+01, 2.924000e+01,
       2.726000e+01, 2.642000e+01, 2.442000e+01, 2.426000e+01,
       2.321000e+01, 2.320000e+01, 2.246000e+01, 2.182000e+01,
       2.042000e+01, 1.970000e+01, 1.915000e+01, 1.807000e+01,
       1.703000e+01, 1.655000e+01, 1.518000e+01, 1.501000e+01,
       1.379000e+01, 1.172000e+01, 1.133000e+01, 1.118000e+01,
       1.050000e+01, 9.490000e+00, 7.370000e+00, 7.040000e+00,
       6.850000e+00, 6.260000e+00, 5.750000e+00, 5.130000e+00,
       4.860000e+00, 4.070000e+00, 3.350000e+00, 3.310000e+00,
       2.960000e+00, 2.400000e+00, 2.340000e+00, 2.290000e+00,
       2.160000e+00, 1.380000e+00, 1.350000e+00, 1.677400e+02,
       1.900000e-01, 1.000000e-01, 1.400000e-01, 1.520000e+00])

## 💵 Find Unique Budget Values

The `unique()` function is used to display all the unique values present in the **Budget** column.  
It helps to identify the different production budgets of movies and understand the variation in investment amounts.

In [122]:
df['Budget'].unique()

array([2.580e+02, 1.600e+02, 1.500e+02, 3.000e+02, 1.100e+02, 1.300e+02,
       7.000e+01, 6.500e+01, 7.500e+01, 9.000e+01, 3.300e+01, 7.500e+00,
       1.400e+02, 1.000e+02, 8.500e+01, 2.000e+01, 6.100e+01, 1.750e+02,
       6.000e+01, 4.500e+01, 2.200e+01, 2.500e+01, 1.800e+02, 1.000e+01,
       1.400e+01, 1.500e+01, 3.500e+01, 3.000e+01, 4.800e+01, 5.000e+01,
       4.000e+01, 8.000e+01, 2.800e+01, 1.750e+01, 3.200e+01, 1.700e+01,
       2.100e+01, 1.800e+01, 5.300e+01, 9.000e+00, 1.900e+01, 2.000e+00,
       4.700e+01, 6.000e+00, 3.900e+01, 2.600e+01, 1.850e+02, 1.860e+02,
       2.000e+02, 3.700e+01, 2.300e+02, 5.750e+01, 6.600e+01, 1.375e+02,
       5.500e+01, 1.450e+02, 1.050e+02, 1.100e+01, 8.250e+01, 9.250e+01,
       7.250e+01, 1.080e+01, 7.800e+01, 2.700e+01, 1.200e+02, 4.750e+01,
       6.750e+01, 1.200e+01, 1.300e+01, 8.500e+00, 2.600e+00, 5.000e-01,
       6.200e+01, 7.000e+00, 2.400e+01, 5.800e+01, 1.600e+01, 8.000e+00,
       2.510e+01, 1.350e+01, 5.000e+00, 2.500e+00, 1.700e+00, 0.000e+00,
       3.750e+01, 4.000e+00, 1.250e+01, 3.800e+01, 3.500e+00, 2.370e+02,
       2.100e+02, 2.500e+02, 2.900e+01,       nan, 2.360e+01, 4.200e+01,
       2.750e+01, 5.900e+01, 1.850e+01, 9.800e+00, 1.290e+01, 3.000e+00,
       4.400e+01, 1.250e+02, 6.900e+01, 3.100e+01, 5.200e+01, 1.120e+02,
       3.600e+01, 1.650e+02, 1.170e+02, 9.500e+01, 2.600e+02, 1.550e+02,
       8.200e+01, 1.800e+00, 6.800e+01, 1.700e+02, 2.000e-01, 5.700e+01,
       3.200e+00, 3.250e+01, 1.630e+02, 1.350e+02, 6.300e+01, 1.500e+00,
       7.900e+01, 5.600e+01, 9.300e+01, 6.500e+00, 5.020e+01, 4.100e+01,
       1.950e+02, 4.990e+01, 2.090e+02, 1.000e+00, 1.020e+02, 2.300e+01,
       2.200e+02, 2.250e+02, 4.600e+01, 5.500e+00, 7.600e+01, 1.900e+02,
       2.150e+02, 1.030e+02, 9.200e+01, 1.150e+02, 4.300e+01, 8.400e+01,
       4.600e+00, 4.900e+00])

## 📈 Find Unique Profitability Values

The `unique()` function is used to display all the unique values present in the **Profitability** column.  
It helps to identify different profitability values of movies and understand the variation in return generated compared to the production budget.

In [123]:
df['Profitability'].unique()

array([3.453000e+02, 4.993500e+02, 4.731400e+02, 3.211400e+02,
       6.265900e+02, 3.902300e+02, 4.025700e+02, 3.518200e+02,
       5.161900e+02, 7.016400e+02, 4.158100e+02, 7.027600e+02,
       2.818000e+02, 6.638600e+02, 3.085480e+03, 1.843000e+02,
       3.486600e+02, 2.223400e+02, 2.664600e+02, 4.005700e+02,
       1.917300e+02, 8.493600e+02, 2.189100e+02, 2.700600e+02,
       2.388700e+02, 3.662500e+02, 2.079400e+02, 9.910000e+01,
       1.693300e+02, 2.655200e+02, 3.897200e+02, 6.721800e+02,
       1.309300e+02, 5.887900e+02, 6.865000e+02, 2.068000e+02,
       1.586700e+02, 1.393520e+03, 5.393600e+02, 1.753400e+02,
       4.012700e+02, 3.724100e+02, 2.731700e+02, 5.227800e+02,
       1.458600e+02, 3.050500e+02, 3.647400e+02, 3.719600e+02,
       4.207300e+02, 1.083200e+02, 1.568800e+02, 1.980200e+02,
       3.307100e+02, 3.222100e+02, 3.047200e+02, 4.343300e+02,
       5.712300e+02, 2.359500e+02, 1.936600e+02, 9.969000e+01,
       2.129400e+02, 3.359000e+02, 2.367600e+02, 1.304400e+02,
       2.779000e+02, 2.615500e+02, 2.406100e+02, 2.386900e+02,
       1.533300e+02, 3.182900e+02, 1.569300e+02, 4.796000e+01,
       4.009800e+02, 6.526000e+01, 2.497700e+02, 1.857900e+02,
       1.108900e+03, 3.750300e+02, 5.879000e+01, 1.086700e+02,
       3.561900e+02, 3.663800e+02, 8.103000e+01, 5.021000e+01,
       1.806100e+02, 3.032800e+02, 6.877000e+01, 2.004500e+02,
       1.756100e+02, 1.001400e+02, 1.185500e+02, 5.430000e+02,
       3.148000e+02, 4.252100e+02, 4.162600e+02, 2.896200e+02,
       3.158700e+02, 4.026000e+02, 1.061120e+03, 2.548200e+02,
       3.495700e+02, 7.221800e+02, 8.180500e+02, 9.240000e+02,
       2.098300e+02, 2.519390e+03, 1.915800e+02, 4.552400e+02,
       2.883600e+02, 2.046700e+02, 2.089700e+02, 2.660900e+02,
       2.066500e+02, 4.413000e+02, 2.766400e+02, 5.377600e+02,
       2.225800e+02, 1.970900e+02, 2.499200e+02, 3.189100e+02,
       2.569400e+02, 7.464100e+02, 2.299160e+03, 3.908600e+02,
       2.670300e+02, 4.512200e+02, 6.267900e+02, 2.693700e+02,
       6.830500e+02, 2.087100e+02, 5.341900e+02, 1.944100e+02,
       2.330900e+02, 3.779000e+02, 1.760400e+02, 1.534200e+02,
       3.299300e+02, 3.404200e+02, 3.505700e+02, 4.424800e+02,
       9.166000e+01, 3.057600e+02, 8.618000e+02, 1.054290e+03,
       9.154400e+02, 2.326900e+02, 1.580900e+02, 2.817700e+02,
       2.704700e+02, 2.709500e+02, 2.649100e+02, 3.682000e+01,
       1.642600e+02, 7.829000e+01, 3.177600e+02, 2.384100e+02,
       1.247100e+02, 2.098800e+02, 2.812500e+02, 2.440500e+02,
       1.307700e+02, 2.232700e+02, 1.705100e+02, 2.821500e+02,
       3.624300e+02, 2.984800e+02, 3.631500e+02, 3.710500e+02,
       1.681700e+02, 2.054900e+02, 8.033200e+02, 1.687850e+03,
       6.694400e+03, 1.242300e+02, 6.591000e+01, 7.921000e+02,
       2.729300e+02, 3.632600e+02, 3.443300e+02, 3.350500e+02,
       4.746900e+02, 1.754300e+02, 7.120000e+01, 2.213900e+02,
       1.752200e+02, 3.241100e+02, 1.504500e+02, 3.125400e+02,
       2.292400e+02, 1.942800e+02, 3.278600e+02, 5.984800e+02,
       1.096000e+02, 1.175500e+02, 1.982200e+02, 1.257400e+02,
       6.025500e+02, 1.602400e+02, 1.953400e+02, 1.200500e+02,
       1.383300e+02, 1.024900e+02, 2.081100e+02, 2.036200e+02,
       6.505200e+02, 1.765700e+02, 9.091000e+01, 1.086400e+02,
       8.817000e+01, 1.038200e+02, 9.442000e+01, 1.740800e+02,
       3.207800e+02, 3.083400e+02, 1.353700e+02, 5.455200e+02,
       1.385200e+02, 8.769000e+01, 1.371240e+03, 2.787000e+01,
                nan, 8.442000e+01, 3.922000e+01, 1.528800e+02,
       6.730000e+01, 4.482000e+01, 1.410300e+02, 2.615000e+01,
       1.691900e+02, 4.519500e+02, 3.233300e+02, 9.871000e+01,
       7.399000e+01, 2.885000e+01, 2.072000e+01, 4.718000e+01,
       2.226200e+02, 2.205700e+02, 2.145700e+02, 1.173630e+03,
       3.982400e+02, 3.736000e+02, 1.419640e+03, 4.178900e+02,
       1.335600e+03, 2.754600e+02, 1.066200e+03, 5.876000e+02,
       5.822400e+02, 2.180000e+02, 9.852000e+02, 2.487300e+02,
       2.753300e+02, 3.848400e+02, 7.867500e+02, 4.271800e+02,
       1.726300e+02, 7.049200e+02, 9.072000e+02, 1.626700e+02,
       3.239300e+02, 1.860000e+02, 2.430300e+02, 4.591600e+02,
       1.900700e+02, 7.025700e+02, 2.577600e+02, 2.863800e+02,
       1.425400e+02, 2.543200e+02, 2.141000e+02, 3.164300e+02,
       7.153600e+02, 5.402200e+02, 8.008100e+02, 3.671600e+02,
       4.444300e+02, 1.000800e+02, 4.338600e+02, 2.076300e+02,
       2.386400e+02, 3.377100e+02, 4.353200e+02, 2.285000e+02,
       3.691000e+02, 2.127600e+02, 4.654700e+02, 1.501600e+02,
       4.810500e+02, 6.815000e+02, 2.598200e+02, 3.114300e+02,
       3.838300e+02, 2.584000e+02, 2.044400e+02, 9.544000e+01,
       7.194900e+02, 2.764300e+02, 3.480500e+02, 2.610000e+02,
       1.550000e+02, 1.438600e+02, 1.039200e+02, 4.781900e+02,
       1.509100e+02, 3.026700e+02, 2.556400e+02, 1.302300e+02,
       1.530400e+02, 1.231800e+02, 2.037200e+02, 1.470000e+02,
       2.218000e+02, 1.287100e+02, 2.674700e+02, 2.627300e+02,
       1.898200e+02, 2.757600e+02, 8.096000e+02, 1.285500e+02,
       1.613700e+02, 6.385000e+01, 1.470300e+02, 1.560000e+02,
       1.664200e+02, 6.199100e+02, 1.257200e+02, 4.770000e+02,
       1.202000e+02, 1.286200e+02, 1.497800e+02, 2.004400e+02,
       4.289500e+02, 1.161500e+02, 3.265600e+02, 6.749000e+01,
       6.136000e+01, 1.751400e+02, 1.040700e+02, 9.300000e+01,
       3.281300e+02, 1.971900e+02, 4.180000e+01, 1.751000e+02,
       8.000000e+01, 1.630700e+02, 1.112700e+02, 8.789000e+01,
       4.800000e+01, 9.808000e+01, 2.674400e+02, 1.066700e+02,
       3.478700e+02, 8.638000e+01, 3.314000e+02, 2.176800e+02,
       1.443300e+02, 2.140000e+02, 4.250000e+01, 3.486000e+01,
       3.333300e+02, 7.090000e+01, 1.941000e+02, 4.489900e+02,
       7.810000e+01, 2.468000e+01, 1.060000e+02, 7.268000e+01,
       1.105100e+02, 3.440000e+01, 4.253000e+01, 2.339400e+02,
       6.100000e+01, 3.373900e+02, 3.304900e+02, 5.127300e+02,
       2.525400e+02, 2.533820e+03, 2.143500e+02, 9.574000e+02,
       1.627600e+02, 1.084200e+02, 1.323400e+02, 1.095200e+02,
       1.312300e+02, 3.945700e+02, 7.768000e+01, 1.852900e+02,
       1.368500e+02, 1.417100e+02, 2.768400e+02, 2.570500e+02,
       4.598800e+02, 2.335700e+02, 7.871200e+02, 6.269400e+02,
       5.046700e+02, 1.258800e+02, 4.235600e+02, 9.368800e+02,
       3.409800e+02, 1.014000e+02, 4.884000e+01, 1.484400e+02,
       2.621400e+02, 1.015900e+02, 1.035300e+02, 2.281400e+02,
       1.314100e+02, 9.488000e+01, 3.392900e+02, 2.119500e+02,
       7.674400e+02, 1.793600e+02, 2.999300e+02, 1.381500e+02,
       5.159600e+02, 3.119700e+02, 8.584300e+02, 2.321000e+01,
       1.797400e+02, 3.206300e+02, 1.308800e+02, 2.238700e+02,
       1.716200e+02, 1.750900e+02, 2.612300e+02, 2.639300e+02,
       1.021000e+02, 3.106500e+02, 3.426700e+02, 9.327000e+01,
       2.204500e+02, 1.675100e+02, 2.476000e+02, 1.501000e+02,
       8.388000e+01, 2.664000e+02, 6.300000e+01, 5.917030e+03,
       2.384200e+02, 3.466200e+02, 1.436300e+02, 3.180800e+02,
       1.681800e+02, 3.431100e+02, 3.502100e+02, 5.753000e+01,
       4.937000e+02, 1.608300e+02, 2.668200e+02, 6.807500e+02,
       7.943000e+01, 2.883500e+02, 2.488900e+02, 4.561200e+02,
       3.685000e+02, 6.681700e+02, 3.452000e+01, 5.309700e+02,
       4.309000e+01, 2.157800e+02, 2.276100e+02, 1.772400e+02,
       3.393800e+02, 2.213600e+02, 1.963800e+02, 3.408300e+02,
       2.681800e+02, 2.740200e+02, 3.347200e+02, 5.166200e+02,
       1.338200e+02, 1.970000e+01, 8.978000e+02, 8.676000e+02,
       2.761360e+03, 2.131400e+02, 3.762940e+03, 4.452000e+02,
       1.175200e+02, 2.248300e+02, 1.704300e+02, 4.677000e+01,
       4.498400e+02, 1.435200e+02, 2.622700e+02, 2.783500e+02,
       4.162800e+02, 1.027190e+03, 9.319000e+01, 2.342900e+02,
       5.315800e+02, 2.353300e+02, 6.638800e+02, 1.766300e+02,
       4.163200e+02, 4.027300e+02, 1.924900e+02, 3.033500e+02,
       2.519800e+02, 1.600200e+02, 1.557600e+02, 1.091600e+02,
       1.448100e+02, 4.898400e+02, 1.373100e+02, 1.862500e+02,
       2.345300e+02, 5.131000e+01, 8.855000e+02, 5.112400e+02,
       1.143400e+02, 9.827000e+01, 3.066000e+02, 1.080980e+03,
       3.026000e+02, 2.539100e+02, 4.471900e+02, 8.873300e+02,
       2.646900e+02, 2.799300e+02, 6.861000e+01, 1.524100e+02,
       5.422000e+01, 2.257600e+02, 1.072500e+02, 2.857000e+02,
       3.448400e+02, 2.578600e+02, 1.479700e+02, 7.700000e+01,
       5.078300e+02, 6.429000e+01, 2.317000e+01, 1.381200e+02,
       5.009000e+02, 3.947200e+02, 2.647600e+02, 4.272600e+02,
       1.366700e+02, 5.388000e+02, 1.099300e+02, 2.310000e+02,
       2.126000e+02, 1.114100e+02, 1.073210e+03, 2.919900e+02,
       5.989700e+02, 1.238500e+02, 2.498000e+02, 3.025400e+02,
       4.348300e+02, 6.467270e+03, 2.417300e+02, 1.894700e+02,
       3.557300e+02, 2.686800e+02, 8.055000e+01, 4.437900e+02,
       2.400300e+02, 5.994400e+02, 3.680000e+00, 5.572600e+02,
       2.599000e+01, 8.889400e+02, 4.791100e+02, 2.204000e+02,
       1.983300e+02, 3.406600e+02, 2.536400e+02, 5.969100e+02,
       3.959200e+02, 4.963200e+02, 4.140780e+03, 2.449600e+02,
       4.182800e+02, 1.305100e+02, 4.269100e+02, 1.820200e+02,
       2.720600e+02, 2.122900e+02, 2.760000e+01, 5.384800e+02,
       5.180000e+02, 3.620300e+02, 2.428400e+02, 2.290700e+02,
       2.596000e+02, 1.605400e+02, 4.363600e+02, 1.719500e+02,
       2.616000e+02, 4.604100e+02, 3.169000e+02, 1.095000e+02,
       5.201900e+02, 2.771000e+01, 6.252000e+01, 2.547200e+02,
       2.876900e+02, 8.339500e+02, 3.033000e+01, 1.817000e+01,
       1.450900e+02, 3.255000e+01, 6.191000e+01, 2.281800e+02,
       8.862200e+02, 9.960000e+01, 1.084800e+02, 2.579600e+02,
       1.898500e+02, 7.334600e+02, 8.665600e+02, 6.079400e+02,
       8.842700e+02, 1.875200e+02, 1.276800e+02, 3.670800e+02,
       2.595900e+02, 2.530800e+02, 5.321000e+01, 1.397600e+02,
       5.125000e+02, 7.218000e+01, 1.763700e+02, 1.697000e+02,
       2.995500e+02, 3.839500e+02, 2.039000e+02, 5.763000e+02,
       6.474300e+02, 4.359500e+02, 2.690700e+02, 9.223000e+01,
       3.081400e+02, 2.401600e+02, 1.521300e+02, 2.210100e+02,
       4.981000e+01, 2.123100e+02, 4.799700e+02, 1.688000e+02,
       4.699800e+02, 2.223500e+02, 2.957100e+02, 5.220800e+02,
       1.449900e+02, 7.108700e+02, 6.180000e+01, 2.913400e+02,
       3.715760e+03, 1.055300e+03, 1.279200e+02, 3.850500e+02,
       1.636800e+02, 3.505100e+02, 4.253700e+02, 4.983400e+02,
       7.125000e+01, 6.875200e+02, 5.218500e+02, 2.089500e+02,
       2.325700e+02, 1.451000e+02, 3.809400e+02, 4.216200e+02,
       3.946200e+02, 9.234200e+02, 3.639000e+02, 1.136600e+02,
       4.243800e+02, 2.727200e+02, 2.528700e+02, 2.064500e+02,
       7.242800e+02, 5.075100e+02, 4.235300e+02, 5.883600e+02,
       5.151200e+02, 2.388880e+03, 1.100500e+02, 6.902700e+02,
       2.773500e+02, 1.955000e+02, 1.421900e+02, 2.856780e+03,
       1.785700e+02, 4.790900e+02, 6.649500e+02, 8.881000e+01,
       3.102700e+02, 6.893000e+01, 8.684000e+01, 3.694800e+02,
       2.116800e+02, 7.922000e+01, 1.344900e+02, 2.448000e+02,
       2.383800e+02, 1.843700e+02, 1.294800e+02, 1.125770e+03,
       2.590410e+03, 5.542800e+02, 2.332900e+02, 1.759800e+02,
       4.256700e+02, 8.358700e+02, 1.098740e+03, 8.246000e+01,
       3.270500e+02, 1.368360e+03, 2.209200e+02, 2.216200e+02,
       4.337800e+02, 1.017585e+04, 2.759700e+02, 3.054300e+02,
       1.797000e+02, 3.091100e+02, 1.046500e+02, 5.085000e+02,
       6.009100e+02, 3.974300e+02, 8.831000e+01, 2.568000e+02,
       2.237300e+02, 6.103300e+02, 1.827300e+02, 6.914000e+02,
       6.537200e+02, 1.003900e+02, 7.513600e+02, 2.516000e+02,
       1.587700e+02, 2.287300e+02, 2.109600e+02, 2.035100e+02,
       2.855900e+02, 3.320500e+02, 3.055000e+01, 1.320500e+02,
       2.377500e+02, 3.087300e+02, 1.875700e+02, 3.936100e+02,
       2.667500e+02, 2.654900e+02, 1.006500e+02, 1.414900e+02,
       1.821300e+02, 5.008500e+02, 6.077200e+02, 1.269420e+03,
       6.583800e+02, 3.765900e+02, 5.402700e+02, 4.929200e+02,
       3.717800e+02, 6.885100e+02, 2.969100e+02, 3.723000e+02,
       4.349700e+02, 2.842100e+02, 2.294500e+02, 2.459800e+02,
       3.456900e+02, 2.163200e+02, 2.890300e+02, 3.514600e+02,
       4.689700e+02, 3.343200e+02, 3.310000e+02, 1.590000e+03,
       3.311500e+02, 2.384700e+02, 2.488200e+02, 2.093100e+02,
       7.297100e+02, 2.684300e+02, 1.211600e+02, 3.304800e+02,
       5.347200e+02, 4.514100e+02, 4.395800e+02, 1.369100e+02,
       2.220500e+02, 1.013800e+02, 4.970400e+02, 1.878300e+02,
       5.590300e+02, 3.310100e+02, 4.060000e+02, 3.230060e+03,
       2.300400e+02, 9.933500e+02, 9.761900e+02, 1.691400e+02,
       2.163000e+02, 6.409000e+02, 3.938800e+02, 6.957000e+01,
       4.205100e+02, 3.342300e+02, 1.020300e+02, 1.753300e+02,
       2.587800e+02, 5.737800e+02, 2.375500e+02, 5.266800e+02,
       2.347900e+02, 1.611900e+02, 2.607400e+02, 1.651600e+02,
       1.509400e+02, 2.374900e+02, 2.977620e+03, 3.314400e+02,
       7.072300e+02, 2.801000e+02, 3.918900e+02, 6.025000e+01,
       4.213200e+02, 2.809500e+02, 5.274800e+02, 2.112400e+02,
       2.089200e+02, 1.000900e+02, 2.397670e+03, 2.127000e+02,
       5.410900e+02, 1.074000e+02, 1.205700e+02, 2.304500e+02,
       3.506300e+02, 2.862000e+02, 2.994300e+02, 2.365700e+02,
       1.418200e+02, 6.344900e+02, 1.205000e+02, 6.169000e+02,
       1.320200e+02, 4.987700e+02, 7.309000e+01, 7.789000e+01,
       7.549100e+02, 3.052300e+02, 1.213100e+02, 2.109700e+02,
       5.043200e+02, 2.641900e+02, 6.234000e+01, 2.269300e+02,
       5.629000e+01, 2.393200e+02, 1.702600e+03, 8.275000e+01,
       3.035900e+02, 3.939000e+01, 9.767000e+01, 5.150000e+01,
       3.725500e+02, 5.834000e+01, 4.260000e+01, 1.340100e+02,
       2.741800e+02, 7.368000e+01, 2.566500e+02, 1.620000e+01,
       5.814000e+01, 1.838900e+02, 3.695000e+01, 3.906000e+01,
       4.406000e+01, 1.969000e+01, 2.300000e+00, 5.391000e+02,
       5.591400e+02, 7.721000e+01, 1.420000e+01, 1.525000e+01])

## 💹 Find Unique Open Profit Values

The `unique()` function is used to display all the unique values present in the **OpenProfit** column.  
It helps to identify the different opening profit values of movies and understand the variation in initial box office returns.

In [124]:
df['OpenProfit'].unique()

array([5.85700e+01, 7.60000e+01, 4.70000e+01, 3.82300e+01, 5.14000e+01,
       5.14700e+01, 6.30000e+01, 3.44600e+01, 6.32900e+01, 1.09080e+02,
       3.13300e+01, 9.86700e+01, 4.41100e+01, 9.30300e+01, 1.41330e+02,
       3.50700e+01, 3.03600e+01, 4.46200e+01, 4.36000e+01, 4.04700e+01,
       2.53300e+01, 1.65000e+02, 4.02400e+01, 3.66700e+01, 5.41000e+01,
       4.24700e+01, 4.11800e+01, 1.78300e+01, 2.51000e+01, 5.70000e+01,
       4.31100e+01, 1.04090e+02, 1.83300e+01, 1.11000e+02, 3.12000e+01,
       1.42800e+01, 1.28000e+01, 3.17000e+02, 1.56430e+02, 2.07100e+01,
       1.32000e+02, 1.42670e+02, 6.94300e+01, 2.16700e+01, 2.91700e+01,
       1.86000e+01, 3.40000e+01, 4.16000e+01, 8.80000e+01, 2.13800e+01,
       2.37700e+01, 2.97100e+01, 4.17900e+01, 2.50000e+01, 1.96000e+01,
       9.30000e+01, 7.54300e+01, 4.87500e+01, 1.30900e+01, 1.92900e+01,
       2.33300e+01, 8.58800e+01, 5.48000e+01, 2.06200e+01, 3.85200e+01,
       5.14300e+01, 5.00000e+01, 3.75000e+01, 3.45000e+01, 4.94400e+01,
       2.18900e+01, 4.00000e+01, 8.44000e+00, 6.46700e+01, 1.00000e+02,
       1.40000e+01, 1.17100e+01, 1.01400e+01, 8.20000e+01, 8.00000e+00,
       1.40400e+01, 7.00000e+00, 1.91400e+01, 5.66700e+01, 1.46200e+01,
       1.02900e+01, 6.67000e+00, 1.92300e+01, 8.56200e+01, 5.30200e+01,
       5.41100e+01, 4.17300e+01, 3.50500e+01, 3.01200e+01, 4.20700e+01,
       1.88220e+02, 2.93500e+01, 5.29400e+01, 9.92000e+01, 8.93300e+01,
       4.20500e+01, 2.75200e+01, 2.86700e+01, 4.01000e+01, 6.79100e+01,
       4.83800e+01, 3.88400e+01, 2.86800e+01, 3.43800e+01, 1.74700e+01,
       6.61100e+01, 2.79300e+01, 4.66700e+01, 3.65000e+01, 4.76000e+01,
       4.81600e+01, 2.60900e+01, 3.41900e+01, 1.46500e+02, 3.82090e+02,
       8.92300e+01, 2.80400e+01, 6.88600e+01, 5.76300e+01, 3.32100e+01,
       1.60400e+02, 1.67800e+01, 7.67000e+01, 4.18200e+01, 3.05000e+01,
       5.71800e+01, 2.05400e+01, 2.97900e+01, 6.84600e+01, 6.35800e+01,
       5.91000e+01, 5.17000e+01, 2.48700e+01, 2.70900e+01, 1.08060e+02,
       2.78700e+02, 2.33220e+02, 3.89100e+01, 1.83600e+01, 5.81200e+01,
       3.56800e+01, 1.89700e+01, 3.69000e+01, 9.71000e+00, 3.95600e+01,
       1.55000e+01, 1.15610e+02, 3.83200e+01, 4.63100e+01, 1.00400e+02,
       4.47300e+01, 5.02900e+01, 2.71700e+01, 7.50000e+01, 1.91100e+01,
       6.17000e+01, 1.24250e+02, 1.36150e+02, 9.57300e+01, 1.73800e+02,
       1.70900e+01, 1.71760e+02, 5.80000e+02, 1.36800e+03, 2.57500e+01,
       2.24400e+01, 1.39430e+02, 7.50000e+00, 4.02000e+01, 1.18330e+02,
       1.13100e+02, 1.03330e+02, 4.19600e+01, 2.19000e+01, 3.20000e+01,
       1.94100e+01, 2.97000e+01, 3.25700e+01, 6.32500e+01, 6.25000e+01,
       2.05000e+01, 1.31250e+02, 1.46300e+01, 4.18300e+01, 4.09500e+01,
       3.59100e+01, 2.35000e+01, 2.11100e+01, 2.88600e+01, 3.51800e+01,
       2.60000e+01, 4.13500e+01, 2.12000e+01, 1.08330e+02, 3.30000e+01,
       3.11500e+01, 2.08700e+01, 1.73300e+01, 2.90000e+01, 2.44400e+01,
       1.08000e+02, 2.50500e+01, 1.36400e+02, 2.42000e+00, 2.83300e+01,
       1.64710e+02, 4.15000e+00,         nan, 8.75000e+00, 1.33300e+01,
       2.02500e+01, 1.48500e+01, 1.82400e+01, 1.21600e+01, 5.84300e+01,
       2.25000e+00, 8.24000e+00, 1.90000e+01, 1.22900e+01, 7.78000e+00,
       3.07000e+00, 8.48600e+01, 4.03000e+01, 3.24900e+01, 5.19000e+01,
       3.11200e+01, 2.85600e+02, 1.28570e+02, 5.37100e+01, 1.17590e+02,
       6.50700e+01, 6.92200e+01, 3.38900e+01, 4.63300e+01, 5.67300e+01,
       3.61300e+01, 3.26500e+01, 8.40000e+01, 8.34100e+01, 3.12600e+01,
       1.22310e+02, 9.88000e+01, 1.50500e+01, 3.08000e+01, 2.13000e+01,
       3.03000e+01, 5.42900e+01, 2.11300e+01, 1.24670e+02, 5.71700e+01,
       4.24600e+01, 2.30500e+01, 2.52000e+01, 1.11200e+02, 7.26300e+01,
       4.48000e+01, 4.92000e+01, 9.22900e+01, 3.27000e+01, 1.04660e+02,
       2.80000e+01, 3.96200e+01, 4.85700e+01, 3.88300e+01, 4.45000e+01,
       1.43000e+02, 4.88000e+01, 6.85000e+01, 2.33700e+01, 2.13680e+02,
       1.18500e+02, 4.76900e+01, 7.28600e+01, 7.03300e+01, 7.66700e+01,
       3.02700e+01, 1.51430e+02, 4.82900e+01, 1.88000e+01, 4.50900e+01,
       5.94300e+01, 2.14300e+01, 2.61500e+01, 3.26700e+01, 1.23750e+02,
       1.75700e+01, 5.26700e+01, 4.26700e+01, 1.86300e+01, 2.66000e+01,
       1.43300e+01, 1.02500e+02, 1.96600e+01, 7.46700e+01, 1.08670e+02,
       4.77300e+01, 5.08000e+01, 5.06700e+01, 2.65800e+01, 3.56700e+01,
       1.61700e+01, 1.13800e+01, 5.80000e+01, 3.65400e+01, 1.28180e+02,
       4.24000e+01, 1.22000e+02, 1.77800e+01, 6.11100e+01, 4.47200e+01,
       5.55600e+01, 1.75000e+01, 7.32000e+01, 6.81000e+00, 1.03100e+01,
       3.78400e+01, 1.26700e+01, 2.75000e+01, 9.30000e-01, 4.31300e+01,
       1.00000e+01, 5.81600e+01, 3.25000e+01, 4.21400e+01, 2.72200e+01,
       9.75000e+00, 1.57500e+01, 5.42600e+01, 1.01300e+01, 2.65000e+01,
       1.80000e+01, 4.08000e+01, 5.73300e+01, 1.06000e+02, 1.10000e+01,
       1.36670e+02, 6.20000e-01, 1.60000e+01, 3.57000e+00, 1.85700e+01,
       9.40000e+00, 1.88200e+01, 5.80000e+00, 6.00000e+00, 1.20700e+01,
       1.73000e+00, 1.18300e+01, 9.40000e+01, 5.80500e+01, 4.55000e+01,
       6.44600e+01, 7.88200e+01, 5.15000e+00, 2.17300e+01, 2.07700e+01,
       1.44700e+01, 2.81800e+01, 5.30000e-01, 4.89600e+01, 1.29600e+01,
       6.07000e+01, 4.88700e+01, 2.57000e+00, 4.58200e+01, 7.55000e+01,
       1.21600e+02, 7.71400e+01, 8.17400e+01, 1.23000e+02, 1.47330e+02,
       3.40600e+01, 6.53800e+01, 2.21250e+02, 3.85000e+01, 2.15000e+01,
       1.93500e+01, 3.55000e+01, 9.28600e+01, 1.57700e+01, 1.88600e+01,
       4.40000e+01, 2.15600e+01, 1.43000e+01, 5.06300e+01, 5.63000e+00,
       3.88900e+01, 2.64800e+01, 7.30000e-01, 3.92500e+01, 6.40500e+01,
       2.52000e+02, 1.14900e+01, 6.91700e+01, 6.60000e+01, 2.10700e+01,
       1.72600e+01, 4.84200e+01, 2.01300e+01, 6.73100e+01, 4.50000e+01,
       2.77400e+01, 3.08300e+01, 3.24700e+01, 5.50000e+01, 2.32000e+01,
       3.54000e+01, 2.30000e+01, 2.73600e+01, 2.40000e+01, 1.35567e+03,
       3.28400e+01, 4.20800e+01, 3.33000e+00, 6.20000e+01, 1.50000e+01,
       3.75900e+01, 1.90600e+01, 3.27300e+01, 1.12650e+02, 1.76700e+01,
       3.10000e+01, 4.90000e+01, 4.29100e+01, 5.12500e+01, 1.16900e+02,
       6.00000e-01, 3.40000e-01, 6.40600e+01, 1.87600e+01, 2.57000e+01,
       6.55000e+01, 3.48600e+01, 4.08800e+01, 5.17500e+01, 1.54800e+01,
       8.03500e+01, 4.24400e+01, 4.80000e+01, 4.44000e+00, 5.10000e+00,
       1.39250e+02, 8.75000e+01, 2.93300e+01, 2.68700e+01, 1.13333e+03,
       8.00000e+01, 3.76000e+01, 2.18000e+01, 1.17300e+01, 4.42100e+01,
       6.43200e+01, 9.52900e+01, 2.10000e+01, 5.51500e+01, 2.59000e+01,
       6.31600e+01, 2.38800e+01, 1.08080e+02, 6.10000e+01, 2.71400e+01,
       4.20000e+01, 3.83300e+01, 4.76100e+01, 8.50000e-01, 6.81600e+01,
       3.12300e+01, 3.40000e+00, 1.74000e+02, 3.05500e+01, 8.05000e+00,
       3.86000e+01, 1.58000e+02, 5.08100e+01, 5.79400e+01, 4.38000e+00,
       8.07700e+01, 4.64700e+01, 3.30700e+01, 3.00000e+00, 2.60300e+01,
       1.11300e+01, 3.73300e+01, 2.23500e+01, 3.82000e+01, 5.17600e+01,
       3.41200e+01, 1.62600e+01, 7.56000e+01, 1.15300e+01, 3.75000e+00,
       1.58000e+01, 6.89500e+01, 4.50800e+01, 6.48300e+01, 5.32000e+01,
       7.04400e+01, 2.65900e+01, 3.76100e+01, 4.12300e+01, 1.57300e+01,
       1.35350e+02, 5.95900e+01, 8.08600e+01, 7.57000e+00, 3.24200e+01,
       4.29500e+01, 3.01300e+01, 8.84670e+02, 3.20600e+01, 3.16500e+01,
       8.51000e+00, 3.81400e+01, 1.33600e+01, 3.17700e+01, 4.36700e+01,
       7.00400e+01, 1.70000e-01, 4.61000e+00, 3.42900e+01, 2.03800e+01,
       3.90000e+01, 3.72500e+01, 3.35500e+01, 2.32300e+01, 7.88000e+01,
       3.38700e+01, 1.40200e+02, 1.05140e+03, 3.26000e+01, 3.60600e+01,
       2.49200e+01, 2.62200e+01, 2.82100e+01, 2.48400e+01, 3.33600e+01,
       4.35900e+01, 5.89400e+01, 4.67300e+01, 5.23000e+00, 3.36000e+01,
       3.17000e+01, 3.98600e+01, 5.88900e+01, 4.62800e+01, 2.32400e+01,
       7.09000e+01, 1.38400e+01, 1.00000e+00, 4.21500e+01, 7.48000e+00,
       1.48100e+01, 5.20000e-01, 7.93000e+00, 2.60200e+01, 4.27000e+00,
       4.95500e+01, 2.54300e+01, 3.47200e+01, 1.41800e+01, 2.79200e+01,
       1.07440e+02, 1.04160e+02, 8.37600e+01, 4.16200e+01, 3.30300e+01,
       2.85000e+01, 6.49800e+01, 9.37500e+01, 1.14200e+01, 3.94000e+01,
       3.23700e+01, 2.23400e+01, 1.15600e+01, 1.16000e+00, 4.38100e+01,
       2.60500e+01, 3.20400e+01, 5.01800e+01, 1.25560e+02, 7.28700e+01,
       2.20000e+01, 2.09600e+01, 4.43200e+01, 1.87200e+01, 2.71000e+01,
       2.62000e+01, 3.44400e+01, 2.50900e+01, 8.64300e+01, 2.36400e+01,
       4.30200e+01, 1.03000e+00, 1.66700e+01, 4.32400e+01, 1.22200e+01,
       8.50000e+00, 1.94000e+01, 3.58500e+01, 7.96000e+02, 1.83330e+02,
       9.42000e+00, 9.74000e+01, 1.97900e+01, 6.64500e+01, 1.00310e+02,
       1.25600e+01, 1.87860e+02, 8.03200e+01, 2.92600e+01, 3.88100e+01,
       3.66500e+01, 4.88300e+01, 5.00200e+01, 1.22900e+02, 4.90800e+01,
       2.53500e+01, 3.46100e+01, 5.95000e+01, 4.54000e+01, 3.84600e+01,
       1.87100e+01, 1.45000e+00, 6.93300e+01, 5.59000e+02, 1.90500e+01,
       9.42900e+01, 2.42600e+01, 2.13300e+01, 3.25000e+00, 2.34800e+01,
       5.82000e+01, 3.02900e+01, 1.72300e+01, 3.92700e+01, 2.19700e+01,
       3.23800e+01, 1.63900e+01, 1.92500e+01, 2.63000e+01, 4.72600e+01,
       1.53000e+00, 3.56000e+01, 2.78000e+01, 2.10000e+00, 6.00330e+02,
       4.41800e+01, 8.31400e+01, 3.55500e+01, 1.10020e+02, 1.08840e+02,
       1.92100e+01, 2.69600e+01, 7.40000e+00, 3.05100e+01, 4.91300e+01,
       6.43600e+01, 3.37300e+03, 2.68300e+01, 2.85900e+01, 3.53700e+01,
       7.86800e+01, 1.32300e+01, 4.23100e+01, 1.95560e+02, 4.70000e-01,
       9.00800e+01, 2.31000e+00, 1.77000e+00, 1.26640e+02, 5.67000e+01,
       1.17560e+02, 1.37330e+02, 1.87500e+01, 1.22760e+02, 3.30900e+01,
       2.04600e+01, 3.61600e+01, 2.63800e+01, 2.23100e+01, 2.97200e+01,
       1.05000e+00, 5.96000e+00, 2.00300e+01, 1.05330e+02, 5.18900e+01,
       2.11700e+01, 4.67600e+01, 1.97800e+01, 4.52600e+01, 1.33000e+00,
       8.86000e+00, 8.70700e+01, 1.09890e+02, 1.21590e+02, 1.60000e-01,
       6.08600e+01, 4.12200e+01, 5.57900e+01, 5.18300e+01, 5.04400e+01,
       3.23300e+01, 3.49500e+01, 3.68000e+01, 3.69300e+01, 4.42600e+01,
       1.96300e+01, 4.04600e+01, 3.91300e+01, 4.77000e+01, 1.67100e+01,
       2.09300e+02, 2.69900e+01, 3.08800e+01, 2.59200e+01, 1.57900e+01,
       7.14100e+01, 3.35300e+01, 1.35900e+01, 4.36200e+01, 9.09800e+01,
       3.93800e+01, 4.44600e+01, 1.65700e+01, 1.39500e+01, 9.87100e+01,
       1.41900e+01, 8.21300e+01, 5.24600e+01, 1.85000e+00, 8.05400e+02,
       4.33900e+01, 2.13730e+02, 1.89330e+02, 2.14900e+01, 4.43600e+01,
       4.60000e+00, 6.47500e+01, 5.66000e+00, 5.83200e+01, 5.81400e+01,
       2.45600e+01, 2.84500e+01, 5.00800e+01, 1.51650e+02, 6.87300e+01,
       3.39000e+00, 2.30000e-01, 2.98800e+01, 1.17000e+00, 2.87500e+01,
       1.55700e+01, 5.00000e-01, 1.13533e+03, 7.78500e+01, 1.08000e+00,
       5.36700e+01, 7.08000e+01, 9.76000e+00, 1.77120e+02, 7.64300e+01,
       3.13600e+01, 1.31690e+02, 1.26300e+01, 7.24000e+02, 4.50000e-01,
       1.39600e+01, 4.40500e+01, 8.78000e+01, 5.59200e+01, 1.87000e+00,
       7.20000e-01, 5.20000e+00, 3.14500e+01, 3.05400e+01, 1.44670e+02,
       1.13000e+00, 8.01700e+01, 1.75500e+01, 2.34000e+02, 2.88000e+00,
       6.50000e-01, 3.73000e+00, 1.19600e+01, 1.06240e+02, 2.16900e+01,
       4.40000e-01, 2.36300e+01, 2.63000e+00, 4.73100e+01, 1.54600e+02,
       1.00900e+01, 2.37300e+01, 8.33000e+00, 2.09700e+01, 1.82000e+00,
       1.06000e+00, 1.29500e+01, 6.50000e+00, 2.97000e+00, 2.00000e+00,
       8.27800e+01, 1.23000e+00, 8.20000e-01, 9.00000e-01, 1.15000e+00,
       1.80000e+00])

## 📅 Find Unique Release Years

The `unique()` function is used to display all the unique values present in the **Year** column.  
It helps to identify the different years in which movies were released and analyze the distribution of movies over time.

In [125]:
df['Year'].unique()

array([2007, 2008, 2009, 2010, 2011, 2012, 2013])

## 📅 Count Movies by Release Year

The `value_counts()` function is used to count the number of occurrences of each unique value in the **Year** column.  
It helps to understand the distribution of movies released in different years.

In [126]:
df['Year'].value_counts()

Year
2013    159
2012    157
2008    148
2011    141
2009    137
2010    136
2007     91
Name: count, dtype: int64

## 🎬 Count Movie Occurrences

The `value_counts()` function is used to count the frequency of each unique value in the **Movie** column.  
It helps to identify the number of times each movie title appears in the dataset and detect duplicate entries.

In [127]:
df['Movie'].value_counts()

Movie
All About Steve                             2
Spider-Man 3                                1
Shrek the Third                             1
Transformers                                1
Pirates of the Caribbean: At World's End    1
                                           ..
The Butler                                  1
The Canyons                                 1
The English Teacher                         1
John Dies at the End                        1
Lovelace                                    1
Name: count, Length: 968, dtype: int64

## 🎥 Count Movies by Lead Studio

The `value_counts()` function is used to count the number of movies associated with each unique value in the **LeadStudio** column.  
It helps to analyze the contribution and distribution of different movie production studios in the dataset.

In [128]:
df['LeadStudio'].value_counts()

LeadStudio
Independent                 133
Warner Bros                 114
Sony                         98
Fox                          91
Universal                    85
Paramount                    81
Lionsgate                    40
Disney                       39
Weinstein                    39
Summit                       33
Relativity Media             30
Buena Vista                  20
Focus                        17
Fox Searchlight              13
CBS                          12
DreamWorks                    8
Roadside Attractions          8
Open Road                     8
FilmDistrict                  7
Magnolia                      6
IFC                           6
MGM                           5
TriStar                       5
Miramax                       4
Eros                          4
New Line                      3
Spyglass Entertainment        3
Happy Madison                 3
Columbia                      3
Samuel Goldwyn                3
Screen Gems                   3
A24                           3
Liberty Starz                 2
Reliance                      2
Legendary Pictures            2
Yash Raj                      2
ARC Entertainment             2
LD Entertainment              2
Mediaplex                     1
Overture                      1
Crest                         1
Highlight Communications      1
Vertigo                       1
Aardman Animations            1
Pixar                         1
Morgan Creek                  1
Village Roadshow              1
Regency Enterprises           1
Virgin                        1
Entertainment One             1
Atlas Distribution            1
UTV                           1
Cohen Media                   1
Rocky Mountain                1
Music Box Films               1
Oscillloscope                 1
Millenium Entertainment       1
Cinedigm Entertainment        1
Radius-TWC                    1
Name: count, dtype: int64

## 🍅 Count RottenTomatoes Scores

The `value_counts()` function is used to count the frequency of each unique value in the **RottenTomatoes** column.  
It helps to understand the distribution of movie ratings and identify the most common scores.

In [129]:
df['RottenTomatoes'].value_counts()

RottenTomatoes
78.0    20
93.0    17
14.0    17
27.0    16
52.0    15
        ..
3.0      2
5.0      2
99.0     2
1.0      1
0.0      1
Name: count, Length: 100, dtype: int64

## ⭐ Count Audience Scores

The `value_counts()` function is used to count the frequency of each unique value in the **AudienceScore** column.  
It helps to analyze the distribution of audience ratings and identify the most frequently occurring scores.

In [130]:
df['AudienceScore'].value_counts()

AudienceScore
73.0    28
72.0    26
57.0    24
55.0    23
56.0    23
        ..
96.0     1
26.0     1
24.0     1
19.0     1
20.0     1
Name: count, Length: 73, dtype: int64

## 📖 Count Story Occurrences

The `value_counts()` function is used to count the frequency of each unique value in the **Story** column.  
It helps to identify the number of times each story description appears in the dataset and analyze repeated entries.

In [131]:
df['Story'].value_counts()

Story
Comedy                80
Love                  64
Monster Force         60
Quest                 51
Rivalry               33
Discovery             31
Pursuit               30
Revenge               27
Transformation        25
Maturation            24
Rescue                21
Journey and Return    20
The Riddle            19
Underdog              17
Escape                17
Sacrifice             12
Temptation            12
Metamorphosis         10
love                   9
quest                  7
Tragedy                7
escape                 6
Fish Out Of Water      6
Wretched Excess        5
pursuit                4
sacrifice              4
rescue                 4
fish out of water      4
rivalry                4
Fish Out of Water      4
comedy                 4
Rags to Riches         4
riddle                 3
discovery              2
maturation             2
underdog               2
monster force          2
journey & return       1
tragedy                1
temptation             1
transformation         1
Rags To Riches         1
Name: count, dtype: int64

## 🎭 Count Movie Genres

The `value_counts()` function is used to count the frequency of each unique value in the **Genre** column.  
It helps to understand the distribution of different movie genres and identify the most common categories.

In [132]:
df['Genre'].value_counts()

Genre
Comedy         177
Action         166
Drama          109
Horror          52
Animation       51
Thriller        35
Adventure       30
Romance         20
Crime           15
Biography       14
Documentary      7
Fantasy          6
Mystery          5
Musical          4
Name: count, dtype: int64

## 🎬 Count Theaters Open Week Values

The `value_counts()` function is used to count the frequency of each unique value in the **TheatersOpenWeek** column.  
It helps to analyze how many movies were released in different numbers of theaters during their opening week.

In [133]:
df['TheatersOpenWeek'].value_counts()

TheatersOpenWeek
4.0       13
2.0        7
3.0        6
3121.0     4
2511.0     4
          ..
351.0      1
87.0       1
222.0      1
2933.0     1
118.0      1
Name: count, Length: 789, dtype: int64

## 💰 Count Opening Weekend Values

The `value_counts()` function is used to count the frequency of each unique value in the **OpeningWeekend** column.  
It helps to analyze the distribution of movies based on their opening weekend earnings and identify commonly occurring values.

In [134]:
df['OpeningWeekend'].value_counts()

OpeningWeekend
0.04     9
0.11     8
10.60    6
0.14     6
0.26     6
        ..
2.46     1
0.89     1
1.01     1
1.49     1
0.69     1
Name: count, Length: 721, dtype: int64

## 💵 Count BOAvgOpenWeekend Values

The `value_counts()` function is used to count the frequency of each unique value in the **BOAvgOpenWeekend** column.  
It helps to analyze the distribution of average box office opening weekend values and understand movie performance patterns.

In [135]:
df['BOAvgOpenWeekend'].value_counts()

BOAvgOpenWeekend
2615.0     3
5000.0     2
5175.0     2
3610.0     2
2617.0     2
          ..
8400.0     1
13351.0    1
3001.0     1
12467.0    1
1564.0     1
Name: count, Length: 912, dtype: int64

## 💰 Count Domestic Gross Values

The `value_counts()` function is used to count the frequency of each unique value in the **DomesticGross** column.  
It helps to analyze the distribution of domestic box office earnings and identify the most common revenue values.

In [136]:
df['DomesticGross'].value_counts()

DomesticGross
118.87    2
36.79     2
25.93     2
25.13     2
19.07     2
         ..
116.63    1
0.06      1
0.10      1
0.14      1
0.36      1
Name: count, Length: 935, dtype: int64

## 🌍 Count Foreign Gross Values

The `value_counts()` function is used to count the frequency of each unique value in the **ForeignGross** column.  
It helps to analyze the distribution of international box office earnings and identify the most common foreign revenue values.

In [137]:
df['ForeignGross'].value_counts()

ForeignGross
0.03     3
10.36    3
14.15    2
5.05     2
14.28    2
        ..
5.34     1
2.67     1
0.10     1
0.06     1
1.17     1
Name: count, Length: 842, dtype: int64

## 🌎 Count World Gross Values

The `value_counts()` function is used to count the frequency of each unique value in the **WorldGross** column.  
It helps to analyze the distribution of worldwide box office earnings and identify the most common global revenue values.

In [138]:
df['WorldGross'].value_counts()

WorldGross
100.08    2
77.71     2
91.40     2
40.12     2
31.43     2
         ..
167.74    1
0.19      1
0.10      1
0.14      1
1.52      1
Name: count, Length: 899, dtype: int64

## 💵 Count Budget Values

The `value_counts()` function is used to count the frequency of each unique value in the **Budget** column.  
It helps to analyze the distribution of movie production budgets and identify the most common budget values in the dataset.

In [139]:
df['Budget'].value_counts()

Budget
20.0     55
30.0     46
40.0     39
35.0     37
25.0     35
         ..
115.0     1
43.0      1
84.0      1
4.6       1
4.9       1
Name: count, Length: 151, dtype: int64

## 📈 Count Profitability Values

The `value_counts()` function is used to count the frequency of each unique value in the **Profitability** column.  
It helps to analyze the distribution of movie profitability values and understand the financial performance patterns of movies.

In [140]:
df['Profitability'].value_counts()

Profitability
68.77     2
175.61    2
254.82    2
350.57    2
138.52    2
         ..
539.10    1
559.14    1
77.21     1
14.20     1
15.25     1
Name: count, Length: 883, dtype: int64

## 🎲 Display Random Sample Data

The `sample()` function is used to display random rows from the dataset.  
It helps to get a quick overview of random records and check the variety of data present in the DataFrame.

In [141]:
df.sample(5)

,Movie,LeadStudio,RottenTomatoes,AudienceScore,Story,Genre,TheatersOpenWeek,OpeningWeekend,BOAvgOpenWeekend,DomesticGross,ForeignGross,WorldGross,Budget,Profitability,OpenProfit,Year
306,Planet 51,Independent,22.0,45.0,Comedy,Animation,3035.0,12.30,4048.0,42.19,63.45,105.64,70.0,150.91,17.57,2009
602,Soul Surfer,Sony,46.0,79.0,Underdog,Drama,2214.0,10.60,4789.0,43.85,3.24,47.09,18.0,261.60,58.89,2011
257,Paul Blart: Mall Cop,Sony,33.0,50.0,Comedy,Action,3144.0,31.80,10125.0,146.33,36.95,183.28,26.0,704.92,122.31,2009
614,The Change Up,Relativity Media,24.0,53.0,Metamorphosis,Comedy,2913.0,13.53,4645.0,37.08,38.37,75.45,52.0,145.09,26.02,2011
255,Fast and Furious,Universal,28.0,76.0,Revenge,Action,3461.0,70.90,20500.0,155.10,208.00,363.10,85.0,427.18,83.41,2009

## 💾 Check Memory Usage

The `memory_usage(deep=True)` function is used to calculate the memory consumption of each column in the dataset.  
It helps to understand how much memory is used by the DataFrame and optimize data storage.

In [142]:
df.memory_usage(deep=True)

Index                7752
Movie               62147
LeadStudio          55591
RottenTomatoes       7752
AudienceScore        7752
Story               47271
Genre               47202
TheatersOpenWeek     7752
OpeningWeekend       7752
BOAvgOpenWeekend     7752
DomesticGross        7752
ForeignGross         7752
WorldGross           7752
Budget               7752
Profitability        7752
OpenProfit           7752
Year                 7752
dtype: int64

## 📋 Display Column Names

The `columns` attribute is used to display the names of all columns present in the dataset.  
It helps to understand the features and structure of the DataFrame.

In [143]:
df.columns

Index(['Movie', 'LeadStudio', 'RottenTomatoes', 'AudienceScore', 'Story',
       'Genre', 'TheatersOpenWeek', 'OpeningWeekend', 'BOAvgOpenWeekend',
       'DomesticGross', 'ForeignGross', 'WorldGross', 'Budget',
       'Profitability', 'OpenProfit', 'Year'],
      dtype='str')

## 🔗 Correlation Analysis

The `corr()` function is used to calculate the correlation between numerical columns in the dataset.  
It helps to understand the relationship and dependency between different numerical features.

In [144]:
df.corr(numeric_only=True)

,RottenTomatoes,AudienceScore,TheatersOpenWeek,OpeningWeekend,BOAvgOpenWeekend,DomesticGross,ForeignGross,WorldGross,Budget,Profitability,OpenProfit,Year
RottenTomatoes,1.000000,0.703083,-0.196008,0.108525,0.230546,0.230328,0.189761,0.204031,0.070293,0.077617,-0.075021,0.130172
AudienceScore,0.703083,1.000000,0.026593,0.298720,0.262974,0.432656,0.341542,0.383971,0.216258,0.084597,-0.096926,0.038879
TheatersOpenWeek,-0.196008,0.026593,1.000000,0.628146,-0.031266,0.589028,0.484349,0.533987,0.607076,0.016417,0.052655,-0.165319
OpeningWeekend,0.108525,0.298720,0.628146,1.000000,0.423543,0.903359,0.767229,0.842006,0.686669,0.142737,0.109101,-0.057385
BOAvgOpenWeekend,0.230546,0.262974,-0.031266,0.423543,1.000000,0.419958,0.369411,0.410707,0.287068,0.099359,0.047153,0.029517
DomesticGross,0.230328,0.432656,0.589028,0.903359,0.419958,1.000000,0.859429,0.938730,0.696222,0.161559,0.043537,-0.049787
ForeignGross,0.189761,0.341542,0.484349,0.767229,0.369411,0.859429,1.000000,0.983282,0.725983,0.114153,-0.021122,0.070779
WorldGross,0.204031,0.383971,0.533987,0.842006,0.410707,0.938730,0.983282,1.000000,0.741850,0.139551,0.004331,0.024580
Budget,0.070293,0.216258,0.607076,0.686669,0.287068,0.696222,0.725983,0.741850,1.000000,-0.130644,-0.149365,0.018654
Profitability,0.077617,0.084597,0.016417,0.142737,0.099359,0.161559,0.114153,0.139551,-0.130644,1.000000,0.891753,0.042091
OpenProfit,-0.075021,-0.096926,0.052655,0.109101,0.047153,0.043537,-0.021122,0.004331,-0.149365,0.891753,1.000000,0.028239
Year,0.130172,0.038879,-0.165319,-0.057385,0.029517,-0.049787,0.070779,0.024580,0.018654,0.042091,0.028239,1.000000

## ❓ Check Missing Values

The `isnull().sum()` function is used to find the number of missing values present in each column of the dataset.  
It helps in identifying incomplete data and is an important step in the data cleaning process.

In [145]:
df.isnull().sum()

Movie                 0
LeadStudio            9
RottenTomatoes       57
AudienceScore        63
Story               328
Genre               278
TheatersOpenWeek     21
OpeningWeekend        1
BOAvgOpenWeekend     25
DomesticGross         0
ForeignGross         94
WorldGross           56
Budget               73
Profitability        74
OpenProfit           75
Year                  0
dtype: int64

## 🎬 Select Important Movie Features

This step creates a new DataFrame by selecting specific columns from the original dataset.  
The selected features include **RottenTomatoes**, **TheatersOpenWeek**, and **OpenProfit**, which are useful for analyzing movie ratings, theater performance, and opening profits.

In [146]:
movies = df[['RottenTomatoes', 'TheatersOpenWeek', 'OpenProfit']]

## 📋 Display Dataset

The `print()` function is used to display the complete DataFrame in the output.  
It shows all the rows and columns of the dataset and helps to view the stored data.

In [147]:
print(df)

                                         Movie              LeadStudio  \
0                                 Spider-Man 3                    Sony
1                              Shrek the Third               Paramount
2                                 Transformers               Paramount
3     Pirates of the Caribbean: At World's End                  Disney
4    Harry Potter and the Order of the Phoenix             Warner Bros
..                                         ...                     ...
964                                 The Butler               Weinstein
965                                The Canyons                     IFC
967                        The English Teacher  Cinedigm Entertainment
968                       John Dies at the End                Magnolia
969                                   Lovelace              Radius-TWC

     RottenTomatoes  AudienceScore          Story      Genre  \
0              61.0           54.0  Metamorphosis     Action
1              42.0           57.0          Quest  Animation
2              57.0           89.0  Monster Force     Action
3              45.0           74.0         Rescue     Action
4              78.0           82.0          Quest  Adventure
..              ...            ...            ...        ...
964            73.0           79.0            NaN        NaN
965            22.0            NaN            NaN        NaN
967            42.0            NaN            NaN        NaN
968            61.0           53.0            NaN        NaN
969            55.0           37.0            NaN  Biography

     TheatersOpenWeek  OpeningWeekend  BOAvgOpenWeekend  DomesticGross  \
0              4252.0          151.10           35540.0         336.53
1              4122.0          121.60           29507.0         322.72
2              4011.0           70.50           17577.0         319.25
3              4362.0          114.70           26302.0         309.42
4              4285.0           77.10           17998.0         292.00
..                ...             ...               ...            ...
964            2933.0           24.64            8400.0         116.63
965               1.0            0.01           13351.0           0.06
967               2.0            0.01            3001.0           0.10
968               1.0            0.01           12467.0           0.14
969             118.0            0.18            1564.0           0.36

     ForeignGross  WorldGross  Budget  Profitability  OpenProfit  Year
0          554.34      890.87   258.0         345.30       58.57  2007
1          476.24      798.96   160.0         499.35       76.00  2007
2          390.46      709.71   150.0         473.14       47.00  2007
3          654.00      963.42   300.0         321.14       38.23  2007
4          647.88      939.89   150.0         626.59       51.40  2007
..            ...         ...     ...            ...         ...   ...
964         51.11      167.74    30.0         559.14       82.13  2013
965          0.14        0.19     NaN          77.21         NaN  2013
967          0.06        0.10     NaN            NaN         NaN  2013
968           NaN        0.14     1.0          14.20        1.00  2013
969          1.17        1.52    10.0          15.25        1.80  2013

[969 rows x 16 columns]

## 🎬 Display Selected Movie Data

The `head()` function is used to display the first five rows of the **movies** DataFrame.  
It helps to quickly check the selected features and verify the extracted data.

In [148]:
movies.head()

   RottenTomatoes  TheatersOpenWeek  OpenProfit
0            61.0            4252.0       58.57
1            42.0            4122.0       76.00
2            57.0            4011.0       47.00
3            45.0            4362.0       38.23
4            78.0            4285.0       51.40

### 📊 DataFrame Shape, Size & Dimensions

- 📐 **Shape:** `df.shape` returns the number of **rows and columns** in the DataFrame.
- 🔢 **Size:** `df.size` returns the **total number of elements** (rows × columns).
- 📏 **Dimensions:** `df.ndim` returns the **number of dimensions** of the DataFrame. For a DataFrame, it is usually `2`.

In [149]:
print("Shape:", df.shape)
print("Size:", df.size)
print("Dimensions:", df.ndim)

Shape: (969, 16)
Size: 15504
Dimensions: 2

### 🎬 Converting Movie Data into NumPy Arrays

- 🎯 **AudienceScore:** `df["AudienceScore"]` se audience scores ko select karke NumPy array mein convert kiya gaya.
- 🌍 **WorldGross:** `df["WorldGross"]` se worldwide gross values ko select karke NumPy array mein convert kiya gaya.
- 🖨️ **Print:** `print()` ka use karke dono NumPy arrays ke values display ki gayi hain.

In [150]:
AudienceScore = np.array(df["AudienceScore"])
WorldGross = np.array(df["WorldGross"])

print(AudienceScore)
print(WorldGross)

[54. 57. 89. 74. 82. 69. 91. 72. 73. 90. 84. 78. 72. 83. 89. 68. 86. 55.
 87. 80. 57. 87. 73. 84. 66. 74. 56. 56. 75. 56. 81. 75. 52. 75. 84. 55.
 73. 70. 83. 64. 64. 47. 63. 82. 85. 81. 70. 72. 55. 78. 82. 55. 64. 37.
 84. 38. 61. 57. 86. 65. 41. 64. 61. 73. 56. 63. 75. 52. 61. 64. 53. 86.
 87. 84. 50. 46. 67. 90. 55. 59. 45. 85. 43. 43. 48. 63. 66. 79. 72. 44.
 41. 96. 91. 59. 67. 89. 83. 73. 82. 62. 75. 81. 90. 76. 78. 90. 75. 72.
 73. 52. 69. 63. 76. 77. 40. 55. 72. 68. 50. 72. 44. 56. 76. 74. 66. 73.
 72. 50. 67. 81. 71. 70. 34. 61. 67. 53. 75. 29. 75. 64. 59. 77. 81. 63.
 48. 65. 46. 54. 50. 69. 61. 56. 67. 61. 46. 70. 64. 36. 56. 36. 44. 44.
 65. 31. 65. 59. 78. 36. 69. 84. 46. 41. 51. 49. 38. 72. 88. 58. 46. 67.
 51. 70. 41. 49. 37. 74. 56. 41. 36. 65. 62. 40. 36. 42. 37. 66. 73. 32.
 34. 51. 55. 42. 51. 75. 29. 26. 32. 51. 44. 54. 33. 28. 68. 22. 60. 78.
 61. nan 37. 70. 42. 42. 39. 57. 47. 27. 74. 73. 41. 83. 84. 61. 64. 47.
 68. 48. 85. 42. 47. 92. 76. 75. 78. 86. 87. 91. 90. 59. 81. 65. 72. 72.
 60. 63. 74. 76. 62. 50. 83. 72. 65. 64. 70. 87. 50. 81. 63. 47. 56. 68.
 72. 65. 69. 60. 68. 76. 50. 66. 59. 87. 77. 77. 57. 82. 72. 50. 50. 52.
 60. 52. 70. 65. 48. 56. 51. 47. 58. 48. 49. 38. 73. 68. 53. 57. 31. 39.
 45. 61. 65. 38. 42. 57. 74. 71. 66. 47. 35. 45. 42. 43. 81. 47. 58. 59.
 31. 48. 52. 62. 67. 35. 44. 39. 46. 40. 40. 43. 80. 43. 40. 53. 47. 51.
 52. 83. 37. 44. 56. 34. 50. 27. 38. 35. 50. 54. 73. 78. 52. 59. 38. 37.
 66. 49. 28. 27. 74. 28. 64. 55. 28. 43. 72. 65. 48. 31. 63. 60. 84. 40.
 72. 35. 41. 86. 47. 63. 66. 42. 43. 62. 77. 48. 71. 45. 56. 51. 58. 50.
 66. 48. 81. 45. 49. 47. 56. 75. 46. 56. 55. 50. 73. 57. 36. 63. 56. 60.
 40. 59. 31. 87. 57. 90. 57. 93. 80. 72. 24. 58. 83. 45. 52. 49. 65. 36.
 62. 62. 40. 55. 33. 66. 46. 73. 54. 29. 54. 70. 49. nan 57. 45. 62. 52.
 71. 72. 70. 43. 53. 59. 62. 47. 83. 49. 60. 64. 73. 19. 47. 67. 20. 57.
 88. 71. 37. 47. 68. 41. 63. 54. 58. 88. 68. 47. 75. 72. 93. 42. 32. 66.
 55. 66. 57. 56. 89. 57. 46. 44. 44. 83. 74. 38. 46. 91. 67. 86. 73. 54.
 32. 43. 44. 67. 36. 45. 35. 52. 48. 93. 89. 71. 46. 66. 74. 31. 49. 82.
 62. 38. 50. 50. 80. 77. 75. 56. 61. 55. 34. 63. 50. 81. 63. 81. 37. 38.
 79. 38. 28. 53. 62. 83. 56. 71. 68. 68. 52. 48. 44. 67. 59. 92. 50. 72.
 84. 57. 59. 55. 65. 84. 59. 55. 63. 48. 80. 46. 73. 71. 73. 43. 84. 86.
 89. 50. 54. 84. 48. 57. 54. 79. 58. 70. 61. 37. 76. 69. 81. 41. 59. 73.
 87. 39. 57. 32. 80. 25. 79. nan 79. 81. 40. 48. 78. 46. 85. 67. 78. 91.
 57. 62. 53. 55. 65. 70. 88. 31. 43. 89. 47. 58. 91. 76. 54. 82. 52. 87.
 43. 29. 48. 43. 50. 52. 48. 61. 80. 68. 61. 67. 68. 57. 73. 93. 72. 79.
 50. 79. 88. 36. 42. 82. nan nan 51. nan nan 63. nan 51. 63. 90. nan nan
 55. 76. 64. 76. nan nan nan nan 29. 71. 67. 58. nan nan 46. 64. 92. 64.
 72. nan 86. nan nan 75. nan nan 70. nan 32. nan nan 40. nan 56. 72. 42.
 nan nan nan 63. nan 67. nan nan 60. 60. 73. nan nan 44. nan 75. 79. 85.
 81. 82. 73. 61. 52. nan 91. 71. 45. nan 86. nan nan 36. 72. 61. 83. 60.
 69. nan nan 52. 58. 51. 81. nan 55. nan nan 60. 64. nan 64. nan 55. nan
 nan 71. 86. nan 61. 86. nan 52. 65. 69. 54. nan 74. 53. 77. nan 79. 58.
 73. 51. nan nan 90. 22. 45. 68. 52. 61. 40. 83. 81. 85. 68. 59. 89. 60.
 49. nan nan nan 49. 71. 63. 40. 55. 51. 47. 62. 48. nan 49. 87. nan 80.
 83. 40. 49. 48. 55. 38. 92. 59. 88. 61. 41. 60. 77. 80. 85. 92. 85. 89.
 84. 83. 85. 76. 83. 79. 73. 57. 90. 70. 78. 49. 45. 71. 68. 58. 83. 42.
 61. 60. 67. 73. 66. 55. 66. 73. 54. 51. 63. 58. 56. 83. 55. 76. 80. 62.
 79. 60. 68. 66. 57. 64. 68. 92. 73. 56. 62. 74. 72. 59. 56. 64. 86. 81.
 nan 54. 89. 47. 61. 92. 37. 48. 91. 48. 41. 39. 90. 68. 25. 66. 71. 34.
 34. 54. 62. 65. 55. 50. 73. 49. 63. 85. 75. 72. 39. 66. 52. 92. 64. 85.
 25. 57. 73. 50. 78. 64. 76. 85. 56. 42. 76. 42. 34. 48. 34. 92. 52. 27.
 39. nan 38. 86. 53. 82. 36. 41. 57. 87. 71. nan 66. 33. 45. 37. 78. 47.
 47. 74. 66. 79. 57. 60. 63. 35. 89. 78. 79. nan nan 53. 37.]
[8.908700e+02 7.989600e+02 7.097100e+02 9.634200e+02 9.398900e+02
 5.853500e+02 4.428200e+02 4.573600e+02 3.613400e+02 4.560700e+02
 6.237200e+02 5.270700e+02 2.536200e+02 2.190800e+02 2.314100e+02
 2.580200e+02 3.835300e+02 2.890500e+02 2.664600e+02 3.404900e+02
 2.875900e+02 1.698700e+02 1.860700e+02 2.025500e+02 1.457100e+02
 3.113100e+02 2.287400e+02 1.734200e+02 1.693300e+02 1.593100e+02
 1.753700e+02 1.478800e+02 1.963900e+02 1.177600e+02 1.716300e+02
 3.722300e+02 1.190000e+02 1.393500e+02 7.551000e+01 1.490400e+02
 8.025000e+01 5.586000e+01 9.561000e+01 1.568300e+02 7.002000e+01
 1.525200e+02 1.459000e+02 9.299000e+01 8.415000e+01 8.666000e+01
 9.570000e+01 6.931000e+01 9.260000e+01 1.288800e+02 7.618000e+01
 8.687000e+01 9.997000e+01 7.550000e+01 1.355600e+02 6.979000e+01
 1.277700e+02 5.710000e+01 5.919000e+01 8.479000e+01 6.947000e+01
 5.493000e+01 4.812000e+01 4.774000e+01 3.067000e+01 5.729000e+01
 6.277000e+01 2.542000e+01 3.609000e+01 2.937000e+01 3.747000e+01
 3.530000e+01 2.218000e+01 5.625000e+01 2.058000e+01 7.607000e+01
 3.562000e+01 7.328000e+01 3.809000e+01 4.017000e+01 6.322000e+01
 1.820000e+01 2.682000e+01 3.508000e+01 1.756000e+01 7.511000e+01
 3.082000e+01 1.004560e+03 5.855200e+02 7.866400e+02 6.243900e+02
 5.213100e+02 6.317400e+02 6.039000e+02 3.926200e+02 5.860900e+02
 2.971400e+02 4.152500e+02 2.699600e+02 6.098400e+02 4.196700e+02
 3.779100e+02 2.634300e+02 3.414300e+02 2.306900e+02 1.637300e+02
 1.880700e+02 2.128700e+02 3.099800e+02 2.427200e+02 4.011300e+02
 2.419900e+02 1.780700e+02 1.281100e+02 1.999400e+02 2.232400e+02
 2.697800e+02 1.492800e+02 2.529100e+02 1.016200e+02 2.002800e+02
 1.579300e+02 2.193800e+02 2.222300e+02 1.707600e+02 3.339300e+02
 1.602600e+02 1.603900e+02 2.330900e+02 1.511600e+02 1.628400e+02
 1.112300e+02 9.238000e+01 1.634000e+02 1.051700e+02 1.637200e+02
 6.416000e+01 1.681700e+02 1.508200e+02 1.138600e+02 8.239000e+01
 1.279800e+02 8.695000e+01 7.044000e+01 1.000800e+02 2.113400e+02
 1.059600e+02 5.155000e+01 4.435000e+01 9.395000e+01 5.720000e+01
 1.132400e+02 4.365000e+01 4.198000e+01 8.437000e+01 8.542000e+01
 7.846000e+01 4.465000e+01 1.151000e+02 8.465000e+01 4.349000e+01
 3.880000e+01 3.995000e+01 3.711000e+01 7.568000e+01 1.130200e+02
 6.828000e+01 4.388000e+01 3.347000e+01 4.969000e+01 4.086000e+01
 5.545000e+01 5.459000e+01 1.089800e+02 4.132000e+01 3.351000e+01
 5.696000e+01 4.210000e+01 4.130000e+01 7.749000e+01 6.483000e+01
 6.482000e+01 5.266000e+01 5.001000e+01 4.585000e+01 7.771000e+01
 6.557000e+01 4.788000e+01 7.124000e+01 2.951000e+01 4.163000e+01
 2.766000e+01 9.641000e+01 7.211000e+01 6.837000e+01 2.641000e+01
 2.767000e+01 3.075000e+01 4.162000e+01 5.091000e+01 3.903000e+01
 1.766000e+01 2.273000e+01 3.259000e+01 1.763000e+01 3.115000e+01
 4.249000e+01 3.482000e+01 4.331000e+01 1.542000e+01 2.707000e+01
 1.364000e+01 1.662000e+01 1.315000e+01 2.331000e+01 1.672000e+01
 1.233000e+01 5.065000e+01 1.177000e+01 3.058000e+01 2.221000e+01
 1.121000e+01 2.116000e+01 9.810000e+00 1.184000e+01 1.808000e+01
 4.042000e+01 1.876000e+01 8.880000e+00 1.010000e+01 9.320000e+00
 1.793000e+01 3.339000e+01 7.720000e+00 2.146000e+01 2.781500e+03
 8.363000e+02 9.340000e+02 7.098200e+02 7.313000e+02 4.674600e+02
 3.856500e+02 3.092000e+02 4.407000e+02 5.240200e+02 3.815000e+02
 8.866800e+02 3.731000e+02 4.130000e+02 7.696900e+02 3.147000e+02
 3.631000e+02 3.021000e+02 1.832800e+02 2.268000e+02 3.253300e+02
 4.859000e+02 3.720000e+02 2.430300e+02 3.214100e+02 2.851000e+02
 2.107700e+02 2.191000e+02 1.718300e+02 1.933600e+02 1.853000e+02
 2.670400e+02 2.141000e+02 1.265700e+02 1.788400e+02 2.052800e+02
 2.002000e+02 1.835800e+02 1.555500e+02 1.000800e+02 1.023900e+02
 1.245800e+02 1.264800e+02 1.182000e+02 2.611900e+02 9.140000e+01
 7.382000e+01 1.063800e+02 1.861900e+02 1.501600e+02 9.140000e+01
 1.363000e+02 1.013300e+02 1.308000e+02 1.151500e+02 7.752000e+01
 1.022200e+02 7.158000e+01 1.007300e+02 9.675000e+01 6.877000e+01
 9.571000e+01 9.135000e+01 1.083000e+02 9.351000e+01 6.235000e+01
 7.651000e+01 1.056400e+02 9.080000e+01 7.669000e+01 7.814000e+01
 1.224300e+02 6.159000e+01 1.222300e+02 8.830000e+01 4.436000e+01
 7.594000e+01 4.012000e+01 3.941000e+01 4.176000e+01 6.894000e+01
 6.072000e+01 4.885000e+01 4.841000e+01 3.831000e+01 8.528000e+01
 3.120000e+01 4.270000e+01 4.327000e+01 6.819000e+01 3.143000e+01
 4.770000e+01 6.010000e+01 5.788000e+01 2.696000e+01 3.608000e+01
 7.721000e+01 4.646000e+01 4.082000e+01 5.399000e+01 3.989000e+01
 3.240000e+01 6.244000e+01 1.860000e+01 4.922000e+01 3.155000e+01
 2.299000e+01 1.716000e+01 1.600000e+01 2.283000e+01 3.338000e+01
 1.582000e+01 1.920000e+01 3.923000e+01 3.450000e+01 1.600000e+01
 2.609000e+01 1.728000e+01 1.657000e+01 2.721000e+01 1.083000e+01
 1.070000e+01 1.700000e+01 1.220000e+01 1.000000e+01 1.489000e+01
 5.823000e+01 3.143000e+01 1.640000e+01 1.234000e+01 1.801000e+01
 3.634000e+01 2.763000e+01 9.980000e+00 6.380000e+00 3.509000e+01
 1.210000e+01 6.073000e+01 1.156700e+02 1.025466e+03 4.012000e+01
 5.050700e+01 3.293970e+02 3.643900e+01 1.914800e+01 8.951900e+01
 2.819000e+01 1.124900e+02 4.818800e+01 7.874000e+00 4.932140e+02
 9.710000e+00 5.558800e+01 2.052800e+01 9.920000e+00 1.522630e+02
 5.141000e+01 1.149700e+02 4.905000e+01 5.431130e+02 6.269400e+01
 7.570000e+01 8.685500e+01 2.117800e+02 7.495000e+01 2.045900e+02
 8.112000e+01 1.514000e+01 3.562600e+01 5.504900e+01 5.282900e+01
 3.623600e+01 9.125700e+01 4.205000e+01 9.487800e+01 6.150000e+00
 2.714300e+02 2.373820e+02 9.593000e+02 6.457100e+01 4.948800e+02
 2.072200e+01 8.255360e+02 6.239300e+02 1.716850e+02 1.091000e+01
 2.156900e+01 9.618800e+01 9.816000e+01 2.619270e+02 3.260800e+01
 1.400730e+02 6.792000e+01 7.917900e+01 5.337400e+01 3.106490e+02
 1.028020e+02 9.327000e+00 4.408900e+01 8.375700e+01 3.218840e+02
 6.003900e+01 2.097100e+01 9.324000e+01 9.450000e+00 2.141300e+01
 1.775110e+02 2.265000e+02 8.318800e+01 4.309000e+00 1.272320e+02
 3.363650e+02 1.990060e+02 5.603400e+01 1.841000e+01 2.962200e+02
 3.216690e+02 2.935020e+02 1.361500e+02 4.766000e+01 2.883470e+02
 4.977800e+01 7.526040e+02 2.948020e+02 6.681700e+01 5.178000e+00
 1.592910e+02 9.479000e+00 6.905000e+01 5.917940e+02 1.772360e+02
 6.787500e+01 7.747700e+01 1.571070e+02 1.363330e+02 4.156850e+02
 5.480300e+01 2.744690e+02 1.291540e+02 6.022000e+01 1.970000e+00
 3.591200e+02 3.470400e+01 4.142040e+02 3.197130e+02 6.773300e+01
 8.904000e+01 2.938000e+01 6.745000e+01 1.704310e+02 4.677000e+00
 2.249190e+02 2.152800e+02 4.523900e+01 4.983100e+01 2.783460e+02
 1.540250e+02 6.984890e+02 1.397900e+02 1.124600e+02 1.063160e+03
 4.000620e+02 2.522730e+02 1.678020e+02 2.164850e+02 8.054600e+01
 1.347430e+02 4.304000e+01 6.067000e+01 2.015840e+02 3.200300e+01
 3.426700e+01 1.964900e+01 4.055000e+01 3.919000e+01 2.746000e+01
 3.539000e+01 8.209000e+01 1.539000e+01 1.770000e+00 2.556000e+01
 4.574000e+01 1.474100e+02 1.750000e+02 2.162000e+02 2.118200e+02
 4.317000e+01 1.431000e+01 2.883800e+02 3.705700e+02 5.598500e+02
 6.860000e+00 6.097000e+01 4.880000e+01 1.354600e+02 1.748200e+02
 1.428500e+02 7.242000e+01 9.541000e+01 3.699000e+01 3.850000e+01
 7.617000e+01 2.893000e+01 4.630000e+00 2.710000e+00 5.524700e+01
 6.261300e+02 1.578900e+02 6.354000e+01 1.495400e+02 4.100000e+01
 1.939700e+02 2.198500e+02 8.316000e+01 6.378000e+01 1.504100e+02
 1.341510e+03 1.839500e+02 2.096400e+02 1.857690e+02 1.498800e+02
 2.269000e+02 1.739300e+02 9.701000e+01 8.461000e+01 1.496800e+02
 1.600800e+02 2.149500e+02 5.638000e+01 6.656900e+02 7.201000e+01
 1.618500e+02 1.100000e+00 1.950000e+01 3.899000e+01 1.511200e+02
 6.947100e+02 1.102000e+02 3.967000e+01 1.873600e+02 3.506000e+01
 1.420400e+02 1.492300e+02 5.939000e+01 2.482000e+01 2.070400e+02
 9.798000e+01 1.045710e+03 7.831000e+01 5.549900e+02 2.457200e+02
 2.992700e+02 8.916000e+01 1.100000e+00 4.846300e+02 4.817400e+02
 1.086100e+02 9.714000e+01 9.163000e+01 1.687400e+01 4.014000e+01
 5.454500e+02 6.018000e+01 4.709000e+01 1.473300e+02 8.556000e+01
 8.979000e+01 2.601000e+02 6.930000e+00 3.130000e+00 1.278700e+02
 3.739930e+02 1.334320e+02 6.370000e+00 7.450000e+00 7.545000e+01
 4.880000e+00 1.548000e+01 4.564000e+01 1.772400e+02 6.972000e+01
 2.712000e+01 2.321610e+02 2.278200e+02 5.867600e+02 2.166400e+02
 7.599000e+01 1.149550e+02 7.501000e+01 5.107000e+01 1.651800e+02
 9.605000e+01 4.049000e+01 2.395000e+01 3.494100e+01 5.637500e+02
 2.743000e+01 1.322700e+02 5.430000e+01 4.493200e+02 8.063000e+01
 1.529200e+02 1.123790e+03 7.121700e+02 1.307900e+02 1.775840e+02
 2.306000e+01 1.170900e+02 1.200810e+02 3.043000e+01 3.315000e+01
 3.536200e+02 2.486000e+01 1.698500e+02 2.015900e+02          nan
          nan 1.164700e+02          nan          nan 2.349900e+02
          nan 6.893000e+01 3.549000e+01 2.323300e+02          nan
          nan 3.030300e+02 1.280000e+01 2.472000e+01 5.389800e+02
          nan          nan          nan          nan 3.716000e+01
 1.266400e+02 1.304800e+02 9.626000e+01          nan          nan
 2.455300e+02 7.711000e+01 4.253700e+02 3.488400e+02 3.563000e+01
          nan 4.813000e+01          nan          nan 1.617700e+02
          nan          nan 8.149000e+01          nan 1.325600e+02
          nan          nan 3.337000e+01          nan 1.142800e+02
 3.583800e+02 3.946000e+01          nan          nan          nan
 8.772400e+02          nan 2.183400e+02          nan          nan
 2.841400e+02 3.352600e+02 3.273000e+01          nan          nan
 3.793000e+01          nan 5.368000e+01 4.418100e+02 6.090200e+02
 2.752900e+02 1.765100e+02 7.469200e+02 1.672200e+02 4.622000e+01
          nan 1.518590e+03 6.240300e+02 1.661700e+02          nan
 2.275000e+01          nan          nan 1.428400e+02 1.071400e+02
 1.197700e+02 1.130400e+02 3.108000e+01 4.033500e+02          nan
          nan 4.481000e+01 5.037000e+01 2.401600e+02 3.069400e+02
          nan 5.942000e+01          nan          nan 4.035000e+01
 2.080800e+02          nan 3.456000e+01          nan 8.297000e+01
          nan          nan 1.942000e+01 2.364100e+02          nan
 7.771000e+01 1.108560e+03          nan 3.965900e+02 2.464000e+01
 1.404700e+02 3.761400e+02          nan 5.493700e+02 5.772000e+01
 7.522200e+02          nan 1.368400e+02 2.761400e+02 6.649000e+01
 1.049100e+02          nan          nan 1.084440e+03 1.017600e+02
 1.793800e+02 3.054300e+02 5.391000e+01 7.728000e+01 4.186000e+01
 1.017000e+03 6.912500e+02 1.802700e+02 9.936000e+01 2.826000e+01
 3.338000e+01 1.230500e+02 8.545000e+01          nan          nan
          nan 5.482000e+01 8.296900e+02 1.961100e+02 6.827000e+01
 1.277300e+02 8.806000e+01 1.984700e+02 1.601100e+02 8.438000e+01
          nan 3.052700e+02 4.712200e+02          nan 1.328200e+02
 8.710000e+01 8.560000e+00 4.622000e+01 3.570000e+00 2.469800e+02
 2.438400e+02 2.164900e+02 1.333800e+02 1.221300e+02 1.208000e+01
 1.131900e+02 1.002000e+01 1.320000e+00 1.215440e+03 9.647600e+02
 8.559000e+02 8.473300e+02 8.104000e+02 7.886800e+02 7.435600e+02
 6.885100e+02 6.680500e+02 6.329100e+02 5.872000e+02 5.400100e+02
 4.933100e+02 4.673700e+02 4.148300e+02 4.110000e+02 3.757400e+02
 3.620000e+02 3.517200e+02 3.510400e+02 3.475500e+02 3.180000e+02
 3.046500e+02 2.861700e+02 2.861400e+02 2.825700e+02 2.699900e+02
 2.684300e+02 2.605000e+02 2.577700e+02 2.299300e+02 2.257000e+02
 2.197900e+02 2.053700e+02 1.998500e+02 1.976900e+02 1.756100e+02
 1.739700e+02 1.690400e+02 1.677100e+02 1.655000e+02 1.624000e+02
 1.615000e+02 1.610300e+02 1.490000e+02 1.464300e+02 1.420800e+02
 1.319400e+02 1.281800e+02 1.260400e+02 1.217600e+02 1.177400e+02
 1.169800e+02 1.122300e+02 1.052000e+02 9.834000e+01 9.754000e+01
 9.502000e+01 9.480000e+01 9.391000e+01 9.349000e+01 9.126000e+01
 9.084000e+01 9.057000e+01 9.025000e+01 8.933000e+01 8.618000e+01
 8.487000e+01 8.403000e+01 7.838000e+01 7.832000e+01 7.163000e+01
 7.135000e+01 7.024000e+01 6.857000e+01 6.337000e+01 6.268000e+01
 6.005000e+01 5.994000e+01 5.956000e+01 5.952000e+01 4.833000e+01
 4.823000e+01 4.609000e+01 4.558000e+01 4.293000e+01 3.593000e+01
 3.549000e+01 3.546000e+01 3.172000e+01 3.136000e+01 3.133000e+01
 3.085000e+01 3.045000e+01 3.037000e+01 2.993000e+01 2.924000e+01
 2.726000e+01 2.642000e+01 2.442000e+01 2.426000e+01 2.321000e+01
 2.320000e+01 2.246000e+01 2.182000e+01 2.042000e+01 1.970000e+01
 1.915000e+01 1.807000e+01 1.801000e+01 1.703000e+01 1.655000e+01
 1.518000e+01 1.501000e+01 1.379000e+01 1.172000e+01 1.172000e+01
 1.133000e+01 1.118000e+01 1.050000e+01 9.490000e+00 7.450000e+00
 7.370000e+00 7.040000e+00 6.850000e+00 6.260000e+00 5.750000e+00
 5.130000e+00 4.860000e+00 4.070000e+00 3.350000e+00 3.310000e+00
 2.960000e+00 2.400000e+00 2.340000e+00 2.290000e+00 2.160000e+00
 1.970000e+00 1.380000e+00 1.350000e+00          nan 1.677400e+02
 1.900000e-01 1.000000e-01 1.400000e-01 1.520000e+00]

### 📊 Calculate Average Values

- 🎯 **Average Audience Score:** `np.mean(AudienceScore)` calculates the **average audience score** of all movies.
- 🌍 **Average World Gross:** `np.mean(WorldGross)` calculates the **average worldwide gross** of all movies.
- 🖨️ **Print:** `print()` displays both average values.

In [151]:

print("Average Audience Score:", np.mean(AudienceScore))
print("Average World Gross:", np.mean(WorldGross))

Average Audience Score: nan
Average World Gross: nan

### 📋 Display Column Names

- 🏷️ **`df.columns`** returns the names of all columns present in the DataFrame.
- 👀 **`print()`** displays the column names on the screen.

In [152]:
print(df.columns)

Index(['Movie', 'LeadStudio', 'RottenTomatoes', 'AudienceScore', 'Story',
       'Genre', 'TheatersOpenWeek', 'OpeningWeekend', 'BOAvgOpenWeekend',
       'DomesticGross', 'ForeignGross', 'WorldGross', 'Budget',
       'Profitability', 'OpenProfit', 'Year'],
      dtype='str')

### 📊 Calculate Median Values

- 🎯 **Median Audience Score:** `np.median(AudienceScore)` finds the middle value of all audience scores.
- 🌍 **Median World Gross:** `np.median(WorldGross)` finds the middle value of all worldwide gross values.
- 🖨️ **Print:** `print()` displays both median values.

In [153]:
print("Median Audience Score:", np.median(AudienceScore))
print("Median World Gross:", np.median(WorldGross))

Median Audience Score: nan
Median World Gross: nan

### 📏 Calculate Standard Deviation

- 🎯 **Audience Score:** `np.std(AudienceScore)` calculates how much the audience scores vary from their average.
- 🌍 **World Gross:** `np.std(WorldGross)` calculates how much the worldwide gross values vary from their average.
- 📊 **Standard Deviation:** A higher value means the data is more spread out, while a lower value means the data is closer to the average.

In [154]:
print("Standard Deviation:", np.std(AudienceScore))
print("Standard Deviation:", np.std(WorldGross))

Standard Deviation: nan
Standard Deviation: nan

### 📊 Calculate Variance

- 🎯 **Audience Score:** `np.var(AudienceScore)` calculates the variance of audience scores.
- 🌍 **World Gross:** `np.var(WorldGross)` calculates the variance of worldwide gross values.
- 📈 **Variance:** It measures how far the data values are spread from their average. A higher variance means greater variation.

In [155]:
print("Variance:", np.var(AudienceScore))
print("Variance:", np.var(WorldGross))

Variance: nan
Variance: nan

### 🏆 Find Movie with Highest Audience Score

- 🔝 **`np.argmax(AudienceScore)`** finds the index of the movie with the **highest audience score**.
- 🎬 **`df.iloc[index]["Movie"]`** gets the movie name from that index.
- 🏷️ **`df.iloc[index]["Genre"]`** gets the genre of that movie.
- 🖨️ **`print()`** displays the movie name and its genre.

In [156]:
index = np.argmax(AudienceScore)

print("Movie:", df.iloc[index]["Movie"])
print("Rating:", df.iloc[index]["Genre"])

Movie: The Pirates Who Don't Do Anything
Rating: nan

### 📉 Find Movie with Lowest Audience Score

- 🔻 **`np.argmin(AudienceScore)`** finds the index of the movie with the **lowest audience score**.
- 🎬 **`df.iloc[index]["Movie"]`** gets the movie name at that index.
- 🏷️ **`df.iloc[index]["Genre"]`** gets the genre of that movie.
- 🖨️ **`print()`** displays the movie name and its genre.

In [157]:
index = np.argmin(AudienceScore)

print("Movie:", df.iloc[index]["Movie"])
print("Rating:", df.iloc[index]["Genre"])

Movie: The Pirates Who Don't Do Anything
Rating: nan

### 🎯 Filter Movies with High Audience Scores

- 🧹 **`~np.isnan(AudienceScore)`** checks that the audience score is **not missing (NaN)**.
- ⭐ **`AudienceScore > 80`** selects movies with an audience score **greater than 80**.
- 🔗 **`&`** combines both conditions.
- 🎬 **`df.loc[mask, ['Movie', 'AudienceScore']]`** selects the **Movie** and **AudienceScore** columns that match the conditions.
- 🔄 **`reset_index(drop=True)`** resets the index after filtering.
- 🖨️ **`print()`** displays the filtered list of high-rated movies.

In [158]:
mask = (~np.isnan(AudienceScore)) & (AudienceScore > 80)
high_rated = df.loc[mask, ['Movie', 'AudienceScore']].reset_index(drop=True)

print(high_rated)

                                         Movie  AudienceScore
0                                 Transformers           89.0
1    Harry Potter and the Order of the Phoenix           82.0
2                         The Bourne Ultimatum           91.0
3                                          300           90.0
4                                  Ratatouille           84.0
..                                         ...            ...
137                          Fruitvale Station           92.0
138                                   Nebraska           86.0
139                            Before Midnight           82.0
140                  Blue Is the Warmest Color           87.0
141                                     Wadjda           89.0

[142 rows x 2 columns]

### 💰 Calculate Average Revenue

- 🌍 **`WorldGross`** contains the worldwide gross/revenue values of the movies.
- 📊 **`np.mean(WorldGross)`** calculates the average worldwide revenue.
- 🖨️ **`print()`** displays the calculated average revenue.

In [159]:
print("Average Revenue:", np.mean(WorldGross))

Average Revenue: nan

### 💰🏆 Find Movie with Highest Revenue

- 🔝 **`np.argmax(WorldGross)`** finds the index of the movie with the **highest worldwide gross**.
- 🎬 **`df.iloc[index]["Movie"]`** gets the movie name at that index.
- 💰 **`df.iloc[index]["WorldGross"]`** gets the worldwide gross/revenue of that movie.
- 🖨️ **`print()`** displays the movie name and its revenue.

In [160]:
index = np.argmax(WorldGross)

print("Movie:", df.iloc[index]["Movie"])
print("Revenue:", df.iloc[index]["WorldGross"])

Movie: A Late Quartet
Revenue: nan

### 🎬⭐ Categorize Movies by Audience Score

- 🎯 **`AudienceScore >= 80`** checks whether the audience score is **80 or higher**.
- 🏆 **`"Excellent"`** is assigned to movies with an audience score of **80 or above**.
- 📉 **`"Average"`** is assigned to movies with an audience score **below 80**.
- 🔀 **`np.where()`** applies this condition to all values in the `AudienceScore` NumPy array.
- 🖨️ **`print()`** displays the rating category for each movie.

In [161]:
rating_category = np.where(
    AudienceScore >= 80,
    "Excellent",
    "Average"
)

print(rating_category)

['Average' 'Average' 'Excellent' 'Average' 'Excellent' 'Average'
 'Excellent' 'Average' 'Average' 'Excellent' 'Excellent' 'Average'
 'Average' 'Excellent' 'Excellent' 'Average' 'Excellent' 'Average'
 'Excellent' 'Excellent' 'Average' 'Excellent' 'Average' 'Excellent'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Excellent'
 'Average' 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average'
 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Excellent'
 'Excellent' 'Excellent' 'Average' 'Average' 'Average' 'Average'
 'Excellent' 'Average' 'Average' 'Average' 'Excellent' 'Average' 'Average'
 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Excellent' 'Excellent' 'Excellent' 'Average' 'Average' 'Average'
 'Excellent' 'Average' 'Average' 'Average' 'Excellent' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Excellent' 'Excellent' 'Average' 'Average' 'Excellent' 'Excellent'
 'Average' 'Excellent' 'Average' 'Average' 'Excellent' 'Excellent'
 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Excellent' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Excellent' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Excellent' 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Excellent' 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Average' 'Excellent'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Average'
 'Excellent' 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Excellent'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Excellent'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Excellent' 'Average' 'Excellent' 'Average' 'Excellent' 'Excellent'
 'Average' 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Excellent' 'Average'
 'Average' 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Excellent' 'Average' 'Average'
 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Excellent'
 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Excellent'
 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Excellent' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Excellent' 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Excellent'
 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Average'
 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Excellent' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Excellent' 'Excellent'
 'Excellent' 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Excellent' 'Average' 'Average' 'Average' 'Excellent' 'Average' 'Average'
 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Excellent'
 'Average' 'Average' 'Average' 'Average' 'Excellent' 'Average' 'Average'
 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Excellent' 'Average' 'Average' 'Excellent' 'Average' 'Average'
 'Excellent' 'Average' 'Average' 'Excellent' 'Average' 'Excellent'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Excellent'
 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Excellent' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average'
 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Excellent' 'Excellent'
 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Excellent' 'Average'
 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Excellent' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Excellent' 'Excellent' 'Excellent' 'Average' 'Average'
 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Excellent' 'Average' 'Excellent'
 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Average' 'Excellent'
 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Average' 'Excellent' 'Average' 'Average' 'Average'
 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Excellent' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Excellent' 'Excellent' 'Average' 'Average'
 'Excellent' 'Average' 'Average' 'Excellent' 'Average' 'Average'
 'Excellent' 'Average' 'Average' 'Average' 'Excellent' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Excellent' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Excellent' 'Average' 'Excellent'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Excellent' 'Average' 'Excellent' 'Average' 'Average' 'Average'
 'Excellent' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Excellent' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average']

### 🎬📊 Categorize Movies by Audience Score

- 🏆 **`AudienceScore >= 80`** → Movie is classified as **"Hit"**.
- ⭐ **`AudienceScore >= 60`** → Movie is classified as **"Average"**.
- 📉 **`AudienceScore < 60`** → Movie is classified as **"Low"**.
- 🔀 **Nested `np.where()`** is used to apply multiple conditions.
- 🖨️ **`print()`** displays the category for each movie.

In [162]:
result = np.where(
    AudienceScore >= 80,
    "Hit",
    np.where(AudienceScore >= 60, "Average", "Low")
)

print(result)

['Low' 'Low' 'Hit' 'Average' 'Hit' 'Average' 'Hit' 'Average' 'Average'
 'Hit' 'Hit' 'Average' 'Average' 'Hit' 'Hit' 'Average' 'Hit' 'Low' 'Hit'
 'Hit' 'Low' 'Hit' 'Average' 'Hit' 'Average' 'Average' 'Low' 'Low'
 'Average' 'Low' 'Hit' 'Average' 'Low' 'Average' 'Hit' 'Low' 'Average'
 'Average' 'Hit' 'Average' 'Average' 'Low' 'Average' 'Hit' 'Hit' 'Hit'
 'Average' 'Average' 'Low' 'Average' 'Hit' 'Low' 'Average' 'Low' 'Hit'
 'Low' 'Average' 'Low' 'Hit' 'Average' 'Low' 'Average' 'Average' 'Average'
 'Low' 'Average' 'Average' 'Low' 'Average' 'Average' 'Low' 'Hit' 'Hit'
 'Hit' 'Low' 'Low' 'Average' 'Hit' 'Low' 'Low' 'Low' 'Hit' 'Low' 'Low'
 'Low' 'Average' 'Average' 'Average' 'Average' 'Low' 'Low' 'Hit' 'Hit'
 'Low' 'Average' 'Hit' 'Hit' 'Average' 'Hit' 'Average' 'Average' 'Hit'
 'Hit' 'Average' 'Average' 'Hit' 'Average' 'Average' 'Average' 'Low'
 'Average' 'Average' 'Average' 'Average' 'Low' 'Low' 'Average' 'Average'
 'Low' 'Average' 'Low' 'Low' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Low' 'Average' 'Hit' 'Average' 'Average' 'Low' 'Average'
 'Average' 'Low' 'Average' 'Low' 'Average' 'Average' 'Low' 'Average' 'Hit'
 'Average' 'Low' 'Average' 'Low' 'Low' 'Low' 'Average' 'Average' 'Low'
 'Average' 'Average' 'Low' 'Average' 'Average' 'Low' 'Low' 'Low' 'Low'
 'Low' 'Average' 'Low' 'Average' 'Low' 'Average' 'Low' 'Average' 'Hit'
 'Low' 'Low' 'Low' 'Low' 'Low' 'Average' 'Hit' 'Low' 'Low' 'Average' 'Low'
 'Average' 'Low' 'Low' 'Low' 'Average' 'Low' 'Low' 'Low' 'Average'
 'Average' 'Low' 'Low' 'Low' 'Low' 'Average' 'Average' 'Low' 'Low' 'Low'
 'Low' 'Low' 'Low' 'Average' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low'
 'Low' 'Average' 'Low' 'Average' 'Average' 'Average' 'Low' 'Low' 'Average'
 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Average' 'Average' 'Low' 'Hit' 'Hit'
 'Average' 'Average' 'Low' 'Average' 'Low' 'Hit' 'Low' 'Low' 'Hit'
 'Average' 'Average' 'Average' 'Hit' 'Hit' 'Hit' 'Hit' 'Low' 'Hit'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Low' 'Hit' 'Average' 'Average' 'Average' 'Average' 'Hit' 'Low'
 'Hit' 'Average' 'Low' 'Low' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Low' 'Average' 'Low' 'Hit' 'Average'
 'Average' 'Low' 'Hit' 'Average' 'Low' 'Low' 'Low' 'Average' 'Low'
 'Average' 'Average' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low'
 'Average' 'Average' 'Low' 'Low' 'Low' 'Low' 'Low' 'Average' 'Average'
 'Low' 'Low' 'Low' 'Average' 'Average' 'Average' 'Low' 'Low' 'Low' 'Low'
 'Low' 'Hit' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Average' 'Average' 'Low'
 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Hit' 'Low' 'Low' 'Low' 'Low' 'Low'
 'Low' 'Hit' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low'
 'Average' 'Average' 'Low' 'Low' 'Low' 'Low' 'Average' 'Low' 'Low' 'Low'
 'Average' 'Low' 'Average' 'Low' 'Low' 'Low' 'Average' 'Average' 'Low'
 'Low' 'Average' 'Average' 'Hit' 'Low' 'Average' 'Low' 'Low' 'Hit' 'Low'
 'Average' 'Average' 'Low' 'Low' 'Average' 'Average' 'Low' 'Average' 'Low'
 'Low' 'Low' 'Low' 'Low' 'Average' 'Low' 'Hit' 'Low' 'Low' 'Low' 'Low'
 'Average' 'Low' 'Low' 'Low' 'Low' 'Average' 'Low' 'Low' 'Average' 'Low'
 'Average' 'Low' 'Low' 'Low' 'Hit' 'Low' 'Hit' 'Low' 'Hit' 'Hit' 'Average'
 'Low' 'Low' 'Hit' 'Low' 'Low' 'Low' 'Average' 'Low' 'Average' 'Average'
 'Low' 'Low' 'Low' 'Average' 'Low' 'Average' 'Low' 'Low' 'Low' 'Average'
 'Low' 'Low' 'Low' 'Low' 'Average' 'Low' 'Average' 'Average' 'Average'
 'Low' 'Low' 'Low' 'Average' 'Low' 'Hit' 'Low' 'Average' 'Average'
 'Average' 'Low' 'Low' 'Average' 'Low' 'Low' 'Hit' 'Average' 'Low' 'Low'
 'Average' 'Low' 'Average' 'Low' 'Low' 'Hit' 'Average' 'Low' 'Average'
 'Average' 'Hit' 'Low' 'Low' 'Average' 'Low' 'Average' 'Low' 'Low' 'Hit'
 'Low' 'Low' 'Low' 'Low' 'Hit' 'Average' 'Low' 'Low' 'Hit' 'Average' 'Hit'
 'Average' 'Low' 'Low' 'Low' 'Low' 'Average' 'Low' 'Low' 'Low' 'Low' 'Low'
 'Hit' 'Hit' 'Average' 'Low' 'Average' 'Average' 'Low' 'Low' 'Hit'
 'Average' 'Low' 'Low' 'Low' 'Hit' 'Average' 'Average' 'Low' 'Average'
 'Low' 'Low' 'Average' 'Low' 'Hit' 'Average' 'Hit' 'Low' 'Low' 'Average'
 'Low' 'Low' 'Low' 'Average' 'Hit' 'Low' 'Average' 'Average' 'Average'
 'Low' 'Low' 'Low' 'Average' 'Low' 'Hit' 'Low' 'Average' 'Hit' 'Low' 'Low'
 'Low' 'Average' 'Hit' 'Low' 'Low' 'Average' 'Low' 'Hit' 'Low' 'Average'
 'Average' 'Average' 'Low' 'Hit' 'Hit' 'Hit' 'Low' 'Low' 'Hit' 'Low' 'Low'
 'Low' 'Average' 'Low' 'Average' 'Average' 'Low' 'Average' 'Average' 'Hit'
 'Low' 'Low' 'Average' 'Hit' 'Low' 'Low' 'Low' 'Hit' 'Low' 'Average' 'Low'
 'Average' 'Hit' 'Low' 'Low' 'Average' 'Low' 'Hit' 'Average' 'Average'
 'Hit' 'Low' 'Average' 'Low' 'Low' 'Average' 'Average' 'Hit' 'Low' 'Low'
 'Hit' 'Low' 'Low' 'Hit' 'Average' 'Low' 'Hit' 'Low' 'Hit' 'Low' 'Low'
 'Low' 'Low' 'Low' 'Low' 'Low' 'Average' 'Hit' 'Average' 'Average'
 'Average' 'Average' 'Low' 'Average' 'Hit' 'Average' 'Average' 'Low'
 'Average' 'Hit' 'Low' 'Low' 'Hit' 'Low' 'Low' 'Low' 'Low' 'Low' 'Average'
 'Low' 'Low' 'Average' 'Hit' 'Low' 'Low' 'Low' 'Average' 'Average'
 'Average' 'Low' 'Low' 'Low' 'Low' 'Low' 'Average' 'Average' 'Low' 'Low'
 'Low' 'Low' 'Average' 'Hit' 'Average' 'Average' 'Low' 'Hit' 'Low' 'Low'
 'Average' 'Low' 'Low' 'Average' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low'
 'Average' 'Low' 'Low' 'Low' 'Low' 'Average' 'Low' 'Average' 'Low' 'Low'
 'Average' 'Average' 'Average' 'Low' 'Low' 'Low' 'Low' 'Average' 'Average'
 'Hit' 'Hit' 'Hit' 'Average' 'Average' 'Low' 'Low' 'Hit' 'Average' 'Low'
 'Low' 'Hit' 'Low' 'Low' 'Low' 'Average' 'Average' 'Hit' 'Average'
 'Average' 'Low' 'Low' 'Low' 'Low' 'Low' 'Hit' 'Low' 'Low' 'Low' 'Low'
 'Average' 'Average' 'Low' 'Average' 'Low' 'Low' 'Low' 'Low' 'Average'
 'Hit' 'Low' 'Average' 'Hit' 'Low' 'Low' 'Average' 'Average' 'Low' 'Low'
 'Average' 'Low' 'Average' 'Low' 'Average' 'Low' 'Average' 'Low' 'Low'
 'Low' 'Hit' 'Low' 'Low' 'Average' 'Low' 'Average' 'Low' 'Hit' 'Hit' 'Hit'
 'Average' 'Low' 'Hit' 'Average' 'Low' 'Low' 'Low' 'Low' 'Low' 'Average'
 'Average' 'Low' 'Low' 'Low' 'Low' 'Average' 'Low' 'Low' 'Low' 'Hit' 'Low'
 'Hit' 'Hit' 'Low' 'Low' 'Low' 'Low' 'Low' 'Hit' 'Low' 'Hit' 'Average'
 'Low' 'Average' 'Average' 'Hit' 'Hit' 'Hit' 'Hit' 'Hit' 'Hit' 'Hit' 'Hit'
 'Average' 'Hit' 'Average' 'Average' 'Low' 'Hit' 'Average' 'Average' 'Low'
 'Low' 'Average' 'Average' 'Low' 'Hit' 'Low' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Low' 'Average' 'Average' 'Low' 'Low' 'Average' 'Low'
 'Low' 'Hit' 'Low' 'Average' 'Hit' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Low' 'Average' 'Average' 'Hit' 'Average' 'Low' 'Average'
 'Average' 'Average' 'Low' 'Low' 'Average' 'Hit' 'Hit' 'Low' 'Low' 'Hit'
 'Low' 'Average' 'Hit' 'Low' 'Low' 'Hit' 'Low' 'Low' 'Low' 'Hit' 'Average'
 'Low' 'Average' 'Average' 'Low' 'Low' 'Low' 'Average' 'Average' 'Low'
 'Low' 'Average' 'Low' 'Average' 'Hit' 'Average' 'Average' 'Low' 'Average'
 'Low' 'Hit' 'Average' 'Hit' 'Low' 'Low' 'Average' 'Low' 'Average'
 'Average' 'Average' 'Hit' 'Low' 'Low' 'Average' 'Low' 'Low' 'Low' 'Low'
 'Hit' 'Low' 'Low' 'Low' 'Low' 'Low' 'Hit' 'Low' 'Hit' 'Low' 'Low' 'Low'
 'Hit' 'Average' 'Low' 'Average' 'Low' 'Low' 'Low' 'Average' 'Low' 'Low'
 'Average' 'Average' 'Average' 'Low' 'Average' 'Average' 'Low' 'Hit'
 'Average' 'Average' 'Low' 'Low' 'Low' 'Low']

### 🔍 Count Missing Audience Scores

- 🧪 **`np.isnan(AudienceScore)`** checks each value to see whether it is **NaN (missing)**.
- 🔢 **`.sum()`** counts all the `True` values, giving the **total number of missing Audience Scores**.
- 🖨️ **`print()`** displays the number of missing values.

In [163]:
print(np.isnan(AudienceScore).sum())

63

### 🎬 Convert Movie Data into NumPy Arrays

- 🌍 **`WorldGross`** converts the `WorldGross` column into a NumPy array.
- 🎯 **`AudienceScore`** converts the `AudienceScore` column into a NumPy array.
- 🔢 **NumPy arrays** make it easy to perform statistical calculations such as mean, median, variance, and standard deviation.

In [164]:

WorldGross = np.array(df["WorldGross"])
AudienceScore = np.array(df["AudienceScore"])

### 🖨️ Display NumPy Arrays

- 🌍 **`WorldGross`** contains the worldwide gross values of the movies.
- 🎯 **`AudienceScore`** contains the audience score values of the movies.
- 👀 **`print(WorldGross, AudienceScore)`** displays both NumPy arrays together.

In [165]:
print(WorldGross, AudienceScore)

[8.908700e+02 7.989600e+02 7.097100e+02 9.634200e+02 9.398900e+02
 5.853500e+02 4.428200e+02 4.573600e+02 3.613400e+02 4.560700e+02
 6.237200e+02 5.270700e+02 2.536200e+02 2.190800e+02 2.314100e+02
 2.580200e+02 3.835300e+02 2.890500e+02 2.664600e+02 3.404900e+02
 2.875900e+02 1.698700e+02 1.860700e+02 2.025500e+02 1.457100e+02
 3.113100e+02 2.287400e+02 1.734200e+02 1.693300e+02 1.593100e+02
 1.753700e+02 1.478800e+02 1.963900e+02 1.177600e+02 1.716300e+02
 3.722300e+02 1.190000e+02 1.393500e+02 7.551000e+01 1.490400e+02
 8.025000e+01 5.586000e+01 9.561000e+01 1.568300e+02 7.002000e+01
 1.525200e+02 1.459000e+02 9.299000e+01 8.415000e+01 8.666000e+01
 9.570000e+01 6.931000e+01 9.260000e+01 1.288800e+02 7.618000e+01
 8.687000e+01 9.997000e+01 7.550000e+01 1.355600e+02 6.979000e+01
 1.277700e+02 5.710000e+01 5.919000e+01 8.479000e+01 6.947000e+01
 5.493000e+01 4.812000e+01 4.774000e+01 3.067000e+01 5.729000e+01
 6.277000e+01 2.542000e+01 3.609000e+01 2.937000e+01 3.747000e+01
 3.530000e+01 2.218000e+01 5.625000e+01 2.058000e+01 7.607000e+01
 3.562000e+01 7.328000e+01 3.809000e+01 4.017000e+01 6.322000e+01
 1.820000e+01 2.682000e+01 3.508000e+01 1.756000e+01 7.511000e+01
 3.082000e+01 1.004560e+03 5.855200e+02 7.866400e+02 6.243900e+02
 5.213100e+02 6.317400e+02 6.039000e+02 3.926200e+02 5.860900e+02
 2.971400e+02 4.152500e+02 2.699600e+02 6.098400e+02 4.196700e+02
 3.779100e+02 2.634300e+02 3.414300e+02 2.306900e+02 1.637300e+02
 1.880700e+02 2.128700e+02 3.099800e+02 2.427200e+02 4.011300e+02
 2.419900e+02 1.780700e+02 1.281100e+02 1.999400e+02 2.232400e+02
 2.697800e+02 1.492800e+02 2.529100e+02 1.016200e+02 2.002800e+02
 1.579300e+02 2.193800e+02 2.222300e+02 1.707600e+02 3.339300e+02
 1.602600e+02 1.603900e+02 2.330900e+02 1.511600e+02 1.628400e+02
 1.112300e+02 9.238000e+01 1.634000e+02 1.051700e+02 1.637200e+02
 6.416000e+01 1.681700e+02 1.508200e+02 1.138600e+02 8.239000e+01
 1.279800e+02 8.695000e+01 7.044000e+01 1.000800e+02 2.113400e+02
 1.059600e+02 5.155000e+01 4.435000e+01 9.395000e+01 5.720000e+01
 1.132400e+02 4.365000e+01 4.198000e+01 8.437000e+01 8.542000e+01
 7.846000e+01 4.465000e+01 1.151000e+02 8.465000e+01 4.349000e+01
 3.880000e+01 3.995000e+01 3.711000e+01 7.568000e+01 1.130200e+02
 6.828000e+01 4.388000e+01 3.347000e+01 4.969000e+01 4.086000e+01
 5.545000e+01 5.459000e+01 1.089800e+02 4.132000e+01 3.351000e+01
 5.696000e+01 4.210000e+01 4.130000e+01 7.749000e+01 6.483000e+01
 6.482000e+01 5.266000e+01 5.001000e+01 4.585000e+01 7.771000e+01
 6.557000e+01 4.788000e+01 7.124000e+01 2.951000e+01 4.163000e+01
 2.766000e+01 9.641000e+01 7.211000e+01 6.837000e+01 2.641000e+01
 2.767000e+01 3.075000e+01 4.162000e+01 5.091000e+01 3.903000e+01
 1.766000e+01 2.273000e+01 3.259000e+01 1.763000e+01 3.115000e+01
 4.249000e+01 3.482000e+01 4.331000e+01 1.542000e+01 2.707000e+01
 1.364000e+01 1.662000e+01 1.315000e+01 2.331000e+01 1.672000e+01
 1.233000e+01 5.065000e+01 1.177000e+01 3.058000e+01 2.221000e+01
 1.121000e+01 2.116000e+01 9.810000e+00 1.184000e+01 1.808000e+01
 4.042000e+01 1.876000e+01 8.880000e+00 1.010000e+01 9.320000e+00
 1.793000e+01 3.339000e+01 7.720000e+00 2.146000e+01 2.781500e+03
 8.363000e+02 9.340000e+02 7.098200e+02 7.313000e+02 4.674600e+02
 3.856500e+02 3.092000e+02 4.407000e+02 5.240200e+02 3.815000e+02
 8.866800e+02 3.731000e+02 4.130000e+02 7.696900e+02 3.147000e+02
 3.631000e+02 3.021000e+02 1.832800e+02 2.268000e+02 3.253300e+02
 4.859000e+02 3.720000e+02 2.430300e+02 3.214100e+02 2.851000e+02
 2.107700e+02 2.191000e+02 1.718300e+02 1.933600e+02 1.853000e+02
 2.670400e+02 2.141000e+02 1.265700e+02 1.788400e+02 2.052800e+02
 2.002000e+02 1.835800e+02 1.555500e+02 1.000800e+02 1.023900e+02
 1.245800e+02 1.264800e+02 1.182000e+02 2.611900e+02 9.140000e+01
 7.382000e+01 1.063800e+02 1.861900e+02 1.501600e+02 9.140000e+01
 1.363000e+02 1.013300e+02 1.308000e+02 1.151500e+02 7.752000e+01
 1.022200e+02 7.158000e+01 1.007300e+02 9.675000e+01 6.877000e+01
 9.571000e+01 9.135000e+01 1.083000e+02 9.351000e+01 6.235000e+01
 7.651000e+01 1.056400e+02 9.080000e+01 7.669000e+01 7.814000e+01
 1.224300e+02 6.159000e+01 1.222300e+02 8.830000e+01 4.436000e+01
 7.594000e+01 4.012000e+01 3.941000e+01 4.176000e+01 6.894000e+01
 6.072000e+01 4.885000e+01 4.841000e+01 3.831000e+01 8.528000e+01
 3.120000e+01 4.270000e+01 4.327000e+01 6.819000e+01 3.143000e+01
 4.770000e+01 6.010000e+01 5.788000e+01 2.696000e+01 3.608000e+01
 7.721000e+01 4.646000e+01 4.082000e+01 5.399000e+01 3.989000e+01
 3.240000e+01 6.244000e+01 1.860000e+01 4.922000e+01 3.155000e+01
 2.299000e+01 1.716000e+01 1.600000e+01 2.283000e+01 3.338000e+01
 1.582000e+01 1.920000e+01 3.923000e+01 3.450000e+01 1.600000e+01
 2.609000e+01 1.728000e+01 1.657000e+01 2.721000e+01 1.083000e+01
 1.070000e+01 1.700000e+01 1.220000e+01 1.000000e+01 1.489000e+01
 5.823000e+01 3.143000e+01 1.640000e+01 1.234000e+01 1.801000e+01
 3.634000e+01 2.763000e+01 9.980000e+00 6.380000e+00 3.509000e+01
 1.210000e+01 6.073000e+01 1.156700e+02 1.025466e+03 4.012000e+01
 5.050700e+01 3.293970e+02 3.643900e+01 1.914800e+01 8.951900e+01
 2.819000e+01 1.124900e+02 4.818800e+01 7.874000e+00 4.932140e+02
 9.710000e+00 5.558800e+01 2.052800e+01 9.920000e+00 1.522630e+02
 5.141000e+01 1.149700e+02 4.905000e+01 5.431130e+02 6.269400e+01
 7.570000e+01 8.685500e+01 2.117800e+02 7.495000e+01 2.045900e+02
 8.112000e+01 1.514000e+01 3.562600e+01 5.504900e+01 5.282900e+01
 3.623600e+01 9.125700e+01 4.205000e+01 9.487800e+01 6.150000e+00
 2.714300e+02 2.373820e+02 9.593000e+02 6.457100e+01 4.948800e+02
 2.072200e+01 8.255360e+02 6.239300e+02 1.716850e+02 1.091000e+01
 2.156900e+01 9.618800e+01 9.816000e+01 2.619270e+02 3.260800e+01
 1.400730e+02 6.792000e+01 7.917900e+01 5.337400e+01 3.106490e+02
 1.028020e+02 9.327000e+00 4.408900e+01 8.375700e+01 3.218840e+02
 6.003900e+01 2.097100e+01 9.324000e+01 9.450000e+00 2.141300e+01
 1.775110e+02 2.265000e+02 8.318800e+01 4.309000e+00 1.272320e+02
 3.363650e+02 1.990060e+02 5.603400e+01 1.841000e+01 2.962200e+02
 3.216690e+02 2.935020e+02 1.361500e+02 4.766000e+01 2.883470e+02
 4.977800e+01 7.526040e+02 2.948020e+02 6.681700e+01 5.178000e+00
 1.592910e+02 9.479000e+00 6.905000e+01 5.917940e+02 1.772360e+02
 6.787500e+01 7.747700e+01 1.571070e+02 1.363330e+02 4.156850e+02
 5.480300e+01 2.744690e+02 1.291540e+02 6.022000e+01 1.970000e+00
 3.591200e+02 3.470400e+01 4.142040e+02 3.197130e+02 6.773300e+01
 8.904000e+01 2.938000e+01 6.745000e+01 1.704310e+02 4.677000e+00
 2.249190e+02 2.152800e+02 4.523900e+01 4.983100e+01 2.783460e+02
 1.540250e+02 6.984890e+02 1.397900e+02 1.124600e+02 1.063160e+03
 4.000620e+02 2.522730e+02 1.678020e+02 2.164850e+02 8.054600e+01
 1.347430e+02 4.304000e+01 6.067000e+01 2.015840e+02 3.200300e+01
 3.426700e+01 1.964900e+01 4.055000e+01 3.919000e+01 2.746000e+01
 3.539000e+01 8.209000e+01 1.539000e+01 1.770000e+00 2.556000e+01
 4.574000e+01 1.474100e+02 1.750000e+02 2.162000e+02 2.118200e+02
 4.317000e+01 1.431000e+01 2.883800e+02 3.705700e+02 5.598500e+02
 6.860000e+00 6.097000e+01 4.880000e+01 1.354600e+02 1.748200e+02
 1.428500e+02 7.242000e+01 9.541000e+01 3.699000e+01 3.850000e+01
 7.617000e+01 2.893000e+01 4.630000e+00 2.710000e+00 5.524700e+01
 6.261300e+02 1.578900e+02 6.354000e+01 1.495400e+02 4.100000e+01
 1.939700e+02 2.198500e+02 8.316000e+01 6.378000e+01 1.504100e+02
 1.341510e+03 1.839500e+02 2.096400e+02 1.857690e+02 1.498800e+02
 2.269000e+02 1.739300e+02 9.701000e+01 8.461000e+01 1.496800e+02
 1.600800e+02 2.149500e+02 5.638000e+01 6.656900e+02 7.201000e+01
 1.618500e+02 1.100000e+00 1.950000e+01 3.899000e+01 1.511200e+02
 6.947100e+02 1.102000e+02 3.967000e+01 1.873600e+02 3.506000e+01
 1.420400e+02 1.492300e+02 5.939000e+01 2.482000e+01 2.070400e+02
 9.798000e+01 1.045710e+03 7.831000e+01 5.549900e+02 2.457200e+02
 2.992700e+02 8.916000e+01 1.100000e+00 4.846300e+02 4.817400e+02
 1.086100e+02 9.714000e+01 9.163000e+01 1.687400e+01 4.014000e+01
 5.454500e+02 6.018000e+01 4.709000e+01 1.473300e+02 8.556000e+01
 8.979000e+01 2.601000e+02 6.930000e+00 3.130000e+00 1.278700e+02
 3.739930e+02 1.334320e+02 6.370000e+00 7.450000e+00 7.545000e+01
 4.880000e+00 1.548000e+01 4.564000e+01 1.772400e+02 6.972000e+01
 2.712000e+01 2.321610e+02 2.278200e+02 5.867600e+02 2.166400e+02
 7.599000e+01 1.149550e+02 7.501000e+01 5.107000e+01 1.651800e+02
 9.605000e+01 4.049000e+01 2.395000e+01 3.494100e+01 5.637500e+02
 2.743000e+01 1.322700e+02 5.430000e+01 4.493200e+02 8.063000e+01
 1.529200e+02 1.123790e+03 7.121700e+02 1.307900e+02 1.775840e+02
 2.306000e+01 1.170900e+02 1.200810e+02 3.043000e+01 3.315000e+01
 3.536200e+02 2.486000e+01 1.698500e+02 2.015900e+02          nan
          nan 1.164700e+02          nan          nan 2.349900e+02
          nan 6.893000e+01 3.549000e+01 2.323300e+02          nan
          nan 3.030300e+02 1.280000e+01 2.472000e+01 5.389800e+02
          nan          nan          nan          nan 3.716000e+01
 1.266400e+02 1.304800e+02 9.626000e+01          nan          nan
 2.455300e+02 7.711000e+01 4.253700e+02 3.488400e+02 3.563000e+01
          nan 4.813000e+01          nan          nan 1.617700e+02
          nan          nan 8.149000e+01          nan 1.325600e+02
          nan          nan 3.337000e+01          nan 1.142800e+02
 3.583800e+02 3.946000e+01          nan          nan          nan
 8.772400e+02          nan 2.183400e+02          nan          nan
 2.841400e+02 3.352600e+02 3.273000e+01          nan          nan
 3.793000e+01          nan 5.368000e+01 4.418100e+02 6.090200e+02
 2.752900e+02 1.765100e+02 7.469200e+02 1.672200e+02 4.622000e+01
          nan 1.518590e+03 6.240300e+02 1.661700e+02          nan
 2.275000e+01          nan          nan 1.428400e+02 1.071400e+02
 1.197700e+02 1.130400e+02 3.108000e+01 4.033500e+02          nan
          nan 4.481000e+01 5.037000e+01 2.401600e+02 3.069400e+02
          nan 5.942000e+01          nan          nan 4.035000e+01
 2.080800e+02          nan 3.456000e+01          nan 8.297000e+01
          nan          nan 1.942000e+01 2.364100e+02          nan
 7.771000e+01 1.108560e+03          nan 3.965900e+02 2.464000e+01
 1.404700e+02 3.761400e+02          nan 5.493700e+02 5.772000e+01
 7.522200e+02          nan 1.368400e+02 2.761400e+02 6.649000e+01
 1.049100e+02          nan          nan 1.084440e+03 1.017600e+02
 1.793800e+02 3.054300e+02 5.391000e+01 7.728000e+01 4.186000e+01
 1.017000e+03 6.912500e+02 1.802700e+02 9.936000e+01 2.826000e+01
 3.338000e+01 1.230500e+02 8.545000e+01          nan          nan
          nan 5.482000e+01 8.296900e+02 1.961100e+02 6.827000e+01
 1.277300e+02 8.806000e+01 1.984700e+02 1.601100e+02 8.438000e+01
          nan 3.052700e+02 4.712200e+02          nan 1.328200e+02
 8.710000e+01 8.560000e+00 4.622000e+01 3.570000e+00 2.469800e+02
 2.438400e+02 2.164900e+02 1.333800e+02 1.221300e+02 1.208000e+01
 1.131900e+02 1.002000e+01 1.320000e+00 1.215440e+03 9.647600e+02
 8.559000e+02 8.473300e+02 8.104000e+02 7.886800e+02 7.435600e+02
 6.885100e+02 6.680500e+02 6.329100e+02 5.872000e+02 5.400100e+02
 4.933100e+02 4.673700e+02 4.148300e+02 4.110000e+02 3.757400e+02
 3.620000e+02 3.517200e+02 3.510400e+02 3.475500e+02 3.180000e+02
 3.046500e+02 2.861700e+02 2.861400e+02 2.825700e+02 2.699900e+02
 2.684300e+02 2.605000e+02 2.577700e+02 2.299300e+02 2.257000e+02
 2.197900e+02 2.053700e+02 1.998500e+02 1.976900e+02 1.756100e+02
 1.739700e+02 1.690400e+02 1.677100e+02 1.655000e+02 1.624000e+02
 1.615000e+02 1.610300e+02 1.490000e+02 1.464300e+02 1.420800e+02
 1.319400e+02 1.281800e+02 1.260400e+02 1.217600e+02 1.177400e+02
 1.169800e+02 1.122300e+02 1.052000e+02 9.834000e+01 9.754000e+01
 9.502000e+01 9.480000e+01 9.391000e+01 9.349000e+01 9.126000e+01
 9.084000e+01 9.057000e+01 9.025000e+01 8.933000e+01 8.618000e+01
 8.487000e+01 8.403000e+01 7.838000e+01 7.832000e+01 7.163000e+01
 7.135000e+01 7.024000e+01 6.857000e+01 6.337000e+01 6.268000e+01
 6.005000e+01 5.994000e+01 5.956000e+01 5.952000e+01 4.833000e+01
 4.823000e+01 4.609000e+01 4.558000e+01 4.293000e+01 3.593000e+01
 3.549000e+01 3.546000e+01 3.172000e+01 3.136000e+01 3.133000e+01
 3.085000e+01 3.045000e+01 3.037000e+01 2.993000e+01 2.924000e+01
 2.726000e+01 2.642000e+01 2.442000e+01 2.426000e+01 2.321000e+01
 2.320000e+01 2.246000e+01 2.182000e+01 2.042000e+01 1.970000e+01
 1.915000e+01 1.807000e+01 1.801000e+01 1.703000e+01 1.655000e+01
 1.518000e+01 1.501000e+01 1.379000e+01 1.172000e+01 1.172000e+01
 1.133000e+01 1.118000e+01 1.050000e+01 9.490000e+00 7.450000e+00
 7.370000e+00 7.040000e+00 6.850000e+00 6.260000e+00 5.750000e+00
 5.130000e+00 4.860000e+00 4.070000e+00 3.350000e+00 3.310000e+00
 2.960000e+00 2.400000e+00 2.340000e+00 2.290000e+00 2.160000e+00
 1.970000e+00 1.380000e+00 1.350000e+00          nan 1.677400e+02
 1.900000e-01 1.000000e-01 1.400000e-01 1.520000e+00] [54. 57. 89. 74. 82. 69. 91. 72. 73. 90. 84. 78. 72. 83. 89. 68. 86. 55.
 87. 80. 57. 87. 73. 84. 66. 74. 56. 56. 75. 56. 81. 75. 52. 75. 84. 55.
 73. 70. 83. 64. 64. 47. 63. 82. 85. 81. 70. 72. 55. 78. 82. 55. 64. 37.
 84. 38. 61. 57. 86. 65. 41. 64. 61. 73. 56. 63. 75. 52. 61. 64. 53. 86.
 87. 84. 50. 46. 67. 90. 55. 59. 45. 85. 43. 43. 48. 63. 66. 79. 72. 44.
 41. 96. 91. 59. 67. 89. 83. 73. 82. 62. 75. 81. 90. 76. 78. 90. 75. 72.
 73. 52. 69. 63. 76. 77. 40. 55. 72. 68. 50. 72. 44. 56. 76. 74. 66. 73.
 72. 50. 67. 81. 71. 70. 34. 61. 67. 53. 75. 29. 75. 64. 59. 77. 81. 63.
 48. 65. 46. 54. 50. 69. 61. 56. 67. 61. 46. 70. 64. 36. 56. 36. 44. 44.
 65. 31. 65. 59. 78. 36. 69. 84. 46. 41. 51. 49. 38. 72. 88. 58. 46. 67.
 51. 70. 41. 49. 37. 74. 56. 41. 36. 65. 62. 40. 36. 42. 37. 66. 73. 32.
 34. 51. 55. 42. 51. 75. 29. 26. 32. 51. 44. 54. 33. 28. 68. 22. 60. 78.
 61. nan 37. 70. 42. 42. 39. 57. 47. 27. 74. 73. 41. 83. 84. 61. 64. 47.
 68. 48. 85. 42. 47. 92. 76. 75. 78. 86. 87. 91. 90. 59. 81. 65. 72. 72.
 60. 63. 74. 76. 62. 50. 83. 72. 65. 64. 70. 87. 50. 81. 63. 47. 56. 68.
 72. 65. 69. 60. 68. 76. 50. 66. 59. 87. 77. 77. 57. 82. 72. 50. 50. 52.
 60. 52. 70. 65. 48. 56. 51. 47. 58. 48. 49. 38. 73. 68. 53. 57. 31. 39.
 45. 61. 65. 38. 42. 57. 74. 71. 66. 47. 35. 45. 42. 43. 81. 47. 58. 59.
 31. 48. 52. 62. 67. 35. 44. 39. 46. 40. 40. 43. 80. 43. 40. 53. 47. 51.
 52. 83. 37. 44. 56. 34. 50. 27. 38. 35. 50. 54. 73. 78. 52. 59. 38. 37.
 66. 49. 28. 27. 74. 28. 64. 55. 28. 43. 72. 65. 48. 31. 63. 60. 84. 40.
 72. 35. 41. 86. 47. 63. 66. 42. 43. 62. 77. 48. 71. 45. 56. 51. 58. 50.
 66. 48. 81. 45. 49. 47. 56. 75. 46. 56. 55. 50. 73. 57. 36. 63. 56. 60.
 40. 59. 31. 87. 57. 90. 57. 93. 80. 72. 24. 58. 83. 45. 52. 49. 65. 36.
 62. 62. 40. 55. 33. 66. 46. 73. 54. 29. 54. 70. 49. nan 57. 45. 62. 52.
 71. 72. 70. 43. 53. 59. 62. 47. 83. 49. 60. 64. 73. 19. 47. 67. 20. 57.
 88. 71. 37. 47. 68. 41. 63. 54. 58. 88. 68. 47. 75. 72. 93. 42. 32. 66.
 55. 66. 57. 56. 89. 57. 46. 44. 44. 83. 74. 38. 46. 91. 67. 86. 73. 54.
 32. 43. 44. 67. 36. 45. 35. 52. 48. 93. 89. 71. 46. 66. 74. 31. 49. 82.
 62. 38. 50. 50. 80. 77. 75. 56. 61. 55. 34. 63. 50. 81. 63. 81. 37. 38.
 79. 38. 28. 53. 62. 83. 56. 71. 68. 68. 52. 48. 44. 67. 59. 92. 50. 72.
 84. 57. 59. 55. 65. 84. 59. 55. 63. 48. 80. 46. 73. 71. 73. 43. 84. 86.
 89. 50. 54. 84. 48. 57. 54. 79. 58. 70. 61. 37. 76. 69. 81. 41. 59. 73.
 87. 39. 57. 32. 80. 25. 79. nan 79. 81. 40. 48. 78. 46. 85. 67. 78. 91.
 57. 62. 53. 55. 65. 70. 88. 31. 43. 89. 47. 58. 91. 76. 54. 82. 52. 87.
 43. 29. 48. 43. 50. 52. 48. 61. 80. 68. 61. 67. 68. 57. 73. 93. 72. 79.
 50. 79. 88. 36. 42. 82. nan nan 51. nan nan 63. nan 51. 63. 90. nan nan
 55. 76. 64. 76. nan nan nan nan 29. 71. 67. 58. nan nan 46. 64. 92. 64.
 72. nan 86. nan nan 75. nan nan 70. nan 32. nan nan 40. nan 56. 72. 42.
 nan nan nan 63. nan 67. nan nan 60. 60. 73. nan nan 44. nan 75. 79. 85.
 81. 82. 73. 61. 52. nan 91. 71. 45. nan 86. nan nan 36. 72. 61. 83. 60.
 69. nan nan 52. 58. 51. 81. nan 55. nan nan 60. 64. nan 64. nan 55. nan
 nan 71. 86. nan 61. 86. nan 52. 65. 69. 54. nan 74. 53. 77. nan 79. 58.
 73. 51. nan nan 90. 22. 45. 68. 52. 61. 40. 83. 81. 85. 68. 59. 89. 60.
 49. nan nan nan 49. 71. 63. 40. 55. 51. 47. 62. 48. nan 49. 87. nan 80.
 83. 40. 49. 48. 55. 38. 92. 59. 88. 61. 41. 60. 77. 80. 85. 92. 85. 89.
 84. 83. 85. 76. 83. 79. 73. 57. 90. 70. 78. 49. 45. 71. 68. 58. 83. 42.
 61. 60. 67. 73. 66. 55. 66. 73. 54. 51. 63. 58. 56. 83. 55. 76. 80. 62.
 79. 60. 68. 66. 57. 64. 68. 92. 73. 56. 62. 74. 72. 59. 56. 64. 86. 81.
 nan 54. 89. 47. 61. 92. 37. 48. 91. 48. 41. 39. 90. 68. 25. 66. 71. 34.
 34. 54. 62. 65. 55. 50. 73. 49. 63. 85. 75. 72. 39. 66. 52. 92. 64. 85.
 25. 57. 73. 50. 78. 64. 76. 85. 56. 42. 76. 42. 34. 48. 34. 92. 52. 27.
 39. nan 38. 86. 53. 82. 36. 41. 57. 87. 71. nan 66. 33. 45. 37. 78. 47.
 47. 74. 66. 79. 57. 60. 63. 35. 89. 78. 79. nan nan 53. 37.]

### 📊🎬 Audience Score Statistics

- 📈 **Mean Rating:** `np.mean(AudienceScore)` calculates the **average audience score**.
- 🎯 **Median Rating:** `np.median(AudienceScore)` finds the **middle audience score**.
- 🔻 **Minimum Rating:** `np.min(AudienceScore)` finds the **lowest audience score**.
- 🔝 **Maximum Rating:** `np.max(AudienceScore)` finds the **highest audience score**.
- 🧮 These functions provide a quick statistical summary of the movie audience ratings.

In [166]:
print("Mean Rating:", np.mean(AudienceScore))
print("Median Rating:", np.median(AudienceScore))
print("Minimum Rating:", np.min(AudienceScore))
print("Maximum Rating:", np.max(AudienceScore))

Mean Rating: nan
Median Rating: nan
Minimum Rating: nan
Maximum Rating: nan

### 📊 Calculate Variance & Standard Deviation

- 📈 **Variance:** `np.var(AudienceScore)` calculates how much the audience scores are spread around their average.
- 📏 **Standard Deviation:** `np.std(AudienceScore)` measures the overall spread of audience scores.
- 🔢 **Higher value:** More variation in the audience scores.
- 📉 **Lower value:** Audience scores are closer to the average.

In [167]:
print("Variance:", np.var(AudienceScore))
print("Standard Deviation:", np.std(AudienceScore))

Variance: nan
Standard Deviation: nan

### 📊 Calculate Percentiles of Audience Score

- 🔹 **25th Percentile:** `np.percentile(AudienceScore, 25)` finds the value below which **25% of the audience scores** fall.
- 🔸 **50th Percentile:** `np.percentile(AudienceScore, 50)` gives the **median** of the audience scores.
- 🔹 **75th Percentile:** `np.percentile(AudienceScore, 75)` finds the value below which **75% of the audience scores** fall.
- 📈 **Percentiles** help us understand the distribution and spread of movie audience scores.

In [168]:
print("25th Percentile:", np.percentile(AudienceScore, 25))
print("50th Percentile:", np.percentile(AudienceScore, 50))
print("75th Percentile:", np.percentile(AudienceScore, 75))

25th Percentile: nan
50th Percentile: nan
75th Percentile: nan

### 📊 Calculate Quartiles & IQR

- 🔹 **Q1 (25th Percentile):** `np.percentile(AudienceScore, 25)` finds the value below which 25% of the scores fall.
- 🔹 **Q3 (75th Percentile):** `np.percentile(AudienceScore, 75)` finds the value below which 75% of the scores fall.
- 📏 **IQR:** `Q3 - Q1` calculates the **Interquartile Range**, which represents the spread of the middle 50% of audience scores.
- 🖨️ **Print:** Displays Q1, Q3, and IQR values.

In [169]:
Q1 = np.percentile(AudienceScore, 25)
Q3 = np.percentile(AudienceScore, 75)

IQR = Q3 - Q1

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

Q1: nan
Q3: nan
IQR: nan

### 🚨 Detect Outliers Using IQR Method

- 🧹 **Remove Missing Values:** `~np.isnan(AudienceScore)` removes `NaN` values before calculating quartiles.
- 🔹 **Q1:** Calculates the 25th percentile of the valid audience scores.
- 🔹 **Q3:** Calculates the 75th percentile of the valid audience scores.
- 📏 **IQR:** `Q3 - Q1` calculates the Interquartile Range.
- ⬇️ **Lower Limit:** `Q1 - 1.5 × IQR` defines the lower boundary for detecting outliers.
- ⬆️ **Upper Limit:** `Q3 + 1.5 × IQR` defines the upper boundary for detecting outliers.
- 🚨 **Outliers:** Scores below the lower limit or above the upper limit are identified as outliers.
- 🔢 **Number of Outliers:** `len(outliers)` counts the total number of outlier scores.

In [170]:
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

scores = AudienceScore[~np.isnan(AudienceScore)]
Q1 = np.percentile(scores, 25)
Q3 = np.percentile(scores, 75)
IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = scores[(scores < lower_limit) | (scores > upper_limit)]

print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)
print("Outliers:", outliers)
print("Number of Outliers:", len(outliers))

print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)
print("Outliers:", outliers)
print("Number of Outliers:", len(outliers))

Lower Limit: 11.5
Upper Limit: 111.5
Outliers: []
Number of Outliers: 0
Lower Limit: 11.5
Upper Limit: 111.5
Outliers: []
Number of Outliers: 0

### 🔍 Check Missing Values in Movie Data

- 🌍 **Missing WorldGross:** `np.isnan(WorldGross).sum()` counts the total number of missing (`NaN`) values in the worldwide gross data.
- 🎯 **Missing AudienceScore:** `np.isnan(AudienceScore).sum()` counts the total number of missing (`NaN`) values in the audience score data.
- 🔢 **`.sum()`** counts how many `True` values are returned by `np.isnan()`.
- 🧹 This helps identify missing data before performing statistical analysis.

In [171]:
print("Missing WorldGross:", np.isnan(WorldGross).sum())
print("Missing AudienceScore:", np.isnan(AudienceScore).sum())

Missing WorldGross: 56
Missing AudienceScore: 63

### 🏆🎬 Find Movie with Highest Rating

- 🎯 **`Rating = AudienceScore`** stores the audience scores in the `Rating` variable.
- 🔝 **`np.argmax(Rating)`** finds the index of the movie with the **highest rating**.
- 🎬 **`df.iloc[index]["Movie"]`** gets the movie name at that index.
- ⭐ **`Rating[index]`** gets the highest audience score.
- 🖨️ **`print()`** displays the movie name and its rating.

In [172]:
Rating = AudienceScore
index = np.argmax(Rating)

print("Movie:", df.iloc[index]["Movie"])
print("Rating:", Rating[index])

Movie: The Pirates Who Don't Do Anything
Rating: nan

### 💰🏆 Find Movie with Highest Worldwide Revenue

- 🌍 **`WorldGross`** contains the worldwide gross/revenue values of the movies.
- 🔝 **`np.argmax(WorldGross)`** finds the index of the movie with the **highest worldwide revenue**.
- 🎬 **`df.iloc[index]["Movie"]`** gets the movie name at that index.
- 💰 **`WorldGross[index]`** gets the highest revenue value.
- 🖨️ **`print()`** displays the movie name and its revenue.

In [173]:
index = np.argmax(WorldGross)

print("Movie:", df.iloc[index]["Movie"])
print("Revenue:", WorldGross[index])

Movie: A Late Quartet
Revenue: nan

### 💰🏆 Find Movie with Highest Worldwide Revenue

- 🌍 **`WorldGross`** contains the worldwide revenue values of all movies.
- 🔝 **`np.argmax(WorldGross)`** finds the index of the movie with the **highest revenue**.
- 🎬 **`df.iloc[index]["Movie"]`** retrieves the movie name from that index.
- 💰 **`WorldGross[index]`** retrieves the highest worldwide revenue.
- 🖨️ **`print()`** displays the movie name and revenue.

In [174]:
index = np.argmax(WorldGross)

print("Movie:", df.iloc[index]["Movie"])
print("Revenue:", WorldGross[index])

Movie: A Late Quartet
Revenue: nan

### 🎬⭐ Categorize Movies by Rating

- 🏆 **Rating ≥ 8:** Movie is classified as **"Excellent"**.
- ⭐ **Rating ≥ 6:** Movie is classified as **"Average"**.
- 📉 **Rating < 6:** Movie is classified as **"Low"**.
- 🔀 **Nested `np.where()`** applies multiple conditions to categorize each movie.
- 🖨️ **`print()`** displays the rating category for every movie.

In [175]:
rating_category = np.where(
    Rating >= 8,
    "Excellent",
    np.where(
        Rating >= 6,
        "Average",
        "Low"
    )
)

print(rating_category)

['Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Low' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Low' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Low' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Low' 'Low' 'Excellent' 'Low' 'Low' 'Excellent' 'Low' 'Excellent'
 'Excellent' 'Excellent' 'Low' 'Low' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Low' 'Low' 'Low' 'Low' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Low' 'Low' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Low' 'Excellent' 'Low' 'Low' 'Excellent' 'Low' 'Low'
 'Excellent' 'Low' 'Excellent' 'Low' 'Low' 'Excellent' 'Low' 'Excellent'
 'Excellent' 'Excellent' 'Low' 'Low' 'Low' 'Excellent' 'Low' 'Excellent'
 'Low' 'Low' 'Excellent' 'Excellent' 'Excellent' 'Low' 'Low' 'Excellent'
 'Low' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Low' 'Excellent' 'Excellent'
 'Excellent' 'Low' 'Excellent' 'Low' 'Low' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Low' 'Low' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Low' 'Excellent' 'Low' 'Low'
 'Excellent' 'Excellent' 'Low' 'Excellent' 'Low' 'Excellent' 'Low' 'Low'
 'Excellent' 'Excellent' 'Low' 'Excellent' 'Excellent' 'Low' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Low' 'Excellent' 'Excellent'
 'Excellent' 'Low' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Low'
 'Low' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Low' 'Low' 'Low'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Low' 'Excellent' 'Excellent' 'Low'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Low' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Low' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Low' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent' 'Excellent'
 'Low' 'Low' 'Excellent' 'Excellent']

### 🎬📊 Categorize Movies by Audience Score

- 🏆 **Audience Score ≥ 80:** Movie is classified as **"Hit"**.
- ⭐ **Audience Score ≥ 60:** Movie is classified as **"Average"**.
- 📉 **Audience Score < 60:** Movie is classified as **"Low"**.
- 🔀 **Nested `np.where()`** applies multiple conditions to categorize every movie.
- 🖨️ **`print()`** displays the category of each movie.

In [176]:
audience_category = np.where(
    AudienceScore >= 80,
    "Hit",
    np.where(
        AudienceScore >= 60,
        "Average",
        "Low"
    )
)

print(audience_category)

['Low' 'Low' 'Hit' 'Average' 'Hit' 'Average' 'Hit' 'Average' 'Average'
 'Hit' 'Hit' 'Average' 'Average' 'Hit' 'Hit' 'Average' 'Hit' 'Low' 'Hit'
 'Hit' 'Low' 'Hit' 'Average' 'Hit' 'Average' 'Average' 'Low' 'Low'
 'Average' 'Low' 'Hit' 'Average' 'Low' 'Average' 'Hit' 'Low' 'Average'
 'Average' 'Hit' 'Average' 'Average' 'Low' 'Average' 'Hit' 'Hit' 'Hit'
 'Average' 'Average' 'Low' 'Average' 'Hit' 'Low' 'Average' 'Low' 'Hit'
 'Low' 'Average' 'Low' 'Hit' 'Average' 'Low' 'Average' 'Average' 'Average'
 'Low' 'Average' 'Average' 'Low' 'Average' 'Average' 'Low' 'Hit' 'Hit'
 'Hit' 'Low' 'Low' 'Average' 'Hit' 'Low' 'Low' 'Low' 'Hit' 'Low' 'Low'
 'Low' 'Average' 'Average' 'Average' 'Average' 'Low' 'Low' 'Hit' 'Hit'
 'Low' 'Average' 'Hit' 'Hit' 'Average' 'Hit' 'Average' 'Average' 'Hit'
 'Hit' 'Average' 'Average' 'Hit' 'Average' 'Average' 'Average' 'Low'
 'Average' 'Average' 'Average' 'Average' 'Low' 'Low' 'Average' 'Average'
 'Low' 'Average' 'Low' 'Low' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Low' 'Average' 'Hit' 'Average' 'Average' 'Low' 'Average'
 'Average' 'Low' 'Average' 'Low' 'Average' 'Average' 'Low' 'Average' 'Hit'
 'Average' 'Low' 'Average' 'Low' 'Low' 'Low' 'Average' 'Average' 'Low'
 'Average' 'Average' 'Low' 'Average' 'Average' 'Low' 'Low' 'Low' 'Low'
 'Low' 'Average' 'Low' 'Average' 'Low' 'Average' 'Low' 'Average' 'Hit'
 'Low' 'Low' 'Low' 'Low' 'Low' 'Average' 'Hit' 'Low' 'Low' 'Average' 'Low'
 'Average' 'Low' 'Low' 'Low' 'Average' 'Low' 'Low' 'Low' 'Average'
 'Average' 'Low' 'Low' 'Low' 'Low' 'Average' 'Average' 'Low' 'Low' 'Low'
 'Low' 'Low' 'Low' 'Average' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low'
 'Low' 'Average' 'Low' 'Average' 'Average' 'Average' 'Low' 'Low' 'Average'
 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Average' 'Average' 'Low' 'Hit' 'Hit'
 'Average' 'Average' 'Low' 'Average' 'Low' 'Hit' 'Low' 'Low' 'Hit'
 'Average' 'Average' 'Average' 'Hit' 'Hit' 'Hit' 'Hit' 'Low' 'Hit'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Low' 'Hit' 'Average' 'Average' 'Average' 'Average' 'Hit' 'Low'
 'Hit' 'Average' 'Low' 'Low' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Low' 'Average' 'Low' 'Hit' 'Average'
 'Average' 'Low' 'Hit' 'Average' 'Low' 'Low' 'Low' 'Average' 'Low'
 'Average' 'Average' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low'
 'Average' 'Average' 'Low' 'Low' 'Low' 'Low' 'Low' 'Average' 'Average'
 'Low' 'Low' 'Low' 'Average' 'Average' 'Average' 'Low' 'Low' 'Low' 'Low'
 'Low' 'Hit' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Average' 'Average' 'Low'
 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Hit' 'Low' 'Low' 'Low' 'Low' 'Low'
 'Low' 'Hit' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low'
 'Average' 'Average' 'Low' 'Low' 'Low' 'Low' 'Average' 'Low' 'Low' 'Low'
 'Average' 'Low' 'Average' 'Low' 'Low' 'Low' 'Average' 'Average' 'Low'
 'Low' 'Average' 'Average' 'Hit' 'Low' 'Average' 'Low' 'Low' 'Hit' 'Low'
 'Average' 'Average' 'Low' 'Low' 'Average' 'Average' 'Low' 'Average' 'Low'
 'Low' 'Low' 'Low' 'Low' 'Average' 'Low' 'Hit' 'Low' 'Low' 'Low' 'Low'
 'Average' 'Low' 'Low' 'Low' 'Low' 'Average' 'Low' 'Low' 'Average' 'Low'
 'Average' 'Low' 'Low' 'Low' 'Hit' 'Low' 'Hit' 'Low' 'Hit' 'Hit' 'Average'
 'Low' 'Low' 'Hit' 'Low' 'Low' 'Low' 'Average' 'Low' 'Average' 'Average'
 'Low' 'Low' 'Low' 'Average' 'Low' 'Average' 'Low' 'Low' 'Low' 'Average'
 'Low' 'Low' 'Low' 'Low' 'Average' 'Low' 'Average' 'Average' 'Average'
 'Low' 'Low' 'Low' 'Average' 'Low' 'Hit' 'Low' 'Average' 'Average'
 'Average' 'Low' 'Low' 'Average' 'Low' 'Low' 'Hit' 'Average' 'Low' 'Low'
 'Average' 'Low' 'Average' 'Low' 'Low' 'Hit' 'Average' 'Low' 'Average'
 'Average' 'Hit' 'Low' 'Low' 'Average' 'Low' 'Average' 'Low' 'Low' 'Hit'
 'Low' 'Low' 'Low' 'Low' 'Hit' 'Average' 'Low' 'Low' 'Hit' 'Average' 'Hit'
 'Average' 'Low' 'Low' 'Low' 'Low' 'Average' 'Low' 'Low' 'Low' 'Low' 'Low'
 'Hit' 'Hit' 'Average' 'Low' 'Average' 'Average' 'Low' 'Low' 'Hit'
 'Average' 'Low' 'Low' 'Low' 'Hit' 'Average' 'Average' 'Low' 'Average'
 'Low' 'Low' 'Average' 'Low' 'Hit' 'Average' 'Hit' 'Low' 'Low' 'Average'
 'Low' 'Low' 'Low' 'Average' 'Hit' 'Low' 'Average' 'Average' 'Average'
 'Low' 'Low' 'Low' 'Average' 'Low' 'Hit' 'Low' 'Average' 'Hit' 'Low' 'Low'
 'Low' 'Average' 'Hit' 'Low' 'Low' 'Average' 'Low' 'Hit' 'Low' 'Average'
 'Average' 'Average' 'Low' 'Hit' 'Hit' 'Hit' 'Low' 'Low' 'Hit' 'Low' 'Low'
 'Low' 'Average' 'Low' 'Average' 'Average' 'Low' 'Average' 'Average' 'Hit'
 'Low' 'Low' 'Average' 'Hit' 'Low' 'Low' 'Low' 'Hit' 'Low' 'Average' 'Low'
 'Average' 'Hit' 'Low' 'Low' 'Average' 'Low' 'Hit' 'Average' 'Average'
 'Hit' 'Low' 'Average' 'Low' 'Low' 'Average' 'Average' 'Hit' 'Low' 'Low'
 'Hit' 'Low' 'Low' 'Hit' 'Average' 'Low' 'Hit' 'Low' 'Hit' 'Low' 'Low'
 'Low' 'Low' 'Low' 'Low' 'Low' 'Average' 'Hit' 'Average' 'Average'
 'Average' 'Average' 'Low' 'Average' 'Hit' 'Average' 'Average' 'Low'
 'Average' 'Hit' 'Low' 'Low' 'Hit' 'Low' 'Low' 'Low' 'Low' 'Low' 'Average'
 'Low' 'Low' 'Average' 'Hit' 'Low' 'Low' 'Low' 'Average' 'Average'
 'Average' 'Low' 'Low' 'Low' 'Low' 'Low' 'Average' 'Average' 'Low' 'Low'
 'Low' 'Low' 'Average' 'Hit' 'Average' 'Average' 'Low' 'Hit' 'Low' 'Low'
 'Average' 'Low' 'Low' 'Average' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low'
 'Average' 'Low' 'Low' 'Low' 'Low' 'Average' 'Low' 'Average' 'Low' 'Low'
 'Average' 'Average' 'Average' 'Low' 'Low' 'Low' 'Low' 'Average' 'Average'
 'Hit' 'Hit' 'Hit' 'Average' 'Average' 'Low' 'Low' 'Hit' 'Average' 'Low'
 'Low' 'Hit' 'Low' 'Low' 'Low' 'Average' 'Average' 'Hit' 'Average'
 'Average' 'Low' 'Low' 'Low' 'Low' 'Low' 'Hit' 'Low' 'Low' 'Low' 'Low'
 'Average' 'Average' 'Low' 'Average' 'Low' 'Low' 'Low' 'Low' 'Average'
 'Hit' 'Low' 'Average' 'Hit' 'Low' 'Low' 'Average' 'Average' 'Low' 'Low'
 'Average' 'Low' 'Average' 'Low' 'Average' 'Low' 'Average' 'Low' 'Low'
 'Low' 'Hit' 'Low' 'Low' 'Average' 'Low' 'Average' 'Low' 'Hit' 'Hit' 'Hit'
 'Average' 'Low' 'Hit' 'Average' 'Low' 'Low' 'Low' 'Low' 'Low' 'Average'
 'Average' 'Low' 'Low' 'Low' 'Low' 'Average' 'Low' 'Low' 'Low' 'Hit' 'Low'
 'Hit' 'Hit' 'Low' 'Low' 'Low' 'Low' 'Low' 'Hit' 'Low' 'Hit' 'Average'
 'Low' 'Average' 'Average' 'Hit' 'Hit' 'Hit' 'Hit' 'Hit' 'Hit' 'Hit' 'Hit'
 'Average' 'Hit' 'Average' 'Average' 'Low' 'Hit' 'Average' 'Average' 'Low'
 'Low' 'Average' 'Average' 'Low' 'Hit' 'Low' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Low' 'Average' 'Average' 'Low' 'Low' 'Average' 'Low'
 'Low' 'Hit' 'Low' 'Average' 'Hit' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Low' 'Average' 'Average' 'Hit' 'Average' 'Low' 'Average'
 'Average' 'Average' 'Low' 'Low' 'Average' 'Hit' 'Hit' 'Low' 'Low' 'Hit'
 'Low' 'Average' 'Hit' 'Low' 'Low' 'Hit' 'Low' 'Low' 'Low' 'Hit' 'Average'
 'Low' 'Average' 'Average' 'Low' 'Low' 'Low' 'Average' 'Average' 'Low'
 'Low' 'Average' 'Low' 'Average' 'Hit' 'Average' 'Average' 'Low' 'Average'
 'Low' 'Hit' 'Average' 'Hit' 'Low' 'Low' 'Average' 'Low' 'Average'
 'Average' 'Average' 'Hit' 'Low' 'Low' 'Average' 'Low' 'Low' 'Low' 'Low'
 'Hit' 'Low' 'Low' 'Low' 'Low' 'Low' 'Hit' 'Low' 'Hit' 'Low' 'Low' 'Low'
 'Hit' 'Average' 'Low' 'Average' 'Low' 'Low' 'Low' 'Average' 'Low' 'Low'
 'Average' 'Average' 'Average' 'Low' 'Average' 'Average' 'Low' 'Hit'
 'Average' 'Average' 'Low' 'Low' 'Low' 'Low']

### 🔗📊 Calculate Correlation

- ⭐ **`Rating`** contains the movie rating values.
- 💰 **`WorldGross`** contains the worldwide revenue values.
- 🔗 **`np.corrcoef(Rating, WorldGross)`** calculates the **correlation coefficient matrix** between Rating and WorldGross.
- 📈 A **positive correlation** means both values tend to increase together.
- 📉 A **negative correlation** means one tends to increase when the other decreases.
- ⚪ A value close to **0** means there is little linear relationship.
- 🖨️ **`print()`** displays the correlation matrix.

In [177]:
correlation = np.corrcoef(Rating, WorldGross)

print(correlation)

[[nan nan]
 [nan nan]]

### 🔗📊 Calculate Correlation Coefficient

- ⭐ **`Rating`** contains the movie rating values.
- 💰 **`WorldGross`** contains the worldwide revenue values.
- 🔗 **`np.corrcoef(Rating, WorldGross)`** creates the correlation matrix.
- 🎯 **`[0, 1]`** selects the correlation value between **Rating and WorldGross**.
- 📈 A value close to **+1** means strong positive correlation.
- 📉 A value close to **-1** means strong negative correlation.
- ⚪ A value close to **0** means little or no linear correlation.

In [178]:
print("Correlation:", np.corrcoef(Rating, WorldGross)[0, 1])

Correlation: nan

### 🔗📊 Create Correlation Matrix

- 🍅 **`RottenTomatoes`**, 🌍 **`WorldGross`**, and 🎯 **`AudienceScore`** are selected as numerical columns.
- 🔢 **`.to_numpy()`** converts the selected DataFrame columns into a NumPy array.
- 🔗 **`np.corrcoef()`** calculates the correlation between all numerical variables.
- 🔄 **`rowvar=False`** tells NumPy that **columns represent variables** and rows represent observations.
- 📊 **Correlation Matrix** shows the relationship between Rotten Tomatoes, World Gross, and Audience Score.
- 🖨️ **`print()`** displays the correlation matrix.

In [179]:
numeric_data = df[['RottenTomatoes', 'WorldGross', 'AudienceScore']].to_numpy()

correlation_matrix = np.corrcoef(numeric_data, rowvar=False)

print(correlation_matrix)

correlation_matrix = np.corrcoef(numeric_data, rowvar=False)

print(correlation_matrix)

[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]

### 🎬📊 Movie Data Statistics

- 📈 **Mean Rating:** `np.mean(Rating)` calculates the average movie rating.
- 🎯 **Median Rating:** `np.median(Rating)` finds the middle rating.
- 🔻 **Minimum Rating:** `np.min(Rating)` finds the lowest rating.
- 🔝 **Maximum Rating:** `np.max(Rating)` finds the highest rating.
- 📊 **Variance:** `np.var(Rating)` measures how widely the ratings are spread around the mean.
- 📏 **Standard Deviation:** `np.std(Rating)` measures the overall spread of movie ratings.
- 🔹 **25%:** `np.percentile(Rating, 25)` gives the 25th percentile (Q1).
- 🔸 **50%:** `np.percentile(Rating, 50)` gives the 50th percentile, which is the median (Q2).
- 🔹 **75%:** `np.percentile(Rating, 75)` gives the 75th percentile (Q3).

In [180]:
print("===== MOVIE DATA STATISTICS =====")

print("Mean Rating:", np.mean(Rating))
print("Median Rating:", np.median(Rating))
print("Minimum Rating:", np.min(Rating))
print("Maximum Rating:", np.max(Rating))
print("Variance:", np.var(Rating))
print("Standard Deviation:", np.std(Rating))

print("25%:", np.percentile(Rating, 25))
print("50%:", np.percentile(Rating, 50))
print("75%:", np.percentile(Rating, 75))

===== MOVIE DATA STATISTICS =====
Mean Rating: nan
Median Rating: nan
Minimum Rating: nan
Maximum Rating: nan
Variance: nan
Standard Deviation: nan
25%: nan
50%: nan
75%: nan